// Copyright 2026, Leia Inc.
// SPDX-License-Identifier: BSL-1.0
/*!
 * @file
 * @brief  glTF 2.0 PBR model renderer — raster implementation.
 *
 * Renders the loaded model into an internal colour image with a
 * metallic-roughness PBR pass, then blits that image into the per-eye
 * swapchain viewport region. The viewport-copy + transparency dance mirrors
 * 3dgs_common/gs_renderer.cpp so this drops into the platform code unchanged.
 *
 * v1: material factors only (no textures/IBL), one directional light + flat
 * ambient, static geometry. See ../PORTING.md for the follow-ups.
 */

#include "model_renderer.h"
#include "model_loader.h"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <vector>

// SPIR-V generated by glslangValidator (--vn) at build time. See CMakeLists.txt.
#include "pbr.vert.h"
#include "pbr.frag.h"
#include "skybox.frag.h"
#include "fullscreen.vert.h"
#include "brdf_lut.frag.h"
#include "irradiance.frag.h"
#include "prefilter.frag.h"

#include <glm/glm.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <glm/gtc/quaternion.hpp>      // glm::quat, slerp, mat4_cast
#include <glm/gtc/matrix_transform.hpp>

namespace {

VkShaderModule createShaderModule(VkDevice device, const uint32_t* code, size_t sizeBytes) {
    VkShaderModuleCreateInfo ci = {VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO};
    ci.codeSize = sizeBytes;
    ci.pCode = code;
    VkShaderModule m = VK_NULL_HANDLE;
    vkCreateShaderModule(device, &ci, nullptr, &m);
    return m;
}

// A throwaway fullscreen-triangle pipeline for the IBL generation passes:
// fullscreen.vert + the given fragment SPIR-V, one float-RGBA(or RG) colour
// target, dynamic viewport/scissor, no depth, optional fragment push constant.
struct FsPipe { VkRenderPass rp = VK_NULL_HANDLE; VkPipelineLayout layout = VK_NULL_HANDLE; VkPipeline pipe = VK_NULL_HANDLE; };

FsPipe makeFsPipe(VkDevice d, VkFormat fmt, const uint32_t* frag, size_t fragBytes, uint32_t pushBytes) {
    FsPipe fp;
    VkAttachmentDescription att = {};
    att.format = fmt; att.samples = VK_SAMPLE_COUNT_1_BIT;
    att.loadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE; att.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
    att.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE; att.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
    att.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED; att.finalLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
    VkAttachmentReference ref = {0, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};
    VkSubpassDescription sub = {}; sub.pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
    sub.colorAttachmentCount = 1; sub.pColorAttachments = &ref;
    VkRenderPassCreateInfo rpci = {VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO};
    rpci.attachmentCount = 1; rpci.pAttachments = &att; rpci.subpassCount = 1; rpci.pSubpasses = &sub;
    vkCreateRenderPass(d, &rpci, nullptr, &fp.rp);

    VkPushConstantRange pc = {VK_SHADER_STAGE_FRAGMENT_BIT, 0, pushBytes};
    VkPipelineLayoutCreateInfo plci = {VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};
    if (pushBytes) { plci.pushConstantRangeCount = 1; plci.pPushConstantRanges = &pc; }
    vkCreatePipelineLayout(d, &plci, nullptr, &fp.layout);

    VkShaderModule vs = createShaderModule(d, fullscreen_vert_data, sizeof(fullscreen_vert_data));
    VkShaderModule fs = createShaderModule(d, frag, fragBytes);
    VkPipelineShaderStageCreateInfo st[2] = {};
    st[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO; st[0].stage = VK_SHADER_STAGE_VERTEX_BIT; st[0].module = vs; st[0].pName = "main";
    st[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO; st[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT; st[1].module = fs; st[1].pName = "main";

    VkPipelineVertexInputStateCreateInfo vi = {VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO};
    VkPipelineInputAssemblyStateCreateInfo ia = {VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO};
    ia.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;
    VkPipelineViewportStateCreateInfo vp = {VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO}; vp.viewportCount = 1; vp.scissorCount = 1;
    VkPipelineRasterizationStateCreateInfo rs = {VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO};
    rs.polygonMode = VK_POLYGON_MODE_FILL; rs.cullMode = VK_CULL_MODE_NONE; rs.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE; rs.lineWidth = 1.0f;
    VkPipelineMultisampleStateCreateInfo ms = {VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO}; ms.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;
    VkPipelineColorBlendAttachmentState cba = {}; cba.colorWriteMask = 0xF;
    VkPipelineColorBlendStateCreateInfo cb = {VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO}; cb.attachmentCount = 1; cb.pAttachments = &cba;
    VkDynamicState dyns[2] = {VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR};
    VkPipelineDynamicStateCreateInfo dyn = {VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO}; dyn.dynamicStateCount = 2; dyn.pDynamicStates = dyns;

    VkGraphicsPipelineCreateInfo gp = {VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO};
    gp.stageCount = 2; gp.pStages = st; gp.pVertexInputState = &vi; gp.pInputAssemblyState = &ia;
    gp.pViewportState = &vp; gp.pRasterizationState = &rs; gp.pMultisampleState = &ms;
    gp.pColorBlendState = &cb; gp.pDynamicState = &dyn; gp.layout = fp.layout; gp.renderPass = fp.rp;
    vkCreateGraphicsPipelines(d, VK_NULL_HANDLE, 1, &gp, nullptr, &fp.pipe);
    vkDestroyShaderModule(d, vs, nullptr);
    vkDestroyShaderModule(d, fs, nullptr);
    return fp;
}
void destroyFsPipe(VkDevice d, FsPipe& fp) {
    if (fp.pipe) vkDestroyPipeline(d, fp.pipe, nullptr);
    if (fp.layout) vkDestroyPipelineLayout(d, fp.layout, nullptr);
    if (fp.rp) vkDestroyRenderPass(d, fp.rp, nullptr);
    fp = {};
}

// 4x4 column-major multiply: out = a * b (matches gs_renderer's convention).
void mat4Mul(const float a[16], const float b[16], float out[16]) {
    for (int col = 0; col < 4; ++col)
        for (int row = 0; row < 4; ++row) {
            float s = 0.0f;
            for (int k = 0; k < 4; ++k) s += a[k * 4 + row] * b[col * 4 + k];
            out[col * 4 + row] = s;
        }
}

// A unit cube (24 verts, per-face normals) for loadDebugModel().
void buildCubeModel(ModelData& md) {
    struct V { float p[3], n[3]; };
    const V faces[6][4] = {
        {{{ 0.5f,-0.5f,-0.5f},{1,0,0}},{{ 0.5f, 0.5f,-0.5f},{1,0,0}},{{ 0.5f, 0.5f, 0.5f},{1,0,0}},{{ 0.5f,-0.5f, 0.5f},{1,0,0}}},
        {{{-0.5f,-0.5f, 0.5f},{-1,0,0}},{{-0.5f, 0.5f, 0.5f},{-1,0,0}},{{-0.5f, 0.5f,-0.5f},{-1,0,0}},{{-0.5f,-0.5f,-0.5f},{-1,0,0}}},
        {{{-0.5f, 0.5f,-0.5f},{0,1,0}},{{-0.5f, 0.5f, 0.5f},{0,1,0}},{{ 0.5f, 0.5f, 0.5f},{0,1,0}},{{ 0.5f, 0.5f,-0.5f},{0,1,0}}},
        {{{-0.5f,-0.5f, 0.5f},{0,-1,0}},{{-0.5f,-0.5f,-0.5f},{0,-1,0}},{{ 0.5f,-0.5f,-0.5f},{0,-1,0}},{{ 0.5f,-0.5f, 0.5f},{0,-1,0}}},
        {{{-0.5f,-0.5f, 0.5f},{0,0,1}},{{ 0.5f,-0.5f, 0.5f},{0,0,1}},{{ 0.5f, 0.5f, 0.5f},{0,0,1}},{{-0.5f, 0.5f, 0.5f},{0,0,1}}},
        {{{ 0.5f,-0.5f,-0.5f},{0,0,-1}},{{-0.5f,-0.5f,-0.5f},{0,0,-1}},{{-0.5f, 0.5f,-0.5f},{0,0,-1}},{{ 0.5f, 0.5f,-0.5f},{0,0,-1}}},
    };
    for (int f = 0; f < 6; ++f) {
        uint32_t base = (uint32_t)md.vertices.size();
        for (int i = 0; i < 4; ++i) {
            ModelVertex v{};
            std::memcpy(v.pos, faces[f][i].p, sizeof(v.pos));
            std::memcpy(v.normal, faces[f][i].n, sizeof(v.normal));
            md.vertices.push_back(v);
        }
        const uint32_t idx[6] = {base, base + 1, base + 2, base, base + 2, base + 3};
        md.indices.insert(md.indices.end(), idx, idx + 6);
    }
    ModelMaterial m{};
    m.baseColorFactor[0] = 0.8f; m.baseColorFactor[1] = 0.3f; m.baseColorFactor[2] = 0.2f;
    m.metallic = 0.1f; m.roughness = 0.5f;
    md.materials.push_back(m);

    ModelPrimitive p{};
    p.firstIndex = 0; p.indexCount = (uint32_t)md.indices.size(); p.material = 0;
    const float ident[16] = {1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1};
    std::memcpy(p.modelMatrix, ident, sizeof(ident));
    md.primitives.push_back(p);
    md.primitiveCount = 1;
    md.bboxMin[0] = md.bboxMin[1] = md.bboxMin[2] = -0.5f;
    md.bboxMax[0] = md.bboxMax[1] = md.bboxMax[2] = 0.5f;
    md.hasBBox = true;
}

}  // namespace

// ═════════════════════════════════════════════════════════════════════════
bool ModelRenderer::init(VkInstance instance,
                         VkPhysicalDevice physicalDevice,
                         VkDevice device,
                         VkQueue queue,
                         uint32_t queueFamilyIndex,
                         uint32_t renderWidth,
                         uint32_t renderHeight) {
    instance_ = instance;
    physDevice_ = physicalDevice;
    device_ = device;
    queue_ = queue;
    queueFamily_ = queueFamilyIndex;
    width_ = renderWidth;
    height_ = renderHeight;

    VkCommandPoolCreateInfo poolInfo = {VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO};
    poolInfo.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
    poolInfo.queueFamilyIndex = queueFamilyIndex;
    if (vkCreateCommandPool(device, &poolInfo, nullptr, &cmdPool_) != VK_SUCCESS) {
        std::fprintf(stderr, "ModelRenderer: failed to create command pool\n");
        return false;
    }

    if (!createRenderTargets()) return false;
    if (!createPipeline()) return false;
    if (!createSamplerAndDefaults()) return false;
    if (!createIbl()) return false;

    initialized_ = true;
    std::printf("ModelRenderer: initialized (%ux%u)\n", width_, height_);
    return true;
}

bool ModelRenderer::createRenderTargets() {
    // Render pass (format-only; size-independent). Clears colour+depth, leaves
    // colour in TRANSFER_SRC for the per-eye viewport blit.
    VkAttachmentDescription atts[2] = {};
    atts[0].format = colorFormat_;
    atts[0].samples = VK_SAMPLE_COUNT_1_BIT;
    atts[0].loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
    atts[0].storeOp = VK_ATTACHMENT_STORE_OP_STORE;
    atts[0].stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
    atts[0].stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
    atts[0].initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    atts[0].finalLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;

    atts[1].format = depthFormat_;
    atts[1].samples = VK_SAMPLE_COUNT_1_BIT;
    atts[1].loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
    atts[1].storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
    atts[1].stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
    atts[1].stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
    atts[1].initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    atts[1].finalLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;

    VkAttachmentReference colorRef = {0, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};
    VkAttachmentReference depthRef = {1, VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL};
    VkSubpassDescription sub = {};
    sub.pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
    sub.colorAttachmentCount = 1;
    sub.pColorAttachments = &colorRef;
    sub.pDepthStencilAttachment = &depthRef;

    VkSubpassDependency deps[2] = {};
    deps[0].srcSubpass = VK_SUBPASS_EXTERNAL;
    deps[0].dstSubpass = 0;
    deps[0].srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT | VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT;
    deps[0].dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT | VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT;
    deps[0].srcAccessMask = 0;
    deps[0].dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;
    deps[1].srcSubpass = 0;
    deps[1].dstSubpass = VK_SUBPASS_EXTERNAL;
    deps[1].srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    deps[1].dstStageMask = VK_PIPELINE_STAGE_TRANSFER_BIT;
    deps[1].srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
    deps[1].dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;

    VkRenderPassCreateInfo rpci = {VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO};
    rpci.attachmentCount = 2;
    rpci.pAttachments = atts;
    rpci.subpassCount = 1;
    rpci.pSubpasses = &sub;
    rpci.dependencyCount = 2;
    rpci.pDependencies = deps;
    if (vkCreateRenderPass(device_, &rpci, nullptr, &renderPass_) != VK_SUCCESS) return false;

    return ensureTargets(width_, height_);
}

// (Re)create the internal colour+depth targets and framebuffer at w×h, reusing
// renderPass_. Called at init and whenever the per-eye viewport size changes
// (window resize) — a fixed-size framebuffer would make the render pass invalid
// once the window grew, leaving the swapchain unwritten (window goes transparent).
bool ModelRenderer::ensureTargets(uint32_t w, uint32_t h) {
    if (w == 0) w = 1;
    if (h == 0) h = 1;
    if (device_ != VK_NULL_HANDLE) vkDeviceWaitIdle(device_);
    if (framebuffer_ != VK_NULL_HANDLE) { vkDestroyFramebuffer(device_, framebuffer_, nullptr); framebuffer_ = VK_NULL_HANDLE; }
    if (colorImage_.image != VK_NULL_HANDLE) modelDestroyImage(device_, colorImage_);
    if (depthImage_.image != VK_NULL_HANDLE) modelDestroyImage(device_, depthImage_);
    width_ = w; height_ = h;

    colorImage_ = modelCreateImage2D(device_, physDevice_, w, h, colorFormat_,
        VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT);
    if (colorImage_.image == VK_NULL_HANDLE) return false;

    VkImageCreateInfo ici = {VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};
    ici.imageType = VK_IMAGE_TYPE_2D; ici.format = depthFormat_;
    ici.extent = {w, h, 1}; ici.mipLevels = 1; ici.arrayLayers = 1;
    ici.samples = VK_SAMPLE_COUNT_1_BIT; ici.tiling = VK_IMAGE_TILING_OPTIMAL;
    ici.usage = VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT; ici.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    if (vkCreateImage(device_, &ici, nullptr, &depthImage_.image) != VK_SUCCESS) return false;
    VkMemoryRequirements mr; vkGetImageMemoryRequirements(device_, depthImage_.image, &mr);
    VkMemoryAllocateInfo ai = {VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};
    ai.allocationSize = mr.size;
    ai.memoryTypeIndex = modelFindMemoryType(physDevice_, mr.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (vkAllocateMemory(device_, &ai, nullptr, &depthImage_.memory) != VK_SUCCESS) return false;
    vkBindImageMemory(device_, depthImage_.image, depthImage_.memory, 0);
    VkImageViewCreateInfo vci = {VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};
    vci.image = depthImage_.image; vci.viewType = VK_IMAGE_VIEW_TYPE_2D; vci.format = depthFormat_;
    vci.subresourceRange = {VK_IMAGE_ASPECT_DEPTH_BIT, 0, 1, 0, 1};
    if (vkCreateImageView(device_, &vci, nullptr, &depthImage_.view) != VK_SUCCESS) return false;
    depthImage_.width = w; depthImage_.height = h;

    VkImageView fbViews[2] = {colorImage_.view, depthImage_.view};
    VkFramebufferCreateInfo fbci = {VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO};
    fbci.renderPass = renderPass_; fbci.attachmentCount = 2; fbci.pAttachments = fbViews;
    fbci.width = w; fbci.height = h; fbci.layers = 1;
    if (vkCreateFramebuffer(device_, &fbci, nullptr, &framebuffer_) != VK_SUCCESS) return false;
    return true;
}

bool ModelRenderer::createPipeline() {
    // Set-0: one UBO, visible to vertex + fragment.
    VkDescriptorSetLayoutBinding b0 = {};
    b0.binding = 0;
    b0.descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
    b0.descriptorCount = 1;
    b0.stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT;
    VkDescriptorSetLayoutCreateInfo dlci = {VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};
    dlci.bindingCount = 1;
    dlci.pBindings = &b0;
    if (vkCreateDescriptorSetLayout(device_, &dlci, nullptr, &dsLayout_) != VK_SUCCESS) return false;

    // Set 1: per-material textures — base color, MR, normal, occlusion, emissive.
    VkDescriptorSetLayoutBinding mb[5] = {};
    for (uint32_t i = 0; i < 5; ++i) {
        mb[i].binding = i;
        mb[i].descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
        mb[i].descriptorCount = 1;
        mb[i].stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;
    }
    VkDescriptorSetLayoutCreateInfo mlci = {VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};
    mlci.bindingCount = 5;
    mlci.pBindings = mb;
    if (vkCreateDescriptorSetLayout(device_, &mlci, nullptr, &matSetLayout_) != VK_SUCCESS) return false;

    // Set 2: IBL — irradiance cube, prefiltered cube, BRDF LUT (all fragment).
    VkDescriptorSetLayoutBinding ib[3] = {};
    for (uint32_t i = 0; i < 3; ++i) {
        ib[i].binding = i;
        ib[i].descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
        ib[i].descriptorCount = 1;
        ib[i].stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;
    }
    VkDescriptorSetLayoutCreateInfo ilci = {VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};
    ilci.bindingCount = 3;
    ilci.pBindings = ib;
    if (vkCreateDescriptorSetLayout(device_, &ilci, nullptr, &iblSetLayout_) != VK_SUCCESS) return false;

    // Set 3: joint-matrix SSBO for skinning (vertex stage). Always present (a
    // 1-matrix dummy for static models) so the binding is valid every draw.
    VkDescriptorSetLayoutBinding jb = {};
    jb.binding = 0;
    jb.descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
    jb.descriptorCount = 1;
    jb.stageFlags = VK_SHADER_STAGE_VERTEX_BIT;
    VkDescriptorSetLayoutCreateInfo jlci = {VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};
    jlci.bindingCount = 1;
    jlci.pBindings = &jb;
    if (vkCreateDescriptorSetLayout(device_, &jlci, nullptr, &jointSetLayout_) != VK_SUCCESS) return false;

    VkPushConstantRange pcr = {};
    pcr.stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT;
    pcr.offset = 0;
    pcr.size = sizeof(PushBlock);
    VkDescriptorSetLayout setLayouts[4] = {dsLayout_, matSetLayout_, iblSetLayout_, jointSetLayout_};
    VkPipelineLayoutCreateInfo plci = {VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};
    plci.setLayoutCount = 4;
    plci.pSetLayouts = setLayouts;
    plci.pushConstantRangeCount = 1;
    plci.pPushConstantRanges = &pcr;
    if (vkCreatePipelineLayout(device_, &plci, nullptr, &pipelineLayout_) != VK_SUCCESS) return false;

    VkShaderModule vs = createShaderModule(device_, pbr_vert_data, sizeof(pbr_vert_data));
    VkShaderModule fs = createShaderModule(device_, pbr_frag_data, sizeof(pbr_frag_data));
    if (vs == VK_NULL_HANDLE || fs == VK_NULL_HANDLE) return false;

    VkPipelineShaderStageCreateInfo stages[2] = {};
    stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
    stages[0].module = vs;
    stages[0].pName = "main";
    stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
    stages[1].module = fs;
    stages[1].pName = "main";

    VkVertexInputBindingDescription vib = {0, sizeof(ModelVertex), VK_VERTEX_INPUT_RATE_VERTEX};
    VkVertexInputAttributeDescription via[5] = {
        {0, 0, VK_FORMAT_R32G32B32_SFLOAT,    (uint32_t)offsetof(ModelVertex, pos)},
        {1, 0, VK_FORMAT_R32G32B32_SFLOAT,    (uint32_t)offsetof(ModelVertex, normal)},
        {2, 0, VK_FORMAT_R32G32_SFLOAT,       (uint32_t)offsetof(ModelVertex, uv)},
        {3, 0, VK_FORMAT_R16G16B16A16_UINT,   (uint32_t)offsetof(ModelVertex, joints0)},
        {4, 0, VK_FORMAT_R32G32B32A32_SFLOAT, (uint32_t)offsetof(ModelVertex, weights0)},
    };
    VkPipelineVertexInputStateCreateInfo vi = {VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO};
    vi.vertexBindingDescriptionCount = 1;
    vi.pVertexBindingDescriptions = &vib;
    vi.vertexAttributeDescriptionCount = 5;
    vi.pVertexAttributeDescriptions = via;

    VkPipelineInputAssemblyStateCreateInfo ia = {VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO};
    ia.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;

    VkPipelineViewportStateCreateInfo vp = {VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO};
    vp.viewportCount = 1;
    vp.scissorCount = 1;

    VkPipelineRasterizationStateCreateInfo rs = {VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO};
    rs.polygonMode = VK_POLYGON_MODE_FILL;
    rs.cullMode = VK_CULL_MODE_NONE;       // two-sided shading handles back faces
    rs.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
    rs.lineWidth = 1.0f;

    VkPipelineMultisampleStateCreateInfo ms = {VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO};
    ms.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

    VkPipelineDepthStencilStateCreateInfo ds = {VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO};
    ds.depthTestEnable = VK_TRUE;
    ds.depthWriteEnable = VK_TRUE;
    ds.depthCompareOp = VK_COMPARE_OP_LESS;

    VkPipelineColorBlendAttachmentState cba = {};
    cba.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
                         VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
    cba.blendEnable = VK_FALSE;
    VkPipelineColorBlendStateCreateInfo cb = {VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO};
    cb.attachmentCount = 1;
    cb.pAttachments = &cba;

    VkDynamicState dynStates[2] = {VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR};
    VkPipelineDynamicStateCreateInfo dyn = {VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO};
    dyn.dynamicStateCount = 2;
    dyn.pDynamicStates = dynStates;

    VkGraphicsPipelineCreateInfo gpci = {VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO};
    gpci.stageCount = 2;
    gpci.pStages = stages;
    gpci.pVertexInputState = &vi;
    gpci.pInputAssemblyState = &ia;
    gpci.pViewportState = &vp;
    gpci.pRasterizationState = &rs;
    gpci.pMultisampleState = &ms;
    gpci.pDepthStencilState = &ds;
    gpci.pColorBlendState = &cb;
    gpci.pDynamicState = &dyn;
    gpci.layout = pipelineLayout_;
    gpci.renderPass = renderPass_;
    gpci.subpass = 0;
    VkResult pr = vkCreateGraphicsPipelines(device_, VK_NULL_HANDLE, 1, &gpci, nullptr, &pipeline_);

    vkDestroyShaderModule(device_, vs, nullptr);
    vkDestroyShaderModule(device_, fs, nullptr);
    if (pr != VK_SUCCESS) {
        std::fprintf(stderr, "ModelRenderer: failed to create pipeline (%d)\n", pr);
        return false;
    }

    // Skybox pipeline: fullscreen.vert + skybox.frag, no vertex input, depth
    // test/write off (drawn behind the model). Reuses pipelineLayout_/renderPass_.
    {
        VkShaderModule svs = createShaderModule(device_, fullscreen_vert_data, sizeof(fullscreen_vert_data));
        VkShaderModule sfs = createShaderModule(device_, skybox_frag_data, sizeof(skybox_frag_data));
        VkPipelineShaderStageCreateInfo st2[2] = {};
        st2[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO; st2[0].stage = VK_SHADER_STAGE_VERTEX_BIT;   st2[0].module = svs; st2[0].pName = "main";
        st2[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO; st2[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT; st2[1].module = sfs; st2[1].pName = "main";
        VkPipelineVertexInputStateCreateInfo vi2 = {VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO};
        VkPipelineDepthStencilStateCreateInfo ds2 = {VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO};
        ds2.depthTestEnable = VK_FALSE; ds2.depthWriteEnable = VK_FALSE;
        VkGraphicsPipelineCreateInfo gp2 = gpci;   // reuse ia/vp/rs/ms/cb/dyn/layout/renderPass
        gp2.pStages = st2;
        gp2.pVertexInputState = &vi2;
        gp2.pDepthStencilState = &ds2;
        VkResult spr = vkCreateGraphicsPipelines(device_, VK_NULL_HANDLE, 1, &gp2, nullptr, &skyboxPipeline_);
        vkDestroyShaderModule(device_, svs, nullptr);
        vkDestroyShaderModule(device_, sfs, nullptr);
        if (spr != VK_SUCCESS) { std::fprintf(stderr, "ModelRenderer: failed to create skybox pipeline (%d)\n", spr); return false; }
    }

    // Descriptor pool + set + the host-visible uniform buffer.
    VkDescriptorPoolSize ps = {VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, 1};
    VkDescriptorPoolCreateInfo dpci = {VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};
    dpci.maxSets = 1;
    dpci.poolSizeCount = 1;
    dpci.pPoolSizes = &ps;
    if (vkCreateDescriptorPool(device_, &dpci, nullptr, &descriptorPool_) != VK_SUCCESS) return false;

    VkDescriptorSetAllocateInfo dsai = {VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};
    dsai.descriptorPool = descriptorPool_;
    dsai.descriptorSetCount = 1;
    dsai.pSetLayouts = &dsLayout_;
    if (vkAllocateDescriptorSets(device_, &dsai, &descriptorSet_) != VK_SUCCESS) return false;

    uniformBuffer_ = modelCreateBuffer(device_, physDevice_, sizeof(UniformBlock),
        VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT,
        VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
    if (uniformBuffer_.buffer == VK_NULL_HANDLE) return false;

    VkDescriptorBufferInfo dbi = {uniformBuffer_.buffer, 0, sizeof(UniformBlock)};
    VkWriteDescriptorSet w = {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
    w.dstSet = descriptorSet_;
    w.dstBinding = 0;
    w.descriptorCount = 1;
    w.descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
    w.pBufferInfo = &dbi;
    vkUpdateDescriptorSets(device_, 1, &w, 0, nullptr);
    return true;
}

ModelImage ModelRenderer::uploadTexture(const ModelTexture& tex) {
    ModelImage img;
    if (tex.width <= 0 || tex.height <= 0 || tex.rgba.empty()) return img;
    img.width = tex.width;
    img.height = tex.height;
    const uint32_t w = (uint32_t)tex.width, h = (uint32_t)tex.height;
    const uint32_t mips = (uint32_t)std::floor(std::log2((float)std::max(w, h))) + 1u;

    VkImageCreateInfo ici = {VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};
    ici.imageType = VK_IMAGE_TYPE_2D;
    ici.format = VK_FORMAT_R8G8B8A8_UNORM;  // sRGB decode done in the shader
    ici.extent = {w, h, 1};
    ici.mipLevels = mips;
    ici.arrayLayers = 1;
    ici.samples = VK_SAMPLE_COUNT_1_BIT;
    ici.tiling = VK_IMAGE_TILING_OPTIMAL;
    ici.usage = VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT |
                VK_IMAGE_USAGE_TRANSFER_SRC_BIT;  // SRC for mip blits
    ici.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    if (vkCreateImage(device_, &ici, nullptr, &img.image) != VK_SUCCESS) return ModelImage{};

    VkMemoryRequirements mr;
    vkGetImageMemoryRequirements(device_, img.image, &mr);
    VkMemoryAllocateInfo ai = {VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};
    ai.allocationSize = mr.size;
    ai.memoryTypeIndex = modelFindMemoryType(physDevice_, mr.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (vkAllocateMemory(device_, &ai, nullptr, &img.memory) != VK_SUCCESS) { vkDestroyImage(device_, img.image, nullptr); return ModelImage{}; }
    vkBindImageMemory(device_, img.image, img.memory, 0);

    VkImageViewCreateInfo vci = {VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};
    vci.image = img.image;
    vci.viewType = VK_IMAGE_VIEW_TYPE_2D;
    vci.format = ici.format;
    vci.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, mips, 0, 1};
    vkCreateImageView(device_, &vci, nullptr, &img.view);

    // Staging upload of mip 0.
    ModelBuffer staging = modelCreateBuffer(device_, physDevice_, tex.rgba.size(),
        VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
        VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
    void* mapped = nullptr;
    vkMapMemory(device_, staging.memory, 0, tex.rgba.size(), 0, &mapped);
    std::memcpy(mapped, tex.rgba.data(), tex.rgba.size());
    vkUnmapMemory(device_, staging.memory);

    VkCommandBufferAllocateInfo cbai = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};
    cbai.commandPool = cmdPool_; cbai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY; cbai.commandBufferCount = 1;
    VkCommandBuffer cmd; vkAllocateCommandBuffers(device_, &cbai, &cmd);
    VkCommandBufferBeginInfo bi = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(cmd, &bi);

    auto barrier = [&](uint32_t mip, uint32_t count, VkImageLayout oldL, VkImageLayout newL,
                       VkAccessFlags srcA, VkAccessFlags dstA, VkPipelineStageFlags srcS, VkPipelineStageFlags dstS) {
        VkImageMemoryBarrier b = {VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};
        b.oldLayout = oldL; b.newLayout = newL;
        b.srcAccessMask = srcA; b.dstAccessMask = dstA;
        b.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED; b.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        b.image = img.image;
        b.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, mip, count, 0, 1};
        vkCmdPipelineBarrier(cmd, srcS, dstS, 0, 0, nullptr, 0, nullptr, 1, &b);
    };

    // mip 0 → TRANSFER_DST, copy.
    barrier(0, 1, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
            0, VK_ACCESS_TRANSFER_WRITE_BIT, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT);
    VkBufferImageCopy region = {};
    region.imageSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
    region.imageExtent = {w, h, 1};
    vkCmdCopyBufferToImage(cmd, staging.buffer, img.image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &region);

    // Generate mips by successive blits.
    int32_t mw = (int32_t)w, mh = (int32_t)h;
    for (uint32_t i = 1; i < mips; ++i) {
        // src mip (i-1): TRANSFER_DST → TRANSFER_SRC
        barrier(i - 1, 1, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT);
        // dst mip (i): UNDEFINED → TRANSFER_DST
        barrier(i, 1, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
                0, VK_ACCESS_TRANSFER_WRITE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT);
        int32_t nw = mw > 1 ? mw / 2 : 1, nh = mh > 1 ? mh / 2 : 1;
        VkImageBlit blit = {};
        blit.srcSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, i - 1, 0, 1};
        blit.srcOffsets[1] = {mw, mh, 1};
        blit.dstSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, i, 0, 1};
        blit.dstOffsets[1] = {nw, nh, 1};
        vkCmdBlitImage(cmd, img.image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                       img.image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &blit, VK_FILTER_LINEAR);
        // src mip (i-1) → SHADER_READ
        barrier(i - 1, 1, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
                VK_ACCESS_TRANSFER_READ_BIT, VK_ACCESS_SHADER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT);
        mw = nw; mh = nh;
    }
    // last mip → SHADER_READ
    barrier(mips - 1, 1, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
            VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT);

    vkEndCommandBuffer(cmd);
    VkSubmitInfo si = {VK_STRUCTURE_TYPE_SUBMIT_INFO};
    si.commandBufferCount = 1; si.pCommandBuffers = &cmd;
    vkQueueSubmit(queue_, 1, &si, VK_NULL_HANDLE);
    vkQueueWaitIdle(queue_);
    vkFreeCommandBuffers(device_, cmdPool_, 1, &cmd);
    modelDestroyBuffer(device_, staging);
    return img;
}

bool ModelRenderer::createSamplerAndDefaults() {
    VkSamplerCreateInfo sci = {VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO};
    sci.magFilter = VK_FILTER_LINEAR;
    sci.minFilter = VK_FILTER_LINEAR;
    sci.mipmapMode = VK_SAMPLER_MIPMAP_MODE_LINEAR;
    sci.addressModeU = VK_SAMPLER_ADDRESS_MODE_REPEAT;
    sci.addressModeV = VK_SAMPLER_ADDRESS_MODE_REPEAT;
    sci.addressModeW = VK_SAMPLER_ADDRESS_MODE_REPEAT;
    sci.maxLod = VK_LOD_CLAMP_NONE;
    sci.borderColor = VK_BORDER_COLOR_FLOAT_OPAQUE_WHITE;
    if (vkCreateSampler(device_, &sci, nullptr, &sampler_) != VK_SUCCESS) return false;

    ModelTexture white; white.width = 1; white.height = 1; white.rgba = {255, 255, 255, 255};
    whiteTex_ = uploadTexture(white);
    ModelTexture flat;  flat.width = 1;  flat.height = 1;  flat.rgba = {128, 128, 255, 255};
    flatNormalTex_ = uploadTexture(flat);
    return whiteTex_.view != VK_NULL_HANDLE && flatNormalTex_.view != VK_NULL_HANDLE;
}

bool ModelRenderer::genCubeMap(CubeMap& cube, uint32_t size, uint32_t mips,
                               const uint32_t* fragSpv, size_t fragSpvBytes, bool /*perMipRoughness*/) {
    cube.size = size; cube.mips = mips;
    const VkFormat fmt = VK_FORMAT_R16G16B16A16_SFLOAT;

    VkImageCreateInfo ici = {VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};
    ici.flags = VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT;
    ici.imageType = VK_IMAGE_TYPE_2D;
    ici.format = fmt;
    ici.extent = {size, size, 1};
    ici.mipLevels = mips;
    ici.arrayLayers = 6;
    ici.samples = VK_SAMPLE_COUNT_1_BIT;
    ici.tiling = VK_IMAGE_TILING_OPTIMAL;
    ici.usage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;
    ici.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    if (vkCreateImage(device_, &ici, nullptr, &cube.image) != VK_SUCCESS) return false;
    VkMemoryRequirements mreq; vkGetImageMemoryRequirements(device_, cube.image, &mreq);
    VkMemoryAllocateInfo ai = {VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};
    ai.allocationSize = mreq.size;
    ai.memoryTypeIndex = modelFindMemoryType(physDevice_, mreq.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (vkAllocateMemory(device_, &ai, nullptr, &cube.memory) != VK_SUCCESS) return false;
    vkBindImageMemory(device_, cube.image, cube.memory, 0);

    VkImageViewCreateInfo cvci = {VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};
    cvci.image = cube.image; cvci.viewType = VK_IMAGE_VIEW_TYPE_CUBE; cvci.format = fmt;
    cvci.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, mips, 0, 6};
    if (vkCreateImageView(device_, &cvci, nullptr, &cube.view) != VK_SUCCESS) return false;

    struct Push { int32_t face; float roughness; };
    FsPipe fp = makeFsPipe(device_, fmt, fragSpv, fragSpvBytes, sizeof(Push));

    for (uint32_t m = 0; m < mips; ++m) {
        uint32_t ms = size >> m; if (ms == 0) ms = 1;
        float rough = (mips > 1) ? (float)m / (float)(mips - 1) : 0.0f;
        for (uint32_t f = 0; f < 6; ++f) {
            VkImageView faceView;
            VkImageViewCreateInfo fv = {VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};
            fv.image = cube.image; fv.viewType = VK_IMAGE_VIEW_TYPE_2D; fv.format = fmt;
            fv.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, m, 1, f, 1};
            vkCreateImageView(device_, &fv, nullptr, &faceView);

            VkFramebufferCreateInfo fbci = {VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO};
            fbci.renderPass = fp.rp; fbci.attachmentCount = 1; fbci.pAttachments = &faceView;
            fbci.width = ms; fbci.height = ms; fbci.layers = 1;
            VkFramebuffer fb; vkCreateFramebuffer(device_, &fbci, nullptr, &fb);

            VkCommandBufferAllocateInfo cai = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};
            cai.commandPool = cmdPool_; cai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY; cai.commandBufferCount = 1;
            VkCommandBuffer cmd; vkAllocateCommandBuffers(device_, &cai, &cmd);
            VkCommandBufferBeginInfo bi = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
            bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
            vkBeginCommandBuffer(cmd, &bi);
            VkRenderPassBeginInfo rpbi = {VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO};
            rpbi.renderPass = fp.rp; rpbi.framebuffer = fb;
            rpbi.renderArea.extent = {ms, ms};
            vkCmdBeginRenderPass(cmd, &rpbi, VK_SUBPASS_CONTENTS_INLINE);
            VkViewport vpr = {0, 0, (float)ms, (float)ms, 0, 1};
            VkRect2D sc = {{0, 0}, {ms, ms}};
            vkCmdSetViewport(cmd, 0, 1, &vpr); vkCmdSetScissor(cmd, 0, 1, &sc);
            vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, fp.pipe);
            Push pcv = {(int32_t)f, rough};
            vkCmdPushConstants(cmd, fp.layout, VK_SHADER_STAGE_FRAGMENT_BIT, 0, sizeof(Push), &pcv);
            vkCmdDraw(cmd, 3, 1, 0, 0);
            vkCmdEndRenderPass(cmd);
            vkEndCommandBuffer(cmd);
            VkSubmitInfo si = {VK_STRUCTURE_TYPE_SUBMIT_INFO}; si.commandBufferCount = 1; si.pCommandBuffers = &cmd;
            vkQueueSubmit(queue_, 1, &si, VK_NULL_HANDLE); vkQueueWaitIdle(queue_);
            vkFreeCommandBuffers(device_, cmdPool_, 1, &cmd);
            vkDestroyFramebuffer(device_, fb, nullptr);
            vkDestroyImageView(device_, faceView, nullptr);
        }
    }
    destroyFsPipe(device_, fp);
    return true;
}

bool ModelRenderer::createIbl() {
    VkSamplerCreateInfo sc = {VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO};
    sc.magFilter = VK_FILTER_LINEAR; sc.minFilter = VK_FILTER_LINEAR;
    sc.mipmapMode = VK_SAMPLER_MIPMAP_MODE_LINEAR;
    sc.addressModeU = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
    sc.addressModeV = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
    sc.addressModeW = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
    sc.maxLod = VK_LOD_CLAMP_NONE; sc.borderColor = VK_BORDER_COLOR_FLOAT_OPAQUE_WHITE;
    if (vkCreateSampler(device_, &sc, nullptr, &iblCubeSampler_) != VK_SUCCESS) return false;
    VkSamplerCreateInfo sl = sc; sl.maxLod = 0.0f;
    if (vkCreateSampler(device_, &sl, nullptr, &iblLutSampler_) != VK_SUCCESS) return false;

    // BRDF LUT (2D R16G16) via a fullscreen pass.
    brdfLut_ = modelCreateImage2D(device_, physDevice_, 256, 256, VK_FORMAT_R16G16_SFLOAT,
        VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_SAMPLED_BIT);
    if (brdfLut_.image == VK_NULL_HANDLE) return false;
    {
        FsPipe fp = makeFsPipe(device_, VK_FORMAT_R16G16_SFLOAT, brdf_lut_frag_data, sizeof(brdf_lut_frag_data), 0);
        VkFramebufferCreateInfo fbci = {VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO};
        fbci.renderPass = fp.rp; fbci.attachmentCount = 1; fbci.pAttachments = &brdfLut_.view;
        fbci.width = 256; fbci.height = 256; fbci.layers = 1;
        VkFramebuffer fb; vkCreateFramebuffer(device_, &fbci, nullptr, &fb);
        VkCommandBufferAllocateInfo cai = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};
        cai.commandPool = cmdPool_; cai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY; cai.commandBufferCount = 1;
        VkCommandBuffer cmd; vkAllocateCommandBuffers(device_, &cai, &cmd);
        VkCommandBufferBeginInfo bi = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
        bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
        vkBeginCommandBuffer(cmd, &bi);
        VkRenderPassBeginInfo rpbi = {VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO};
        rpbi.renderPass = fp.rp; rpbi.framebuffer = fb; rpbi.renderArea.extent = {256, 256};
        vkCmdBeginRenderPass(cmd, &rpbi, VK_SUBPASS_CONTENTS_INLINE);
        VkViewport vpr = {0, 0, 256, 256, 0, 1}; VkRect2D scs = {{0, 0}, {256, 256}};
        vkCmdSetViewport(cmd, 0, 1, &vpr); vkCmdSetScissor(cmd, 0, 1, &scs);
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, fp.pipe);
        vkCmdDraw(cmd, 3, 1, 0, 0);
        vkCmdEndRenderPass(cmd); vkEndCommandBuffer(cmd);
        VkSubmitInfo si = {VK_STRUCTURE_TYPE_SUBMIT_INFO}; si.commandBufferCount = 1; si.pCommandBuffers = &cmd;
        vkQueueSubmit(queue_, 1, &si, VK_NULL_HANDLE); vkQueueWaitIdle(queue_);
        vkFreeCommandBuffers(device_, cmdPool_, 1, &cmd);
        vkDestroyFramebuffer(device_, fb, nullptr);
        destroyFsPipe(device_, fp);
    }

    if (!genCubeMap(irradianceCube_, 32, 1, irradiance_frag_data, sizeof(irradiance_frag_data), false)) return false;
    if (!genCubeMap(prefilterCube_, 128, 5, prefilter_frag_data, sizeof(prefilter_frag_data), true)) return false;

    // Descriptor set (set = 2).
    VkDescriptorPoolSize ps = {VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 3};
    VkDescriptorPoolCreateInfo dpci = {VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};
    dpci.maxSets = 1; dpci.poolSizeCount = 1; dpci.pPoolSizes = &ps;
    if (vkCreateDescriptorPool(device_, &dpci, nullptr, &iblPool_) != VK_SUCCESS) return false;
    VkDescriptorSetAllocateInfo dsai = {VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};
    dsai.descriptorPool = iblPool_; dsai.descriptorSetCount = 1; dsai.pSetLayouts = &iblSetLayout_;
    if (vkAllocateDescriptorSets(device_, &dsai, &iblSet_) != VK_SUCCESS) return false;
    VkDescriptorImageInfo ii[3] = {
        {iblCubeSampler_, irradianceCube_.view, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL},
        {iblCubeSampler_, prefilterCube_.view,  VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL},
        {iblLutSampler_,  brdfLut_.view,        VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL},
    };
    VkWriteDescriptorSet w[3];
    for (uint32_t i = 0; i < 3; ++i) {
        w[i] = {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
        w[i].dstSet = iblSet_; w[i].dstBinding = i; w[i].descriptorCount = 1;
        w[i].descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER; w[i].pImageInfo = &ii[i];
    }
    vkUpdateDescriptorSets(device_, 3, w, 0, nullptr);
    std::printf("ModelRenderer: IBL ready (irradiance 32, prefilter 128x%u, BRDF LUT 256)\n", prefilterCube_.mips);
    return true;
}

VkDescriptorSet ModelRenderer::makeMaterialSet(VkImageView baseColor, VkImageView mr,
                                               VkImageView normal, VkImageView occ,
                                               VkImageView emissive) {
    VkDescriptorSetAllocateInfo ai = {VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};
    ai.descriptorPool = matPool_;
    ai.descriptorSetCount = 1;
    ai.pSetLayouts = &matSetLayout_;
    VkDescriptorSet set = VK_NULL_HANDLE;
    if (vkAllocateDescriptorSets(device_, &ai, &set) != VK_SUCCESS) return VK_NULL_HANDLE;

    VkImageView views[5] = {baseColor, mr, normal, occ, emissive};
    VkDescriptorImageInfo infos[5];
    VkWriteDescriptorSet writes[5];
    for (uint32_t i = 0; i < 5; ++i) {
        infos[i] = {sampler_, views[i], VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL};
        writes[i] = {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
        writes[i].dstSet = set;
        writes[i].dstBinding = i;
        writes[i].descriptorCount = 1;
        writes[i].descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
        writes[i].pImageInfo = &infos[i];
    }
    vkUpdateDescriptorSets(device_, 5, writes, 0, nullptr);
    return set;
}

bool ModelRenderer::finalizeModel(ModelData& md) {
    cleanupModel();

    // Morph models need a CPU-writable vertex buffer (re-blended each frame);
    // everything else keeps the device-local staged upload.
    hasMorph_ = !md.morphs.empty();
    const VkDeviceSize vbSize = md.vertices.size() * sizeof(ModelVertex);
    vertexBuffer_ = modelCreateBuffer(device_, physDevice_, vbSize,
        VK_BUFFER_USAGE_VERTEX_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
        hasMorph_ ? (VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)
                  : VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    indexBuffer_ = modelCreateBuffer(device_, physDevice_,
        md.indices.size() * sizeof(uint32_t),
        VK_BUFFER_USAGE_INDEX_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
        VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (vertexBuffer_.buffer == VK_NULL_HANDLE || indexBuffer_.buffer == VK_NULL_HANDLE) return false;
    if (hasMorph_) {
        // Keep the base verts for re-blending; seed the buffer with them.
        morphBase_ = md.vertices;
        void* mapped = nullptr;
        vkMapMemory(device_, vertexBuffer_.memory, 0, vbSize, 0, &mapped);
        std::memcpy(mapped, md.vertices.data(), (size_t)vbSize);
        vkUnmapMemory(device_, vertexBuffer_.memory);
    } else {
        modelUploadBuffer(device_, physDevice_, queue_, cmdPool_, vertexBuffer_,
                          md.vertices.data(), vertexBuffer_.size);
    }
    modelUploadBuffer(device_, physDevice_, queue_, cmdPool_, indexBuffer_,
                      md.indices.data(), indexBuffer_.size);

    // Upload textures (parallel to md.textures; empty entries stay null).
    modelTextures_.resize(md.textures.size());
    for (size_t i = 0; i < md.textures.size(); ++i)
        if (!md.textures[i].rgba.empty())
            modelTextures_[i] = uploadTexture(md.textures[i]);

    materials_ = std::move(md.materials);
    primitives_ = std::move(md.primitives);

    // Animation graph (Phase 1). Auto-play the first clip; no clips → static
    // fast-path (activeAnim_ stays -1 and updateAnimation is a no-op).
    nodes_ = std::move(md.nodes);
    animations_ = std::move(md.animations);
    rootNodes_ = std::move(md.rootNodes);
    morphs_ = std::move(md.morphs);
    bindNodes_ = nodes_;                  // bind-pose snapshot for clean clip switches
    nodeWorld_.assign(nodes_.size() * 16, 0.0f);
    activeAnim_ = animations_.empty() ? -1 : 0;
    animTime_ = 0.0f;
    paused_ = false;

    // ── Skinning: joint-matrix SSBO (set = 3) ────────────────────────────────
    // Sized to all skins' joints concatenated; ≥1 matrix so static models still
    // bind a valid set 3. Host-visible: updateAnimation memcpy's it each frame.
    // Initialized to identity — the static fast-path then leaves it untouched.
    skins_ = std::move(md.skins);
    jointCount_ = md.totalJoints > 0 ? md.totalJoints : 1;
    jointBuffer_ = modelCreateBuffer(device_, physDevice_,
        (VkDeviceSize)jointCount_ * 16 * sizeof(float),
        VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,
        VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
    if (jointBuffer_.buffer == VK_NULL_HANDLE) return false;
    {
        void* mapped = nullptr;
        vkMapMemory(device_, jointBuffer_.memory, 0, jointBuffer_.size, 0, &mapped);
        const glm::mat4 ident(1.0f);
        for (uint32_t i = 0; i < jointCount_; ++i)
            std::memcpy((char*)mapped + i * 16 * sizeof(float), glm::value_ptr(ident), 16 * sizeof(float));
        vkUnmapMemory(device_, jointBuffer_.memory);
    }
    {
        VkDescriptorPoolSize jps = {VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1};
        VkDescriptorPoolCreateInfo jdpci = {VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};
        jdpci.maxSets = 1;
        jdpci.poolSizeCount = 1;
        jdpci.pPoolSizes = &jps;
        if (vkCreateDescriptorPool(device_, &jdpci, nullptr, &jointPool_) != VK_SUCCESS) return false;
        VkDescriptorSetAllocateInfo jdsai = {VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};
        jdsai.descriptorPool = jointPool_;
        jdsai.descriptorSetCount = 1;
        jdsai.pSetLayouts = &jointSetLayout_;
        if (vkAllocateDescriptorSets(device_, &jdsai, &jointSet_) != VK_SUCCESS) return false;
        VkDescriptorBufferInfo jdbi = {jointBuffer_.buffer, 0, jointBuffer_.size};
        VkWriteDescriptorSet jw = {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
        jw.dstSet = jointSet_;
        jw.dstBinding = 0;
        jw.descriptorCount = 1;
        jw.descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        jw.pBufferInfo = &jdbi;
        vkUpdateDescriptorSets(device_, 1, &jw, 0, nullptr);
    }

    std::memcpy(bboxMin_, md.bboxMin, sizeof(bboxMin_));
    std::memcpy(bboxMax_, md.bboxMax, sizeof(bboxMax_));
    hasBBox_ = md.hasBBox;
    numPrimitives_ = md.primitiveCount;

    // For animated models, replace the bind-pose AABB with the swept animated
    // bounds (correct height/center for the auto-fit). Needs primitives_/nodes_/
    // animations_/skins_ (set above) plus the still-intact CPU verts + indices.
    recomputeAnimatedBounds(md.vertices, md.indices);

    // Apply the rest-pose morph once so a model with nonzero default weights and
    // no clip still shows its morphed shape (animated models re-blend per frame).
    blendMorphs();

    // Per-material descriptor sets (set = 1) + a default for material == -1.
    const uint32_t nSets = (uint32_t)materials_.size() + 1;
    VkDescriptorPoolSize ps = {VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, nSets * 5};
    VkDescriptorPoolCreateInfo dpci = {VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};
    dpci.maxSets = nSets;
    dpci.poolSizeCount = 1;
    dpci.pPoolSizes = &ps;
    if (vkCreateDescriptorPool(device_, &dpci, nullptr, &matPool_) != VK_SUCCESS) return false;

    auto viewOr = [&](int idx, VkImageView def) -> VkImageView {
        if (idx >= 0 && idx < (int)modelTextures_.size() && modelTextures_[idx].view != VK_NULL_HANDLE)
            return modelTextures_[idx].view;
        return def;
    };
    materialSets_.reserve(materials_.size());
    for (const auto& m : materials_) {
        materialSets_.push_back(makeMaterialSet(
            viewOr(m.baseColorTex, whiteTex_.view),
            viewOr(m.metallicRoughnessTex, whiteTex_.view),
            viewOr(m.normalTex, flatNormalTex_.view),
            viewOr(m.occlusionTex, whiteTex_.view),
            viewOr(m.emissiveTex, whiteTex_.view)));
    }
    defaultMatSet_ = makeMaterialSet(whiteTex_.view, whiteTex_.view, flatNormalTex_.view,
                                     whiteTex_.view, whiteTex_.view);

    modelLoaded_ = true;
    return true;
}

bool ModelRenderer::loadModel(const char* gltfPath) {
    if (!initialized_ || !gltfPath) return false;
    ModelData md;
    if (!model_loader_load(gltfPath, md)) return false;
    if (!finalizeModel(md)) return false;
    loadedModelPath_ = gltfPath;
    return true;
}

bool ModelRenderer::loadDebugModel() {
    if (!initialized_) return false;
    ModelData md;
    buildCubeModel(md);
    if (!finalizeModel(md)) return false;
    loadedModelPath_ = "<debug-cube>";
    return true;
}

bool ModelRenderer::hasModel() const { return modelLoaded_; }
const std::string& ModelRenderer::modelPath() const { return loadedModelPath_; }
uint32_t ModelRenderer::primitiveCount() const { return numPrimitives_; }

bool ModelRenderer::getSceneBBox(float outMin[3], float outMax[3]) const {
    if (!modelLoaded_ || !hasBBox_) return false;
    std::memcpy(outMin, bboxMin_, sizeof(bboxMin_));
    std::memcpy(outMax, bboxMax_, sizeof(bboxMax_));
    return true;
}

bool ModelRenderer::getRobustSceneBounds(float, float,
                                         float outCenter[3], float outExtent[3]) const {
    float mn[3], mx[3];
    if (!getSceneBBox(mn, mx)) return false;
    for (int i = 0; i < 3; ++i) {
        outCenter[i] = 0.5f * (mn[i] + mx[i]);
        outExtent[i] = mx[i] - mn[i];
    }
    return true;
}

bool ModelRenderer::pickSurface(const float[3], const float[3], float[3], float) const {
    // TODO(follow-up): ray/triangle intersection against the loaded mesh.
    return false;
}

float ModelRenderer::findBestYaw(const float[3], const float[3], uint32_t) const {
    return 0.0f;  // glTF models are authored front-facing.
}

void ModelRenderer::updateUniforms(const float viewMatrix[16], const float projMatrix[16],
                                   float clipFar) {
    // Mirror gs_renderer: flip world Y at the view stage (right-multiply by
    // diag(1,-1,1,1) → negate view column 1) so the model is upright and
    // consistent with the demo's Y-mirrored display-pose contract.
    float vmFlipped[16];
    std::memcpy(vmFlipped, viewMatrix, sizeof(vmFlipped));
    vmFlipped[4] = -vmFlipped[4];
    vmFlipped[5] = -vmFlipped[5];
    vmFlipped[6] = -vmFlipped[6];
    vmFlipped[7] = -vmFlipped[7];

    UniformBlock ub{};
    mat4Mul(projMatrix, vmFlipped, ub.viewProj);
    // inverse(viewProj) for the skybox per-pixel ray reconstruction.
    glm::mat4 ivp = glm::inverse(glm::make_mat4(ub.viewProj));
    std::memcpy(ub.invViewProj, glm::value_ptr(ivp), 16 * sizeof(float));

    // View matrix with the Z row negated → positive Z = forward (matches
    // gs_renderer / the eye_display.z forward distance), used by the shader's
    // foreground clip. Column-major Z-row indices: 2, 6, 10, 14.
    std::memcpy(ub.view, vmFlipped, sizeof(ub.view));
    ub.view[2]  = -ub.view[2];
    ub.view[6]  = -ub.view[6];
    ub.view[10] = -ub.view[10];
    ub.view[14] = -ub.view[14];

    // Camera world position = -R^T * t from the flipped view matrix.
    float tx = vmFlipped[12], ty = vmFlipped[13], tz = vmFlipped[14];
    ub.cameraPos[0] = -(vmFlipped[0] * tx + vmFlipped[1] * ty + vmFlipped[2] * tz);
    ub.cameraPos[1] = -(vmFlipped[4] * tx + vmFlipped[5] * ty + vmFlipped[6] * tz);
    ub.cameraPos[2] = -(vmFlipped[8] * tx + vmFlipped[9] * ty + vmFlipped[10] * tz);
    // .w = shader gamma-encode flag: encode linear→sRGB at output for a UNORM
    // swapchain (the DisplayXR compositor decodes it for presentation); skip for
    // an sRGB swapchain, whose blit already encodes. Repurposes an unused slot.
    ub.cameraPos[3] = swapchainIsSrgb_ ? 0.0f : 1.0f;

    // Fixed key light (world space), normalized.
    float lx = 0.4f, ly = 0.8f, lz = 0.5f;
    float ln = std::sqrt(lx * lx + ly * ly + lz * lz);
    ub.lightDir[0] = lx / ln; ub.lightDir[1] = ly / ln; ub.lightDir[2] = lz / ln;
    ub.lightDir[3] = (clipFar > 0.0f) ? clipFar : 0.0f;  // foreground clip (view-space)

    void* mapped = nullptr;
    vkMapMemory(device_, uniformBuffer_.memory, 0, sizeof(UniformBlock), 0, &mapped);
    std::memcpy(mapped, &ub, sizeof(UniformBlock));
    vkUnmapMemory(device_, uniformBuffer_.memory);
}

namespace {

// Sample a translation/scale sampler (comps = 3) at time t → out[comps].
// Handles STEP / LINEAR / CUBICSPLINE; clamps outside the keyframe range.
void sampleVec(const AnimSampler& s, int comps, float t, float* out) {
    const std::vector<float>& in = s.input;
    const size_t n = in.size();
    const int stride = (s.interp == AnimInterp::CubicSpline) ? 3 * comps : comps;
    const int valOff = (s.interp == AnimInterp::CubicSpline) ? comps : 0;
    auto val = [&](size_t k) -> const float* { return &s.output[k * stride + valOff]; };

    if (n == 0) { for (int c = 0; c < comps; ++c) out[c] = 0.0f; return; }
    if (t <= in.front() || n == 1) { const float* v = val(0);   for (int c=0;c<comps;++c) out[c]=v[c]; return; }
    if (t >= in.back())            { const float* v = val(n-1); for (int c=0;c<comps;++c) out[c]=v[c]; return; }

    size_t k = 0;
    while (k + 1 < n && in[k + 1] <= t) ++k;   // in[k] <= t < in[k+1]
    const float dt = in[k + 1] - in[k];
    const float u = dt > 0.0f ? (t - in[k]) / dt : 0.0f;

    if (s.interp == AnimInterp::Step) { const float* v = val(k); for (int c=0;c<comps;++c) out[c]=v[c]; return; }
    if (s.interp == AnimInterp::CubicSpline) {
        const float* p0 = val(k);
        const float* p1 = val(k + 1);
        const float* m0 = &s.output[k * stride + 2 * comps];       // out-tangent of key k
        const float* m1 = &s.output[(k + 1) * stride + 0];         // in-tangent of key k+1
        const float u2 = u * u, u3 = u2 * u;
        const float h00 = 2*u3 - 3*u2 + 1, h10 = u3 - 2*u2 + u;
        const float h01 = -2*u3 + 3*u2,    h11 = u3 - u2;
        for (int c = 0; c < comps; ++c)
            out[c] = h00*p0[c] + h10*dt*m0[c] + h01*p1[c] + h11*dt*m1[c];
        return;
    }
    const float* v0 = val(k); const float* v1 = val(k + 1);   // LINEAR
    for (int c = 0; c < comps; ++c) out[c] = v0[c] + (v1[c] - v0[c]) * u;
}

// glTF quat (x,y,z,w) at output offset → glm::quat (w,x,y,z).
glm::quat quatFrom(const std::vector<float>& o, size_t base) {
    return glm::quat(o[base + 3], o[base + 0], o[base + 1], o[base + 2]);
}

// Sample a rotation sampler at time t → normalized quaternion. LINEAR uses
// slerp; CUBICSPLINE does the Hermite on quat components then renormalizes.
glm::quat sampleQuat(const AnimSampler& s, float t) {
    const std::vector<float>& in = s.input;
    const size_t n = in.size();
    const int stride = (s.interp == AnimInterp::CubicSpline) ? 12 : 4;
    const int valOff = (s.interp == AnimInterp::CubicSpline) ? 4 : 0;

    if (n == 0) return glm::quat(1, 0, 0, 0);
    if (t <= in.front() || n == 1) return glm::normalize(quatFrom(s.output, 0 * stride + valOff));
    if (t >= in.back())            return glm::normalize(quatFrom(s.output, (n-1) * stride + valOff));

    size_t k = 0;
    while (k + 1 < n && in[k + 1] <= t) ++k;
    const float dt = in[k + 1] - in[k];
    const float u = dt > 0.0f ? (t - in[k]) / dt : 0.0f;

    if (s.interp == AnimInterp::Step)
        return glm::normalize(quatFrom(s.output, k * stride + valOff));
    if (s.interp == AnimInterp::CubicSpline) {
        const glm::quat p0 = quatFrom(s.output, k * stride + valOff);
        const glm::quat p1 = quatFrom(s.output, (k + 1) * stride + valOff);
        const glm::quat m0 = quatFrom(s.output, k * stride + 8);        // out-tangent k
        const glm::quat m1 = quatFrom(s.output, (k + 1) * stride + 0);  // in-tangent k+1
        const float u2 = u * u, u3 = u2 * u;
        const float h00 = 2*u3 - 3*u2 + 1, h10 = u3 - 2*u2 + u;
        const float h01 = -2*u3 + 3*u2,    h11 = u3 - u2;
        glm::quat q = p0*h00 + m0*(h10*dt) + p1*h01 + m1*(h11*dt);
        return glm::normalize(q);
    }
    return glm::normalize(glm::slerp(glm::normalize(quatFrom(s.output, k * stride)),
                                     glm::normalize(quatFrom(s.output, (k + 1) * stride)), u));
}

// Compose a node's local matrix from its (possibly animated) TRS, or its
// explicit matrix.
glm::mat4 nodeLocal(const ModelNode& n) {
    if (n.hasMatrix) return glm::make_mat4(n.matrix);
    glm::mat4 T = glm::translate(glm::mat4(1.0f),
                                 glm::vec3(n.translation[0], n.translation[1], n.translation[2]));
    glm::mat4 R = glm::mat4_cast(glm::quat(n.rotation[3], n.rotation[0], n.rotation[1], n.rotation[2]));
    glm::mat4 S = glm::scale(glm::mat4(1.0f),
                             glm::vec3(n.scale[0], n.scale[1], n.scale[2]));
    return T * R * S;
}

}  // namespace

void ModelRenderer::updateAnimation(float dtSeconds) {
    // Static fast-path: no clip → primitives keep their once-baked modelMatrix.
    if (activeAnim_ < 0 || activeAnim_ >= (int)animations_.size()) return;
    const Animation& anim = animations_[activeAnim_];

    // Advance + loop the playhead within the clip duration (frozen when paused;
    // the pose below is still recomputed so the held frame stays correct).
    if (!paused_) {
        animTime_ += dtSeconds;
        if (anim.duration > 0.0f) {
            animTime_ = std::fmod(animTime_, anim.duration);
            if (animTime_ < 0.0f) animTime_ += anim.duration;
        }
    }

    // 1) Sample each channel → write the ABSOLUTE TRS value into its target
    //    node. Channel-driven components are fully recomputed every frame, so
    //    mutating nodes_ in place is safe; untargeted components keep their base.
    for (const AnimChannel& ch : anim.channels) {
        const AnimSampler& s = anim.samplers[ch.sampler];
        ModelNode& node = nodes_[ch.targetNode];
        switch (ch.path) {
            case AnimPath::Translation: sampleVec(s, 3, animTime_, node.translation); break;
            case AnimPath::Scale:       sampleVec(s, 3, animTime_, node.scale);       break;
            case AnimPath::Rotation: {
                glm::quat q = sampleQuat(s, animTime_);
                node.rotation[0] = q.x; node.rotation[1] = q.y;
                node.rotation[2] = q.z; node.rotation[3] = q.w;
                break;
            }
            case AnimPath::Weights:
                if (!node.weights.empty())
                    sampleVec(s, (int)node.weights.size(), animTime_, node.weights.data());
                break;
        }
    }

    // 2) Re-walk the hierarchy (parent before child via DFS) → world matrices.
    for (int root : rootNodes_) {
        // Iterative DFS; each node's parent world is already written when popped.
        std::vector<int> stack(1, root);
        while (!stack.empty()) {
            int idx = stack.back(); stack.pop_back();
            if (idx < 0 || idx >= (int)nodes_.size()) continue;
            const ModelNode& n = nodes_[idx];
            glm::mat4 parentW = (n.parent >= 0 && n.parent < (int)nodes_.size())
                ? glm::make_mat4(&nodeWorld_[n.parent * 16]) : glm::mat4(1.0f);
            glm::mat4 world = parentW * nodeLocal(n);
            std::memcpy(&nodeWorld_[idx * 16], glm::value_ptr(world), 16 * sizeof(float));
            for (int c : n.children) stack.push_back(c);
        }
    }

    // 3) Refresh each primitive's model matrix from its owning node.
    for (ModelPrimitive& p : primitives_) {
        if (p.node >= 0 && p.node < (int)nodes_.size())
            std::memcpy(p.modelMatrix, &nodeWorld_[p.node * 16], 16 * sizeof(float));
    }

    // Display-rig bind anchor: world centroid of the moving subject, tracked so
    // the convergence plane stays on it. Skeleton mean for skinned models;
    // morphed-vertex mean (computed in blendMorphs below) otherwise.
    glm::vec3 anchorRaw(0.0f);
    bool anchorValid = false;

    // 4) Recompute joint matrices from the freshly walked hierarchy and push
    //    them to the SSBO. jointMatrix[i] = nodeWorld[joint_i] * inverseBind[i]
    //    (the skinned mesh node's own transform is intentionally omitted — see
    //    ModelSkin). Static skinned models keep the identity SSBO from
    //    finalizeModel, which is exactly the bind pose, so this only runs when a
    //    clip is animating the skeleton.
    if (!skins_.empty()) {
        void* mapped = nullptr;
        vkMapMemory(device_, jointBuffer_.memory, 0, jointBuffer_.size, 0, &mapped);
        uint32_t base = 0;
        glm::dvec3 centroid(0.0);   // accumulate joint world positions for the rig bind
        uint32_t jointTotal = 0;
        for (const ModelSkin& s : skins_) {
            for (size_t j = 0; j < s.joints.size(); ++j) {
                const int node = s.joints[j];
                const glm::mat4 nw = (node >= 0 && node < (int)nodes_.size())
                    ? glm::make_mat4(&nodeWorld_[node * 16]) : glm::mat4(1.0f);
                const glm::mat4 jm = nw * glm::make_mat4(&s.inverseBind[j * 16]);
                std::memcpy((char*)mapped + (base + j) * 16 * sizeof(float),
                            glm::value_ptr(jm), 16 * sizeof(float));
                centroid += glm::dvec3(nw[3]);   // joint world translation
                ++jointTotal;
            }
            base += (uint32_t)s.joints.size();
        }
        vkUnmapMemory(device_, jointBuffer_.memory);

        if (jointTotal > 0) {
            anchorRaw = glm::vec3(centroid / (double)jointTotal);
            // Lift the skeleton mean onto the model's visual centre (see
            // recomputeAnimatedBounds) so joint-free geometry up high (a hat)
            // doesn't make the subject ride off-centre. No-op (~0) for rigs whose
            // joints already span the mesh.
            if (anchorOffsetValid_) {
                anchorRaw.x += anchorOffset_[0];
                anchorRaw.y += anchorOffset_[1];
                anchorRaw.z += anchorOffset_[2];
            }
            anchorValid = true;
        }
    }

    // 5) Re-blend morph targets into the (host-visible) vertex buffer. Runs
    //    after the node walk so the Weights channels above are applied; morphed
    //    verts are then skinned by the GPU (morph→skin, the glTF-correct order).
    //    trackAnchor → it also computes the morphed-vertex world centroid.
    blendMorphs(true);
    if (!anchorValid && morphCentroidValid_) {
        anchorRaw = glm::vec3(morphCentroid_[0], morphCentroid_[1], morphCentroid_[2]);
        anchorValid = true;
    }

    // Smooth the chosen anchor into animAnchor_: snap on the first frame, then
    // ease with a ~0.15 s time constant so a pose/shape pop doesn't jerk the
    // frame. Tracks all 3 axes (subject stays pinned + centered at the ZDP).
    if (anchorValid) {
        if (!animAnchorValid_) {
            animAnchor_[0] = anchorRaw.x; animAnchor_[1] = anchorRaw.y; animAnchor_[2] = anchorRaw.z;
            animAnchorValid_ = true;
        } else {
            const float a = 1.0f - std::exp(-dtSeconds / 0.15f);
            animAnchor_[0] += (anchorRaw.x - animAnchor_[0]) * a;
            animAnchor_[1] += (anchorRaw.y - animAnchor_[1]) * a;
            animAnchor_[2] += (anchorRaw.z - animAnchor_[2]) * a;
        }
    }
}

bool ModelRenderer::getAnimatedAnchor(float out[3]) const {
    if (!modelLoaded_ || !animAnchorValid_) return false;
    out[0] = animAnchor_[0]; out[1] = animAnchor_[1]; out[2] = animAnchor_[2];
    return true;
}

void ModelRenderer::setActiveAnimation(int index) {
    const int n = (int)animations_.size();
    if (n == 0) return;
    activeAnim_ = ((index % n) + n) % n;   // wrap
    animTime_ = 0.0f;
    // Channels mutate nodes_ in place with absolute TRS; restore the bind pose
    // so a node the new clip doesn't target can't keep the old clip's value.
    if (bindNodes_.size() == nodes_.size()) nodes_ = bindNodes_;
    animAnchorValid_ = false;              // re-snap the rig bind to the new clip
}

void ModelRenderer::cycleAnimation() {
    if (animations_.size() < 2) return;
    setActiveAnimation(activeAnim_ + 1);
}

void ModelRenderer::togglePaused() {
    if (!animations_.empty()) paused_ = !paused_;
}

bool ModelRenderer::getPlaybackInfo(std::string& name, int& index, int& count,
                                    float& time, float& duration, bool& playing) const {
    count = (int)animations_.size();
    if (count == 0 || activeAnim_ < 0 || activeAnim_ >= count) return false;
    const Animation& a = animations_[activeAnim_];
    index = activeAnim_;
    name = a.name.empty() ? ("Clip " + std::to_string(activeAnim_)) : a.name;
    time = animTime_;
    duration = a.duration;
    playing = !paused_;
    return true;
}

void ModelRenderer::blendMorphs(bool trackAnchor) {
    if (!hasMorph_ || vertexBuffer_.buffer == VK_NULL_HANDLE) return;
    void* mapped = nullptr;
    vkMapMemory(device_, vertexBuffer_.memory, 0, vertexBuffer_.size, 0, &mapped);
    ModelVertex* dst = static_cast<ModelVertex*>(mapped);
    glm::dvec3 sum(0.0);   // morphed-vertex world centroid for the rig bind
    uint64_t   cnt = 0;
    for (const ModelPrimitive& p : primitives_) {
        if (p.morph < 0 || p.morph >= (int)morphs_.size()) continue;
        const ModelMorph& mm = morphs_[p.morph];
        const std::vector<float>* w = (p.node >= 0 && p.node < (int)nodes_.size())
            ? &nodes_[p.node].weights : nullptr;
        // World transform of the owning node (nodeWorld_ is fresh from the walk
        // when trackAnchor; identity otherwise / at finalize).
        const glm::mat4 nodeW = (trackAnchor && p.node >= 0 && p.node < (int)nodes_.size())
            ? glm::make_mat4(&nodeWorld_[p.node * 16]) : glm::mat4(1.0f);
        for (uint32_t v = 0; v < p.vertexCount; ++v) {
            const uint32_t vi = p.firstVertex + v;
            ModelVertex out = morphBase_[vi];   // base pos/normal + static uv/joints/weights
            if (w) {
                for (uint32_t t = 0; t < mm.targetCount && t < w->size(); ++t) {
                    const float wt = (*w)[t];
                    if (wt == 0.0f) continue;
                    const size_t off = ((size_t)t * mm.vertexCount + v) * 3;
                    out.pos[0] += wt * mm.posDeltas[off + 0];
                    out.pos[1] += wt * mm.posDeltas[off + 1];
                    out.pos[2] += wt * mm.posDeltas[off + 2];
                    if (!mm.nrmDeltas.empty()) {
                        out.normal[0] += wt * mm.nrmDeltas[off + 0];
                        out.normal[1] += wt * mm.nrmDeltas[off + 1];
                        out.normal[2] += wt * mm.nrmDeltas[off + 2];
                    }
                }
            }
            dst[vi] = out;
            if (trackAnchor) {
                sum += glm::dvec3(nodeW * glm::vec4(out.pos[0], out.pos[1], out.pos[2], 1.0f));
                ++cnt;
            }
        }
    }
    vkUnmapMemory(device_, vertexBuffer_.memory);

    if (trackAnchor) {
        morphCentroidValid_ = cnt > 0;
        if (cnt > 0) {
            const glm::dvec3 c = sum / (double)cnt;
            morphCentroid_[0] = (float)c.x; morphCentroid_[1] = (float)c.y; morphCentroid_[2] = (float)c.z;
        }
    }
}

void ModelRenderer::recomputeAnimatedBounds(const std::vector<ModelVertex>& verts,
                                            const std::vector<uint32_t>& indices) {
    if (activeAnim_ < 0 || activeAnim_ >= (int)animations_.size()) return;  // keep static box
    if (verts.empty() || indices.empty() || nodes_.empty()) return;
    const Animation& anim = animations_[activeAnim_];

    // Sample the clip at N evenly-spaced times and union the skinned bounds.
    // Subsample very dense meshes so load stays snappy (the box is robust to it).
    const int N = 24;
    const uint32_t step = indices.size() > 200000u
        ? (uint32_t)(indices.size() / 200000u) + 1u : 1u;
    std::vector<float> world(nodes_.size() * 16, 0.0f);
    std::vector<float> jmats(std::max<uint32_t>(jointCount_, 1u) * 16, 0.0f);

    bool has = false;
    glm::vec3 mn(0.0f), mx(0.0f);
    glm::dvec3 centroidSum(0.0);   // mean joint position summed over all samples
    uint32_t centroidCount = 0;    // (for the anchor visual-centre correction)
    for (int si = 0; si < N; ++si) {
        const float t = (anim.duration > 0.0f && N > 1)
            ? anim.duration * (float)si / (float)(N - 1) : 0.0f;

        // Sample channels onto a fresh copy of the bind-pose TRS.
        std::vector<ModelNode> nd = nodes_;
        for (const AnimChannel& ch : anim.channels) {
            const AnimSampler& s = anim.samplers[ch.sampler];
            ModelNode& node = nd[ch.targetNode];
            switch (ch.path) {
                case AnimPath::Translation: sampleVec(s, 3, t, node.translation); break;
                case AnimPath::Scale:       sampleVec(s, 3, t, node.scale);       break;
                case AnimPath::Rotation: {
                    glm::quat q = sampleQuat(s, t);
                    node.rotation[0]=q.x; node.rotation[1]=q.y; node.rotation[2]=q.z; node.rotation[3]=q.w;
                } break;
                case AnimPath::Weights:
                    if (!node.weights.empty())
                        sampleVec(s, (int)node.weights.size(), t, node.weights.data());
                    break;
            }
        }
        // Walk hierarchy → world matrices (parent before child).
        for (int root : rootNodes_) {
            std::vector<int> stack(1, root);
            while (!stack.empty()) {
                int idx = stack.back(); stack.pop_back();
                if (idx < 0 || idx >= (int)nd.size()) continue;
                const ModelNode& n = nd[idx];
                glm::mat4 pw = (n.parent >= 0 && n.parent < (int)nd.size())
                    ? glm::make_mat4(&world[n.parent * 16]) : glm::mat4(1.0f);
                glm::mat4 w = pw * nodeLocal(n);
                std::memcpy(&world[idx * 16], glm::value_ptr(w), 16 * sizeof(float));
                for (int c : n.children) stack.push_back(c);
            }
        }
        // Joint matrices, same packing as updateAnimation.
        uint32_t base = 0;
        for (const ModelSkin& sk : skins_) {
            for (size_t j = 0; j < sk.joints.size(); ++j) {
                const int node = sk.joints[j];
                glm::mat4 nw = (node >= 0 && node < (int)nd.size())
                    ? glm::make_mat4(&world[node * 16]) : glm::mat4(1.0f);
                glm::mat4 jm = nw * glm::make_mat4(&sk.inverseBind[j * 16]);
                std::memcpy(&jmats[(base + j) * 16], glm::value_ptr(jm), 16 * sizeof(float));
                centroidSum += glm::dvec3(nw[3]); ++centroidCount;   // joint world pos
            }
            base += (uint32_t)sk.joints.size();
        }
        // Transform each primitive's verts (morphed, then skinned/static) and union.
        for (const ModelPrimitive& p : primitives_) {
            const ModelMorph* mm = (p.morph >= 0 && p.morph < (int)morphs_.size())
                ? &morphs_[p.morph] : nullptr;
            const std::vector<float>* mw = (mm && p.node >= 0 && p.node < (int)nd.size())
                ? &nd[p.node].weights : nullptr;
            for (uint32_t ii = 0; ii < p.indexCount; ii += step) {
                const uint32_t gv = indices[p.firstIndex + ii];
                const ModelVertex& v = verts[gv];
                glm::vec3 lp3(v.pos[0], v.pos[1], v.pos[2]);
                if (mm && mw) {
                    const uint32_t lv = gv - p.firstVertex;   // vertex index within the prim
                    for (uint32_t tt = 0; tt < mm->targetCount && tt < mw->size(); ++tt) {
                        const float wt = (*mw)[tt];
                        if (wt == 0.0f) continue;
                        const size_t off = ((size_t)tt * mm->vertexCount + lv) * 3;
                        lp3.x += wt * mm->posDeltas[off + 0];
                        lp3.y += wt * mm->posDeltas[off + 1];
                        lp3.z += wt * mm->posDeltas[off + 2];
                    }
                }
                const glm::vec4 lp(lp3, 1.0f);
                glm::vec4 wp;
                if (p.skin >= 0) {
                    glm::mat4 m =
                        v.weights0[0] * glm::make_mat4(&jmats[(p.jointBase + v.joints0[0]) * 16]) +
                        v.weights0[1] * glm::make_mat4(&jmats[(p.jointBase + v.joints0[1]) * 16]) +
                        v.weights0[2] * glm::make_mat4(&jmats[(p.jointBase + v.joints0[2]) * 16]) +
                        v.weights0[3] * glm::make_mat4(&jmats[(p.jointBase + v.joints0[3]) * 16]);
                    wp = m * lp;
                } else {
                    wp = (p.node >= 0 && p.node < (int)nd.size())
                        ? glm::make_mat4(&world[p.node * 16]) * lp : lp;
                }
                if (!has) { mn = mx = glm::vec3(wp); has = true; }
                else { mn = glm::min(mn, glm::vec3(wp)); mx = glm::max(mx, glm::vec3(wp)); }
            }
        }
    }
    if (has) {
        bboxMin_[0]=mn.x; bboxMin_[1]=mn.y; bboxMin_[2]=mn.z;
        bboxMax_[0]=mx.x; bboxMax_[1]=mx.y; bboxMax_[2]=mx.z;
        hasBBox_ = true;
        // Offset that lifts the per-frame skeleton-centroid anchor onto the
        // model's visual centre (the AABB centre), so joint-free geometry like a
        // hat doesn't make the subject ride off-centre. ~0 for rigs whose joints
        // already span the mesh; applied in updateAnimation.
        if (centroidCount > 0) {
            const glm::vec3 c = glm::vec3(centroidSum / (double)centroidCount);
            anchorOffset_[0] = 0.5f * (mn.x + mx.x) - c.x;
            anchorOffset_[1] = 0.5f * (mn.y + mx.y) - c.y;
            anchorOffset_[2] = 0.5f * (mn.z + mx.z) - c.z;
            anchorOffsetValid_ = true;
        }
    }
}

void ModelRenderer::renderEye(VkImage swapchainImage,
                              VkFormat swapchainFormat,
                              uint32_t imageWidth,
                              uint32_t imageHeight,
                              uint32_t viewportX,
                              uint32_t viewportY,
                              uint32_t viewportWidth,
                              uint32_t viewportHeight,
                              const float viewMatrix[16],
                              const float projMatrix[16],
                              bool transparentBg,
                              float clipFarViewSpace) {
    if (!initialized_ || !modelLoaded_) return;

    // Size the internal targets to the SWAPCHAIN (stable), not the per-eye
    // viewport — the viewport is set via renderArea/scissor each frame and is
    // always ≤ the framebuffer. Recreate only if the swapchain itself changes
    // size, so a window resize doesn't churn (destroy/recreate) the targets.
    if (imageWidth != width_ || imageHeight != height_) {
        if (!ensureTargets(imageWidth, imageHeight)) return;
    }

    // An sRGB swapchain gets the linear→sRGB encode for free from the blit's HW
    // write; a UNORM swapchain needs the shader to encode (see updateUniforms).
    swapchainIsSrgb_ = (swapchainFormat == VK_FORMAT_R8G8B8A8_SRGB ||
                        swapchainFormat == VK_FORMAT_B8G8R8A8_SRGB ||
                        swapchainFormat == VK_FORMAT_A8B8G8R8_SRGB_PACK32);

    updateUniforms(viewMatrix, projMatrix, clipFarViewSpace);

    VkCommandBufferAllocateInfo ai = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};
    ai.commandPool = cmdPool_;
    ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
    ai.commandBufferCount = 1;
    VkCommandBuffer cmd;
    vkAllocateCommandBuffers(device_, &ai, &cmd);
    VkCommandBufferBeginInfo bi = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(cmd, &bi);

    VkClearValue clears[2];
    if (transparentBg) clears[0].color = {{0.0f, 0.0f, 0.0f, 0.0f}};
    else               clears[0].color = {{0.05f, 0.05f, 0.06f, 1.0f}};
    clears[1].depthStencil = {1.0f, 0};

    VkRenderPassBeginInfo rpbi = {VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO};
    rpbi.renderPass = renderPass_;
    rpbi.framebuffer = framebuffer_;
    rpbi.renderArea.offset = {0, 0};
    rpbi.renderArea.extent = {viewportWidth, viewportHeight};
    rpbi.clearValueCount = 2;
    rpbi.pClearValues = clears;
    vkCmdBeginRenderPass(cmd, &rpbi, VK_SUBPASS_CONTENTS_INLINE);

    VkViewport vpRect = {0.0f, 0.0f, (float)viewportWidth, (float)viewportHeight, 0.0f, 1.0f};
    VkRect2D scissor = {{0, 0}, {viewportWidth, viewportHeight}};
    vkCmdSetViewport(cmd, 0, 1, &vpRect);
    vkCmdSetScissor(cmd, 0, 1, &scissor);

    // Set 0 (camera UBO) + set 2 (IBL): constant for the frame, shared by the
    // skybox and model pipelines (same layout).
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipelineLayout_, 0, 1, &descriptorSet_, 0, nullptr);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipelineLayout_, 2, 1, &iblSet_, 0, nullptr);
    // Set 3 (joint-matrix SSBO): one buffer for the whole model, bound once.
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipelineLayout_, 3, 1, &jointSet_, 0, nullptr);

    // Opaque mode: paint the analytic sky behind the model. Skipped in
    // transparent mode so the desktop shows through (depth untouched).
    if (!transparentBg) {
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, skyboxPipeline_);
        vkCmdDraw(cmd, 3, 1, 0, 0);
    }

    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline_);
    VkDeviceSize voff = 0;
    vkCmdBindVertexBuffers(cmd, 0, 1, &vertexBuffer_.buffer, &voff);
    vkCmdBindIndexBuffer(cmd, indexBuffer_.buffer, 0, VK_INDEX_TYPE_UINT32);

    for (const auto& p : primitives_) {
        PushBlock pb{};
        ModelMaterial m;  // defaults if material == -1
        if (p.material >= 0 && p.material < (int)materials_.size()) m = materials_[p.material];
        std::memcpy(pb.baseColorFactor, m.baseColorFactor, sizeof(pb.baseColorFactor));
        pb.mrParams[0] = m.metallic;
        pb.mrParams[1] = m.roughness;
        if (p.skin >= 0) {
            // Skinned: identity model — the joint matrices carry the full
            // skin→world transform. mrParams.z flags the shader; .w = jointBase.
            const glm::mat4 ident(1.0f);
            std::memcpy(pb.model, glm::value_ptr(ident), sizeof(pb.model));
            pb.mrParams[2] = 1.0f;
            pb.mrParams[3] = (float)p.jointBase;
        } else {
            std::memcpy(pb.model, p.modelMatrix, sizeof(pb.model));
            pb.mrParams[2] = 0.0f;
        }
        pb.emissive[0] = m.emissive[0];
        pb.emissive[1] = m.emissive[1];
        pb.emissive[2] = m.emissive[2];
        vkCmdPushConstants(cmd, pipelineLayout_,
                           VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
                           0, sizeof(PushBlock), &pb);

        // Set 1: this primitive's material textures (or the all-defaults set).
        VkDescriptorSet matSet =
            (p.material >= 0 && p.material < (int)materialSets_.size())
                ? materialSets_[p.material] : defaultMatSet_;
        vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipelineLayout_,
                                1, 1, &matSet, 0, nullptr);

        vkCmdDrawIndexed(cmd, p.indexCount, 1, p.firstIndex, 0, 0);
    }

    vkCmdEndRenderPass(cmd);
    // colorImage_ is now in TRANSFER_SRC_OPTIMAL (render-pass finalLayout).

    // Swapchain → TRANSFER_DST. First eye (vpX==0): UNDEFINED ok. Second eye:
    // preserve the first by treating the prior contents as COLOR_ATTACHMENT.
    VkImageMemoryBarrier toDst = {VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};
    toDst.srcAccessMask = (viewportX == 0) ? 0 : VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
    toDst.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    toDst.oldLayout = (viewportX == 0) ? VK_IMAGE_LAYOUT_UNDEFINED
                                       : VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
    toDst.newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
    toDst.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    toDst.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    toDst.image = swapchainImage;
    toDst.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT,
                         0, 0, nullptr, 0, nullptr, 1, &toDst);

    // Blit [0,0]-[vpW,vpH] of the internal image into the swapchain viewport
    // (handles RGBA→BGRA format conversion, matching gs_renderer).
    VkImageBlit blit = {};
    blit.srcSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
    blit.srcOffsets[0] = {0, 0, 0};
    blit.srcOffsets[1] = {(int32_t)viewportWidth, (int32_t)viewportHeight, 1};
    blit.dstSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
    blit.dstOffsets[0] = {(int32_t)viewportX, (int32_t)viewportY, 0};
    blit.dstOffsets[1] = {(int32_t)(viewportX + viewportWidth),
                          (int32_t)(viewportY + viewportHeight), 1};
    vkCmdBlitImage(cmd,
        colorImage_.image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
        swapchainImage, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
        1, &blit, VK_FILTER_LINEAR);

    // Swapchain → COLOR_ATTACHMENT_OPTIMAL for the compositor.
    VkImageMemoryBarrier toColor = toDst;
    toColor.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    toColor.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
    toColor.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
    toColor.newLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT,
                         VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
                         0, 0, nullptr, 0, nullptr, 1, &toColor);

    vkEndCommandBuffer(cmd);
    VkSubmitInfo si = {VK_STRUCTURE_TYPE_SUBMIT_INFO};
    si.commandBufferCount = 1;
    si.pCommandBuffers = &cmd;
    vkQueueSubmit(queue_, 1, &si, VK_NULL_HANDLE);
    vkQueueWaitIdle(queue_);
    vkFreeCommandBuffers(device_, cmdPool_, 1, &cmd);
}

void ModelRenderer::cleanupModel() {
    if (vertexBuffer_.buffer != VK_NULL_HANDLE) modelDestroyBuffer(device_, vertexBuffer_);
    if (indexBuffer_.buffer != VK_NULL_HANDLE) modelDestroyBuffer(device_, indexBuffer_);
    for (auto& t : modelTextures_)
        if (t.image != VK_NULL_HANDLE) modelDestroyImage(device_, t);
    modelTextures_.clear();
    // Freeing the pool frees all material sets allocated from it.
    if (matPool_ != VK_NULL_HANDLE) { vkDestroyDescriptorPool(device_, matPool_, nullptr); matPool_ = VK_NULL_HANDLE; }
    materialSets_.clear();
    defaultMatSet_ = VK_NULL_HANDLE;
    // Joint-matrix SSBO + its pool (frees jointSet_).
    if (jointBuffer_.buffer != VK_NULL_HANDLE) modelDestroyBuffer(device_, jointBuffer_);
    if (jointPool_ != VK_NULL_HANDLE) { vkDestroyDescriptorPool(device_, jointPool_, nullptr); jointPool_ = VK_NULL_HANDLE; }
    jointSet_ = VK_NULL_HANDLE;
    skins_.clear();
    jointCount_ = 0;
    morphs_.clear();
    morphBase_.clear();
    hasMorph_ = false;
    morphCentroidValid_ = false;
    materials_.clear();
    primitives_.clear();
    nodes_.clear();
    animations_.clear();
    rootNodes_.clear();
    nodeWorld_.clear();
    activeAnim_ = -1;
    animTime_ = 0.0f;
    paused_ = false;
    bindNodes_.clear();
    animAnchorValid_ = false;
    hasBBox_ = false;
    numPrimitives_ = 0;
    modelLoaded_ = false;
    loadedModelPath_.clear();
}

void ModelRenderer::cleanup() {
    if (!initialized_ && cmdPool_ == VK_NULL_HANDLE) return;
    if (device_ != VK_NULL_HANDLE) vkDeviceWaitIdle(device_);

    cleanupModel();

    if (sampler_ != VK_NULL_HANDLE) { vkDestroySampler(device_, sampler_, nullptr); sampler_ = VK_NULL_HANDLE; }
    if (whiteTex_.image != VK_NULL_HANDLE) modelDestroyImage(device_, whiteTex_);
    if (flatNormalTex_.image != VK_NULL_HANDLE) modelDestroyImage(device_, flatNormalTex_);
    if (matSetLayout_ != VK_NULL_HANDLE) { vkDestroyDescriptorSetLayout(device_, matSetLayout_, nullptr); matSetLayout_ = VK_NULL_HANDLE; }

    // IBL resources.
    if (iblPool_ != VK_NULL_HANDLE) { vkDestroyDescriptorPool(device_, iblPool_, nullptr); iblPool_ = VK_NULL_HANDLE; }
    if (iblSetLayout_ != VK_NULL_HANDLE) { vkDestroyDescriptorSetLayout(device_, iblSetLayout_, nullptr); iblSetLayout_ = VK_NULL_HANDLE; }
    if (iblCubeSampler_ != VK_NULL_HANDLE) { vkDestroySampler(device_, iblCubeSampler_, nullptr); iblCubeSampler_ = VK_NULL_HANDLE; }
    if (iblLutSampler_ != VK_NULL_HANDLE) { vkDestroySampler(device_, iblLutSampler_, nullptr); iblLutSampler_ = VK_NULL_HANDLE; }
    if (brdfLut_.image != VK_NULL_HANDLE) modelDestroyImage(device_, brdfLut_);
    for (CubeMap* c : {&irradianceCube_, &prefilterCube_}) {
        if (c->view != VK_NULL_HANDLE) vkDestroyImageView(device_, c->view, nullptr);
        if (c->image != VK_NULL_HANDLE) vkDestroyImage(device_, c->image, nullptr);
        if (c->memory != VK_NULL_HANDLE) vkFreeMemory(device_, c->memory, nullptr);
        *c = {};
    }
    if (uniformBuffer_.buffer != VK_NULL_HANDLE) modelDestroyBuffer(device_, uniformBuffer_);
    if (descriptorPool_ != VK_NULL_HANDLE) { vkDestroyDescriptorPool(device_, descriptorPool_, nullptr); descriptorPool_ = VK_NULL_HANDLE; }
    if (pipeline_ != VK_NULL_HANDLE) { vkDestroyPipeline(device_, pipeline_, nullptr); pipeline_ = VK_NULL_HANDLE; }
    if (skyboxPipeline_ != VK_NULL_HANDLE) { vkDestroyPipeline(device_, skyboxPipeline_, nullptr); skyboxPipeline_ = VK_NULL_HANDLE; }
    if (pipelineLayout_ != VK_NULL_HANDLE) { vkDestroyPipelineLayout(device_, pipelineLayout_, nullptr); pipelineLayout_ = VK_NULL_HANDLE; }
    if (dsLayout_ != VK_NULL_HANDLE) { vkDestroyDescriptorSetLayout(device_, dsLayout_, nullptr); dsLayout_ = VK_NULL_HANDLE; }
    if (jointSetLayout_ != VK_NULL_HANDLE) { vkDestroyDescriptorSetLayout(device_, jointSetLayout_, nullptr); jointSetLayout_ = VK_NULL_HANDLE; }
    if (framebuffer_ != VK_NULL_HANDLE) { vkDestroyFramebuffer(device_, framebuffer_, nullptr); framebuffer_ = VK_NULL_HANDLE; }
    if (renderPass_ != VK_NULL_HANDLE) { vkDestroyRenderPass(device_, renderPass_, nullptr); renderPass_ = VK_NULL_HANDLE; }
    if (colorImage_.image != VK_NULL_HANDLE) modelDestroyImage(device_, colorImage_);
    if (depthImage_.image != VK_NULL_HANDLE) modelDestroyImage(device_, depthImage_);
    if (cmdPool_ != VK_NULL_HANDLE) { vkDestroyCommandPool(device_, cmdPool_, nullptr); cmdPool_ = VK_NULL_HANDLE; }

    initialized_ = false;
}

ModelRenderer::~ModelRenderer() { cleanup(); }
