#!/bin/bash
# Regenerate scene_spv.h (embedded SPIR-V) from scene.vert / scene.frag.
# The build does not run this: the generated header is committed, so the app
# needs no shader compiler (same convention as the cube apps' embedded SPIR-V).
set -euo pipefail
cd "$(dirname "$0")"
glslangValidator -V --vn g_scene_vert_spv -o scene_vert_spv.inc scene.vert
glslangValidator -V --vn g_scene_frag_spv -o scene_frag_spv.inc scene.frag
{
  echo "// Generated by compile.sh from scene.vert / scene.frag — do not edit."
  echo "// SPDX-License-Identifier: BSL-1.0"
  echo "#pragma once"
  echo "#include <cstdint>"
  sed 's/^const uint32_t/static const uint32_t/' scene_vert_spv.inc
  sed 's/^const uint32_t/static const uint32_t/' scene_frag_spv.inc
} > scene_spv.h
rm -f scene_vert_spv.inc scene_frag_spv.inc
echo "wrote $(pwd)/scene_spv.h"
