#!/bin/bash
# One-command Linux hardware-test harness (#660, Phase 1b/2b/3b).
#
# Builds the runtime (+ its OpenXR loader + sim-display plug-in), then launches a
# chosen target — a runtime cube app or one of the 5 demos — against that dev
# runtime by delegating to the target's own run script (which handles its loader)
# while exporting XR_RUNTIME_JSON + XRT_PLUGIN_SEARCH_PATH + SIM_DISPLAY_OUTPUT so
# they all point at the runtime we just built.
#
# Needs a Vulkan GPU + an X server (a real X11 session, or XWayland). No Leia
# hardware required: sim-display weaves anaglyph/SBS to a normal monitor.
#
# Usage:
#   ./scripts/run_linux_demo.sh <target> [--output=anaglyph|sbs|...] [--rebuild]
#                                        [--demo-dir=PATH] [--list]
#
#   <target>:
#     cube-hosted   runtime self-creates the window   (Phase 1b)
#     cube-handle   app passes its own X11 window      (Phase 3b)
#     mediaplayer | gaussiansplat | modelviewer | avatar | earthview   (a demo)
#
# Examples:
#   ./scripts/run_linux_demo.sh cube-hosted
#   ./scripts/run_linux_demo.sh mediaplayer --output=sbs
#   DXR_DEMO_ROOT=~/src ./scripts/run_linux_demo.sh earthview
#
# Demo repos are expected as siblings of this runtime checkout
# (../displayxr-demo-<name>); override the parent dir with $DXR_DEMO_ROOT or a
# full path via --demo-dir=<path-to-demo-repo>.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUILD_DIR="$ROOT/build"
DEMO_ROOT="${DXR_DEMO_ROOT:-$(dirname "$ROOT")}"

OUTPUT="${SIM_DISPLAY_OUTPUT:-anaglyph}"
REBUILD=0
DEMO_DIR_OVERRIDE=""
TARGET=""

for arg in "$@"; do
  case "$arg" in
    --output=*)   OUTPUT="${arg#*=}" ;;
    --rebuild)    REBUILD=1 ;;
    --demo-dir=*) DEMO_DIR_OVERRIDE="${arg#*=}" ;;
    --list)
      echo "targets: cube-hosted  cube-handle  mediaplayer  gaussiansplat  modelviewer  avatar  earthview"
      exit 0 ;;
    -*) echo "unknown flag: $arg" >&2; exit 2 ;;
    *)  TARGET="$arg" ;;
  esac
done

if [ -z "$TARGET" ]; then
  echo "usage: $0 <target> [--output=anaglyph|sbs] [--rebuild] [--demo-dir=PATH] [--list]" >&2
  exit 2
fi

if [ -z "${DISPLAY:-}" ]; then
  echo "WARNING: DISPLAY is unset — the compositor needs an X server (X11 session or XWayland)." >&2
fi

# --- Runtime: build (with test apps) if the dev manifest / plug-in are missing ---
MANIFEST="$BUILD_DIR/openxr_displayxr-dev.json"
PLUGIN_DIR="$BUILD_DIR/_plugins"
if [ "$REBUILD" = "1" ] || [ ! -f "$MANIFEST" ] || [ ! -f "$PLUGIN_DIR/DisplayXR-SimDisplay.so" ]; then
  echo "=== Building runtime + test apps (scripts/build_linux.sh --apps) ==="
  "$ROOT/scripts/build_linux.sh" --apps --no-test
fi
if [ ! -f "$MANIFEST" ]; then
  echo "ERROR: runtime dev manifest not found at $MANIFEST after build." >&2
  exit 1
fi

# Exported so every target's run script picks up THIS runtime build (their scripts
# use := / :- defaults, so a pre-set value wins over their sibling auto-detect).
export XR_RUNTIME_JSON="$MANIFEST"
export XRT_PLUGIN_SEARCH_PATH="$PLUGIN_DIR"
export OXR_ENABLE_VK_NATIVE_COMPOSITOR="${OXR_ENABLE_VK_NATIVE_COMPOSITOR:-1}"
export SIM_DISPLAY_OUTPUT="$OUTPUT"

echo "=== Launching '$TARGET' (SIM_DISPLAY_OUTPUT=$OUTPUT) ==="
echo "    XR_RUNTIME_JSON=$XR_RUNTIME_JSON"
echo "    XRT_PLUGIN_SEARCH_PATH=$XRT_PLUGIN_SEARCH_PATH"

exec_script() {  # exec a run script, erroring clearly if it's missing
  local script="$1"
  if [ ! -f "$script" ]; then
    echo "ERROR: run script not found: $script" >&2; exit 1
  fi
  exec bash "$script"
}

case "$TARGET" in
  # Runtime cube apps — self-contained run scripts generated by build_linux.sh --apps.
  cube-hosted) exec_script "$BUILD_DIR/run_cube_hosted_legacy_vk_linux.sh" ;;
  cube-handle) exec_script "$BUILD_DIR/run_cube_handle_vk_linux.sh" ;;

  # Demos — delegate to the demo's own run_*_linux.sh (handles its loader); our
  # exported XR_RUNTIME_JSON/plug-in path/output override its sibling auto-detect.
  mediaplayer|gaussiansplat|modelviewer|avatar|earthview)
    DEMO_DIR="${DEMO_DIR_OVERRIDE:-$DEMO_ROOT/displayxr-demo-$TARGET}"
    if [ ! -d "$DEMO_DIR" ]; then
      echo "ERROR: demo repo not found at $DEMO_DIR (set \$DXR_DEMO_ROOT or --demo-dir)." >&2
      exit 1
    fi
    # Build the demo if no linux binary is present yet.
    BIN="$(find "$DEMO_DIR/build" -type f -name '*_handle_vk_linux' -perm -u+x 2>/dev/null | head -1 || true)"
    if [ "$REBUILD" = "1" ] || [ -z "$BIN" ]; then
      echo "=== Building $TARGET (scripts/build_linux.sh) ==="
      ( cd "$DEMO_DIR" && ./scripts/build_linux.sh )
    fi
    RUN_SCRIPT="$(find "$DEMO_DIR/scripts" -maxdepth 1 -type f -name 'run_*linux*.sh' 2>/dev/null | head -1 || true)"
    if [ -z "$RUN_SCRIPT" ]; then
      echo "ERROR: no run_*linux*.sh found under $DEMO_DIR/scripts." >&2; exit 1
    fi
    exec_script "$RUN_SCRIPT"
    ;;
  *)
    echo "unknown target '$TARGET' — see --list" >&2; exit 2 ;;
esac
