#!/usr/bin/env python3
# Copyright 2026, The DisplayXR Project
# SPDX-License-Identifier: BSL-1.0
"""Generate the REAL-hardware fixture for the vertical-alignment refinement.

ADR-043 R2. One raw side-by-side GRAY8 frame (1280x480) from a Leia SR laptop's
tracking camera (a ceiling scene, camera 150), recompressed as a JPEG (the PNG
is 297 KB of sensor noise; JPEG q90 keeps the statistics: the signed residual
reads the same +1.7 px), plus the device's calibration as the plug-in hands it
to the runtime (left eye = camera 2 = M2/D2, right = camera 1 = M1/D1,
R' = R^T, T' = -R^T T) and an INDEPENDENT reference: SIFT matches found by
OpenCV on OpenCV's own rectification of the same frame, mapped back to RAW
pixels through OpenCV's maps. tests_stereo_rectify maps them forward through
the runtime's (corrected) rectification and asserts the row residual.

The runtime never depends on OpenCV; run this offline and commit both outputs:

    python3 tests/fixtures/gen_stereo_vrefine_sr_fixture.py <raw_sbs.png> tests/fixtures
"""
import sys

import cv2
import numpy as np

M1 = np.array([[4.7623373282393203e+02, 0, 3.1361746988405270e+02], [0, 4.7573318336977724e+02, 2.4590743710177546e+02], [0, 0, 1]])
D1 = np.array([1.2332390163153338e-01, -1.8065702171496908e-01, -1.7852161465149287e-03, 7.0567885578275071e-04, 8.7485984937824945e-02])
M2 = np.array([[4.7753198103487864e+02, 0, 3.2061581703236254e+02], [0, 4.7719412297375959e+02, 2.2625301107241927e+02], [0, 0, 1]])
D2 = np.array([1.0906040224963771e-01, -1.2479660062568124e-01, -1.1093907046283672e-03, 1.0008674090348705e-03, 2.5815446523384768e-02])
R = np.array([9.9998661420584478e-01, -2.5373925908838452e-03, 4.5092181108025075e-03, 2.5193814304075575e-03, 9.9998884428889723e-01,
              3.9954993384893533e-03, -4.5193059576863282e-03, -3.9840854151836471e-03, 9.9998185130384509e-01]).reshape(3, 3)
T = np.array([1.1996226177065833e+02, -3.9419132551517166e-01, -8.7010595776014110e-01]).reshape(3, 1)


def bilinear(m, x, y):
    x0, y0 = int(np.floor(x)), int(np.floor(y))
    fx, fy = x - x0, y - y0
    return (m[y0, x0] * (1 - fx) * (1 - fy) + m[y0, x0 + 1] * fx * (1 - fy) + m[y0 + 1, x0] * (1 - fx) * fy +
            m[y0 + 1, x0 + 1] * fx * fy)


def main():
    src, outdir = sys.argv[1], sys.argv[2]
    raw = cv2.imread(src, 0)
    cv2.imwrite(outdir + "/stereo_vrefine_sr_raw.jpg", raw, [cv2.IMWRITE_JPEG_QUALITY, 90])
    raw = cv2.imread(outdir + "/stereo_vrefine_sr_raw.jpg", 0)  # what the test sees
    L, Rr = raw[:, :640], raw[:, 640:]
    KL, DL, KR, DR = M2, D2, M1, D1
    Rl2r, Tl2r = R.T, -R.T @ T
    R1, R2, P1, P2, _, _, _ = cv2.stereoRectify(KL, DL, KR, DR, (640, 480), Rl2r, Tl2r, alpha=0,
                                                flags=cv2.CALIB_ZERO_DISPARITY)
    mL = cv2.initUndistortRectifyMap(KL, DL, R1, P1, (640, 480), cv2.CV_32FC1)
    mR = cv2.initUndistortRectifyMap(KR, DR, R2, P2, (640, 480), cv2.CV_32FC1)
    a, b = cv2.remap(L, *mL, cv2.INTER_LINEAR), cv2.remap(Rr, *mR, cv2.INTER_LINEAR)
    sift = cv2.SIFT_create(8000)
    ka, da = sift.detectAndCompute(a, None)
    kb, db = sift.detectAndCompute(b, None)
    good = [x for x, y in cv2.BFMatcher().knnMatch(da, db, k=2) if x.distance < 0.7 * y.distance]
    pa = np.float32([ka[g.queryIdx].pt for g in good])
    pb = np.float32([kb[g.trainIdx].pt for g in good])
    d, dy = pa[:, 0] - pb[:, 0], pb[:, 1] - pa[:, 1]
    ok = (d > 0) & (d < 200) & (np.abs(dy - np.median(dy)) < 5)
    pa, pb, dy = pa[ok], pb[ok], dy[ok]
    rows = []
    for (xa, ya), (xb, yb) in zip(pa, pb):
        if not (1 <= xa < 638 and 1 <= ya < 478 and 1 <= xb < 638 and 1 <= yb < 478):
            continue
        rows.append((bilinear(mL[0], xa, ya), bilinear(mL[1], xa, ya), bilinear(mR[0], xb, yb), bilinear(mR[1], xb, yb)))
    fit = np.linalg.lstsq(np.c_[np.ones(len(dy)), pa[:, 1] - P1[1, 2]], dy, rcond=None)[0]
    with open(outdir + "/stereo_vrefine_sr_fixture.h", "w") as f:
        def p(*x):
            print(*x, file=f)
        p("// Copyright 2026, The DisplayXR Project")
        p("// SPDX-License-Identifier: BSL-1.0")
        p("// GENERATED by gen_stereo_vrefine_sr_fixture.py (OpenCV %s) — do not edit." % cv2.__version__)
        p("// A Leia SR laptop tracking camera: calibration as the plug-in hands it over, and")
        p("// SIFT matches (OpenCV, on OpenCV's rectification) mapped back to RAW pixels.")
        p("#pragma once")
        p("// clang-format off")
        p("")
        p("struct stereo_vrefine_sr_match { double lx, ly, rx, ry; }; // RAW pixels, left / right eye")
        p("")
        p("static const double k_sr_K[2][4] = { // fx fy cx cy; [0] = left = camera 2")
        p("    {%.17g, %.17g, %.17g, %.17g}," % (KL[0, 0], KL[1, 1], KL[0, 2], KL[1, 2]))
        p("    {%.17g, %.17g, %.17g, %.17g}," % (KR[0, 0], KR[1, 1], KR[0, 2], KR[1, 2]))
        p("};")
        p("static const double k_sr_D[2][5] = {")
        p("    {%s}," % ", ".join("%.17g" % v for v in DL))
        p("    {%s}," % ", ".join("%.17g" % v for v in DR))
        p("};")
        p("static const double k_sr_R[3][3] = {%s};" % ", ".join("{%s}" % ", ".join("%.17g" % v for v in r) for r in Rl2r))
        p("static const double k_sr_T[3] = {%s};" % ", ".join("%.17g" % v for v in Tl2r.ravel()))
        p("// OpenCV's rectification of the same frame: signed dy median %+.3f px over %d matches," % (np.median(dy), len(dy)))
        p("// fit dy = %+.3f %+.4f * (y - cy) px." % (fit[0], fit[1]))
        p("static const double k_sr_ocv_median_dy = %.6f;" % np.median(dy))
        p("static const struct stereo_vrefine_sr_match k_sr_matches[] = {")
        for r in rows:
            p("    {%.4f, %.4f, %.4f, %.4f}," % r)
        p("};")
        p("// clang-format on")
    print("matches", len(rows), "median dy", np.median(dy), "fit", fit)


if __name__ == "__main__":
    main()
