// Copyright 2026, Leia Inc.
// SPDX-License-Identifier: BSL-1.0
//
// cube_texture_vk_android entry point. Wires the Khronos OpenXR loader
// (`xrInitializeLoaderKHR` + `xrCreateInstance`) and logs the runtime
// the loader binds to. No Vulkan / session / cube renderer yet — that
// lands in follow-up commits. The point of this step is to prove the
// loader can find our runtime APK via the
// org.khronos.openxr.OpenXRRuntimeService intent.

#include <android/log.h>
#include <android_native_app_glue.h>

#define XR_USE_PLATFORM_ANDROID
#define XR_USE_GRAPHICS_API_VULKAN
// VK_USE_PLATFORM_ANDROID_KHR pulls in vulkan_android.h
// (VkAndroidSurfaceCreateInfoKHR + vkCreateAndroidSurfaceKHR) — the texture
// app creates + presents its OWN swapchain on the Activity's ANativeWindow.
#define VK_USE_PLATFORM_ANDROID_KHR
// openxr_platform.h references VkInstance / VkDevice / VkFormat under
// XR_USE_GRAPHICS_API_VULKAN but does NOT include <vulkan/vulkan.h>
// itself — the consumer must do that first.
#include <vulkan/vulkan.h>
#include <android/native_window.h>
#include <openxr/openxr.h>
#include <openxr/openxr_platform.h>
#include <openxr/XR_EXT_android_surface_binding.h>

#include <atomic>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <jni.h>
#include <sys/system_properties.h>
#include <unistd.h>

// SPIR-V headers generated by the spirv_shaders() CMake helper at build
// time. They expose `shaders_cube_vert` / `shaders_cube_frag` as
// `unsigned int [...]` arrays (host-endian SPIR-V words).
#include "shaders/cube.vert.h"
#include "shaders/cube.frag.h"

#define LOG_TAG "cube_texture_vk_android"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGW(...) __android_log_print(ANDROID_LOG_WARN, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

// Hardware-bring-up verbose debug. Gated on XRT_DEBUG_ANDROID_VERBOSE
// passed from build.gradle's debug variant. Compiled out in release.
// Tag "HW_DBG_APP:" greppable separation from runtime-side HW_DBG_CNSDK
// / HW_DBG_DP logs.
#ifdef XRT_DEBUG_ANDROID_VERBOSE
#define DXR_HW_DBG(...)       __android_log_print(ANDROID_LOG_INFO, LOG_TAG, "HW_DBG_APP: " __VA_ARGS__)
#define DXR_HW_DBG_ONCE(...)  do {                                                                 \
		static bool _logged = false;                                                                \
		if (!_logged) {                                                                             \
			__android_log_print(ANDROID_LOG_INFO, LOG_TAG, "HW_DBG_APP[once]: " __VA_ARGS__);       \
			_logged = true;                                                                         \
		}                                                                                           \
	} while (0)
#else
#define DXR_HW_DBG(...)       ((void)0)
#define DXR_HW_DBG_ONCE(...)  ((void)0)
#endif

namespace {

const char *
xr_result_str(XrResult r)
{
	// Just the codes we expect to see; anything else falls through to a
	// numeric format in the caller.
	switch (r) {
	case XR_SUCCESS:                            return "XR_SUCCESS";
	case XR_ERROR_RUNTIME_FAILURE:              return "XR_ERROR_RUNTIME_FAILURE";
	case XR_ERROR_RUNTIME_UNAVAILABLE:          return "XR_ERROR_RUNTIME_UNAVAILABLE";
	case XR_ERROR_INSTANCE_LOST:                return "XR_ERROR_INSTANCE_LOST";
	case XR_ERROR_INITIALIZATION_FAILED:        return "XR_ERROR_INITIALIZATION_FAILED";
	case XR_ERROR_API_VERSION_UNSUPPORTED:      return "XR_ERROR_API_VERSION_UNSUPPORTED";
	case XR_ERROR_EXTENSION_NOT_PRESENT:        return "XR_ERROR_EXTENSION_NOT_PRESENT";
	case XR_ERROR_API_LAYER_NOT_PRESENT:        return "XR_ERROR_API_LAYER_NOT_PRESENT";
	case XR_ERROR_OUT_OF_MEMORY:                return "XR_ERROR_OUT_OF_MEMORY";
	case XR_ERROR_FUNCTION_UNSUPPORTED:         return "XR_ERROR_FUNCTION_UNSUPPORTED";
	case XR_ERROR_VALIDATION_FAILURE:           return "XR_ERROR_VALIDATION_FAILURE";
	default:                                    return nullptr;
	}
}

void
log_xr_result(const char *what, XrResult r)
{
	const char *name = xr_result_str(r);
	if (name != nullptr) {
		LOGI("%s -> %s", what, name);
	} else {
		LOGI("%s -> XrResult(%d)", what, (int)r);
	}
}

XrInstance g_instance = XR_NULL_HANDLE;
XrSystemId g_system_id = XR_NULL_SYSTEM_ID;
XrVersion g_required_vk_version = XR_MAKE_VERSION(1, 1, 0);

VkInstance g_vk_instance = VK_NULL_HANDLE;
VkPhysicalDevice g_vk_phys_device = VK_NULL_HANDLE;
VkDevice g_vk_device = VK_NULL_HANDLE;
VkQueue g_vk_queue = VK_NULL_HANDLE;
uint32_t g_vk_queue_family = UINT32_MAX;

XrSession g_session = XR_NULL_HANDLE;
XrSessionState g_session_state = XR_SESSION_STATE_UNKNOWN;
bool g_session_running = false;
bool g_exit_requested = false;

// Reference space for the projection layer. STAGE if available, else LOCAL.
XrSpace g_app_space = XR_NULL_HANDLE;

// View configuration + per-view swapchains. Hardcoded to stereo since
// that's the only mode the runtime currently exposes on Android.
constexpr uint32_t kViewCount = 2;

struct PerView
{
	XrSwapchain swapchain{XR_NULL_HANDLE};
	uint32_t width{0};
	uint32_t height{0};
	// Image arrays sized at xrEnumerateSwapchainImages time. We cap at
	// 8 (matches typical OpenXR runtime budgets) and abort if more come
	// back — keeps the test app std-lib-free in case the prefab AAR
	// surprises us.
	XrSwapchainImageVulkanKHR images[8]{};
	VkImageView image_views[8]{};
	VkFramebuffer framebuffers[8]{};
	uint32_t image_count{0};
	// Shared depth target for this view (rendering is serialized per view
	// via vkQueueWaitIdle, so one depth image per view is sufficient).
	VkImage depth_image{VK_NULL_HANDLE};
	VkDeviceMemory depth_mem{VK_NULL_HANDLE};
	VkImageView depth_view{VK_NULL_HANDLE};
};
PerView g_views[kViewCount];

// ─── on-device UI / eye-tracking readout state ────────────────────────────
// g_bg_enabled: background color on/off. Default OFF → black clear in both
//   eyes, so the weave/3D is judged against a clean black field. Toggled
//   on-device by TAPPING the screen (handle_input) and also exposed to the
//   Kotlin side via JNI (nativeSetBackgroundEnabled).
// g_eye_*: latest tracked head-center position (meters, display-relative),
//   stored each frame from the located view poses. Drives the on-screen
//   eye-position marker and is read by the Kotlin overlay (nativeGetEye).
std::atomic<bool> g_bg_enabled{false};
std::atomic<float> g_eye_x{0.0f};
std::atomic<float> g_eye_y{0.0f};
std::atomic<float> g_eye_z{0.0f};

VkFormat g_swapchain_format = VK_FORMAT_UNDEFINED;
VkCommandPool g_app_cmd_pool = VK_NULL_HANDLE;

// ─── texture-class state (app-owns-presentation) ──────────────────────────
// The android_app, stashed in android_main so the bring-up helpers can reach
// app->window for the shared image + present surface.
struct android_app *g_app = nullptr;

// Shared weave-target VkImage. The app creates it and hands it to the runtime
// via XrAndroidSurfaceBindingCreateInfoEXT; the runtime weaves the stereo
// content into its canvas sub-rect (xrSetSharedTextureOutputRectEXT) and does
// NOT present. Format must match what the DP writes (B8G8R8A8_UNORM, see
// comp_vk_native_compositor.c). usage: color attachment (DP weave target) +
// transfer-src (our present blit).
constexpr VkFormat kSharedFormat = VK_FORMAT_B8G8R8A8_UNORM;
VkImage g_shared_image = VK_NULL_HANDLE;
VkDeviceMemory g_shared_mem = VK_NULL_HANDLE;
uint32_t g_shared_w = 0, g_shared_h = 0;

// Canvas sub-rect within the shared image where the runtime weaves 3D. The
// region OUTSIDE it is the app-owned 2D surround. Inset as a fraction of the
// panel on each side — 0.0 = full-panel canvas (no surround). Default demos
// the texture class with a visible surround border. The runtime is told this
// via xrSetSharedTextureOutputRectEXT.
constexpr float kCanvasInsetFrac = 0.12f;
int32_t g_canvas_x = 0, g_canvas_y = 0;
uint32_t g_canvas_w = 0, g_canvas_h = 0;

// App-owned present swapchain on app->window (the runtime presents nothing in
// texture mode).
VkSurfaceKHR g_present_surface = VK_NULL_HANDLE;
VkSwapchainKHR g_present_swapchain = VK_NULL_HANDLE;
VkFormat g_present_format = VK_FORMAT_UNDEFINED;
uint32_t g_present_w = 0, g_present_h = 0;
VkImage g_present_images[8] = {};
uint32_t g_present_image_count = 0;
VkSemaphore g_present_acquire_sem = VK_NULL_HANDLE;  // signalled by acquire
VkSemaphore g_present_blit_sem = VK_NULL_HANDLE;     // signalled by blit, waited by present
bool g_present_ready = false;

PFN_xrSetSharedTextureOutputRectEXT g_set_output_rect = nullptr;

// Graphics pipeline state for the triangle renderer.
VkRenderPass g_render_pass = VK_NULL_HANDLE;
VkPipelineLayout g_pipeline_layout = VK_NULL_HANDLE;
VkPipeline g_pipeline = VK_NULL_HANDLE;
VkShaderModule g_vs_module = VK_NULL_HANDLE;
VkShaderModule g_fs_module = VK_NULL_HANDLE;

// Cube geometry in a vertex buffer (position + per-face color). Baking it in
// the shader tripped Adreno's pipeline linker, so it lives in real GPU memory.
VkBuffer g_cube_vbuf = VK_NULL_HANDLE;
VkDeviceMemory g_cube_vbuf_mem = VK_NULL_HANDLE;
struct CubeVertex { float pos[3]; float color[3]; };
constexpr uint32_t kCubeVertexCount = 36;

// In-frame HUD: a persistently-mapped host-visible vertex buffer of CubeVertex
// quads, rebuilt each frame and drawn with an identity MVP (screen-space NDC).
// Android widgets can't overlay the runtime's display window, so the HUD lives
// inside the rendered frame.
VkBuffer g_hud_vbuf = VK_NULL_HANDLE;
VkDeviceMemory g_hud_vbuf_mem = VK_NULL_HANDLE;
void *g_hud_mapped = nullptr;
constexpr uint32_t kHudMaxVerts = 8192;

// Authoritative 4-way display rotation, pushed from MainActivity (Surface
// rotation: 0/1/2/3 = ROTATION_0/90/180/270). Configuration.orientation only
// distinguishes portrait/landscape, so it can't tell the two portraits (0 vs
// 180) apart — that ambiguity made the HUD rotation jump between builds. The
// framebuffer rotates with the device, so the HUD is counter-rotated by this
// to stay upright in every orientation.
std::atomic<int> g_display_rotation{0};

// Set when xrCreateInstance fails with RUNTIME_UNAVAILABLE (the DisplayXR
// runtime isn't reachable — usually because it's in Android's "stopped" state
// and this device's OEM blocks waking it). MainActivity polls this to show the
// user a "launch DisplayXR first" message.
std::atomic<bool> g_runtime_unavailable{false};

// Frame counter for throttled logging — log heartbeat every 60 frames.
uint64_t g_frame_count = 0;

// Wire the Khronos OpenXR loader's Android-specific init. Required on
// Android because the loader needs the JavaVM + Activity context to
// discover the runtime APK via the OpenXRRuntimeService intent.
bool
initialize_loader(struct android_app *app)
{
	PFN_xrInitializeLoaderKHR xrInitializeLoaderKHR = nullptr;
	XrResult res = xrGetInstanceProcAddr(
	    XR_NULL_HANDLE, "xrInitializeLoaderKHR",
	    reinterpret_cast<PFN_xrVoidFunction *>(&xrInitializeLoaderKHR));
	if (res != XR_SUCCESS || xrInitializeLoaderKHR == nullptr) {
		LOGE("xrGetInstanceProcAddr(xrInitializeLoaderKHR) failed (%d)", (int)res);
		return false;
	}

	XrLoaderInitInfoAndroidKHR loader_init = {};
	loader_init.type = XR_TYPE_LOADER_INIT_INFO_ANDROID_KHR;
	loader_init.applicationVM = app->activity->vm;
	loader_init.applicationContext = app->activity->clazz;
	res = xrInitializeLoaderKHR(
	    reinterpret_cast<const XrLoaderInitInfoBaseHeaderKHR *>(&loader_init));
	log_xr_result("xrInitializeLoaderKHR", res);
	return res == XR_SUCCESS;
}

bool
create_instance(struct android_app *app)
{
	// Reset per attempt so the flag reflects THIS attempt's result, not a
	// stale failure from a previous launch (which made the dialog re-appear
	// after the runtime was already started).
	g_runtime_unavailable.store(false, std::memory_order_relaxed);

	const char *extensions[] = {
	    XR_KHR_ANDROID_CREATE_INSTANCE_EXTENSION_NAME,
	    // _enable2 lets the runtime help create our VkInstance/VkDevice
	    // (next step, B13c) and is the modern replacement for _enable.
	    // The graphics-requirements query in this commit needs only this
	    // extension to be enabled.
	    XR_KHR_VULKAN_ENABLE2_EXTENSION_NAME,
	};

	XrInstanceCreateInfoAndroidKHR android_info = {};
	android_info.type = XR_TYPE_INSTANCE_CREATE_INFO_ANDROID_KHR;
	android_info.applicationVM = app->activity->vm;
	android_info.applicationActivity = app->activity->clazz;

	XrInstanceCreateInfo create_info = {};
	create_info.type = XR_TYPE_INSTANCE_CREATE_INFO;
	create_info.next = &android_info;
	std::strncpy(create_info.applicationInfo.applicationName,
	             "cube_texture_vk_android",
	             XR_MAX_APPLICATION_NAME_SIZE - 1);
	create_info.applicationInfo.applicationVersion = 1;
	std::strncpy(create_info.applicationInfo.engineName, "displayxr",
	             XR_MAX_ENGINE_NAME_SIZE - 1);
	create_info.applicationInfo.engineVersion = 1;
	create_info.applicationInfo.apiVersion = XR_CURRENT_API_VERSION;
	create_info.enabledExtensionCount =
	    sizeof(extensions) / sizeof(extensions[0]);
	create_info.enabledExtensionNames = extensions;

	// Retry on RUNTIME_UNAVAILABLE: on a cold launch the DisplayXR runtime may
	// still be waking from Android's "stopped" state (MainActivity kicks it via
	// FLAG_INCLUDE_STOPPED_PACKAGES). A few hundred ms lets the broker become
	// discoverable on cooperative devices. NOTE: on aggressive OEMs (e.g. the
	// nubia NP02J / ZTE DefendManager+AutoLaunch) the app-initiated wake is
	// BLOCKED ("RelatedStart BlockResult = true") and these retries can't help —
	// there the user must launch the DisplayXR app once, or enable auto-launch
	// for it in device settings.
	XrResult res = XR_ERROR_RUNTIME_UNAVAILABLE;
	for (int attempt = 0; attempt < 5; ++attempt) {
		res = xrCreateInstance(&create_info, &g_instance);
		if (res != XR_ERROR_RUNTIME_UNAVAILABLE) {
			break;
		}
		LOGW("xrCreateInstance: runtime unavailable (attempt %d/5); waiting for "
		     "the DisplayXR runtime broker (launch the DisplayXR app once if this "
		     "persists — OEM auto-start may be blocking it)…",
		     attempt + 1);
		usleep(400 * 1000);  // 400 ms
	}
	log_xr_result("xrCreateInstance", res);
	if (res != XR_SUCCESS) {
		if (res == XR_ERROR_RUNTIME_UNAVAILABLE) {
			g_runtime_unavailable.store(true, std::memory_order_relaxed);
		}
		return false;
	}

	/* Stable sentinel for CI emulator smoke test (build-android.yml).
	 * Tag intentionally distinctive so a single grep over logcat
	 * confirms the full broker → runtime → plug-in chain reached
	 * xrCreateInstance success. Do NOT rename without updating the
	 * CI workflow. */
	LOGI("ANDROID_POC_SENTINEL xrCreateInstance=XR_SUCCESS");

	XrInstanceProperties props = {};
	props.type = XR_TYPE_INSTANCE_PROPERTIES;
	res = xrGetInstanceProperties(g_instance, &props);
	if (res == XR_SUCCESS) {
		LOGI("Runtime: \"%s\" v%u.%u.%u",
		     props.runtimeName,
		     XR_VERSION_MAJOR(props.runtimeVersion),
		     XR_VERSION_MINOR(props.runtimeVersion),
		     XR_VERSION_PATCH(props.runtimeVersion));
	} else {
		LOGW("xrGetInstanceProperties failed (%d)", (int)res);
	}
	return true;
}

// Query the runtime's XrSystemId for a Vulkan handheld/HMD form factor
// and ask what Vulkan API version the runtime needs. Logs everything to
// logcat — this is the last step we can do without actually creating a
// VkInstance. B13c picks up here and uses these values to create one.
bool
query_system_and_graphics_reqs()
{
	if (g_instance == XR_NULL_HANDLE) {
		return false;
	}

	// Try HMD first (runtime default — see u_system.c), then fall back
	// to handheld for tablet-style displays.
	XrSystemGetInfo sys_info = {};
	sys_info.type = XR_TYPE_SYSTEM_GET_INFO;
	sys_info.formFactor = XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY;
	XrResult res = xrGetSystem(g_instance, &sys_info, &g_system_id);
	log_xr_result("xrGetSystem(HEAD_MOUNTED_DISPLAY)", res);
	if (res != XR_SUCCESS) {
		sys_info.formFactor = XR_FORM_FACTOR_HANDHELD_DISPLAY;
		res = xrGetSystem(g_instance, &sys_info, &g_system_id);
		log_xr_result("xrGetSystem(HANDHELD_DISPLAY)", res);
		if (res != XR_SUCCESS) {
			return false;
		}
	}

	XrSystemProperties sys_props = {};
	sys_props.type = XR_TYPE_SYSTEM_PROPERTIES;
	res = xrGetSystemProperties(g_instance, g_system_id, &sys_props);
	if (res == XR_SUCCESS) {
		LOGI("System: \"%s\" vendor=0x%08x maxSwapchain=%ux%u maxLayers=%u",
		     sys_props.systemName, sys_props.vendorId,
		     sys_props.graphicsProperties.maxSwapchainImageWidth,
		     sys_props.graphicsProperties.maxSwapchainImageHeight,
		     sys_props.graphicsProperties.maxLayerCount);
	} else {
		LOGW("xrGetSystemProperties failed (%d)", (int)res);
	}

	// Resolve the extension entry point — it lives in libopenxr_loader.so
	// but the loader exposes it only after the corresponding extension
	// is enabled on the instance (which we did in create_instance).
	PFN_xrGetVulkanGraphicsRequirements2KHR get_reqs = nullptr;
	res = xrGetInstanceProcAddr(
	    g_instance, "xrGetVulkanGraphicsRequirements2KHR",
	    reinterpret_cast<PFN_xrVoidFunction *>(&get_reqs));
	if (res != XR_SUCCESS || get_reqs == nullptr) {
		LOGE("xrGetInstanceProcAddr(xrGetVulkanGraphicsRequirements2KHR) failed (%d)",
		     (int)res);
		return false;
	}

	XrGraphicsRequirementsVulkanKHR reqs = {};
	reqs.type = XR_TYPE_GRAPHICS_REQUIREMENTS_VULKAN_KHR;
	res = get_reqs(g_instance, g_system_id, &reqs);
	log_xr_result("xrGetVulkanGraphicsRequirements2KHR", res);
	if (res != XR_SUCCESS) {
		return false;
	}

	LOGI("Vulkan API: min=%u.%u.%u max=%u.%u.%u",
	     XR_VERSION_MAJOR(reqs.minApiVersionSupported),
	     XR_VERSION_MINOR(reqs.minApiVersionSupported),
	     XR_VERSION_PATCH(reqs.minApiVersionSupported),
	     XR_VERSION_MAJOR(reqs.maxApiVersionSupported),
	     XR_VERSION_MINOR(reqs.maxApiVersionSupported),
	     XR_VERSION_PATCH(reqs.maxApiVersionSupported));

	// Save the runtime's minimum for VkApplicationInfo::apiVersion. Going
	// higher is also allowed (up to max), but min is the safest choice
	// that the runtime promises to accept.
	g_required_vk_version = reqs.minApiVersionSupported;
	return true;
}

// Create a VkInstance via the runtime's xrCreateVulkanInstanceKHR — that
// path lets the runtime inject any platform-specific extensions it needs
// (e.g. swapchain-image-import KHRs) on top of our base
// VkInstanceCreateInfo. No app-side extensions needed at this stage.
bool
create_vulkan_instance()
{
	PFN_xrCreateVulkanInstanceKHR xr_create_vk_instance = nullptr;
	XrResult res = xrGetInstanceProcAddr(
	    g_instance, "xrCreateVulkanInstanceKHR",
	    reinterpret_cast<PFN_xrVoidFunction *>(&xr_create_vk_instance));
	if (res != XR_SUCCESS || xr_create_vk_instance == nullptr) {
		LOGE("xrGetInstanceProcAddr(xrCreateVulkanInstanceKHR) failed (%d)", (int)res);
		return false;
	}

	VkApplicationInfo app_info = {};
	app_info.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
	app_info.pApplicationName = "cube_texture_vk_android";
	app_info.applicationVersion = 1;
	app_info.pEngineName = "displayxr";
	app_info.engineVersion = 1;
	app_info.apiVersion = VK_MAKE_VERSION(
	    XR_VERSION_MAJOR(g_required_vk_version),
	    XR_VERSION_MINOR(g_required_vk_version),
	    0);

	VkInstanceCreateInfo vk_ci = {};
	vk_ci.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
	vk_ci.pApplicationInfo = &app_info;

	XrVulkanInstanceCreateInfoKHR xr_ci = {};
	xr_ci.type = XR_TYPE_VULKAN_INSTANCE_CREATE_INFO_KHR;
	xr_ci.systemId = g_system_id;
	xr_ci.pfnGetInstanceProcAddr = &vkGetInstanceProcAddr;
	xr_ci.vulkanCreateInfo = &vk_ci;
	xr_ci.vulkanAllocator = nullptr;

	VkResult vk_result = VK_SUCCESS;
	res = xr_create_vk_instance(g_instance, &xr_ci, &g_vk_instance, &vk_result);
	log_xr_result("xrCreateVulkanInstanceKHR", res);
	if (res != XR_SUCCESS || vk_result != VK_SUCCESS) {
		LOGE("xrCreateVulkanInstanceKHR vk_result=%d", (int)vk_result);
		return false;
	}
	return true;
}

// Ask the runtime which physical device backs our XrSystemId. On Android
// this is typically the one and only GPU, but the API surface is the
// same on multi-GPU desktop platforms.
bool
pick_physical_device()
{
	PFN_xrGetVulkanGraphicsDevice2KHR xr_get_phys = nullptr;
	XrResult res = xrGetInstanceProcAddr(
	    g_instance, "xrGetVulkanGraphicsDevice2KHR",
	    reinterpret_cast<PFN_xrVoidFunction *>(&xr_get_phys));
	if (res != XR_SUCCESS || xr_get_phys == nullptr) {
		LOGE("xrGetInstanceProcAddr(xrGetVulkanGraphicsDevice2KHR) failed (%d)", (int)res);
		return false;
	}

	XrVulkanGraphicsDeviceGetInfoKHR info = {};
	info.type = XR_TYPE_VULKAN_GRAPHICS_DEVICE_GET_INFO_KHR;
	info.systemId = g_system_id;
	info.vulkanInstance = g_vk_instance;

	res = xr_get_phys(g_instance, &info, &g_vk_phys_device);
	log_xr_result("xrGetVulkanGraphicsDevice2KHR", res);
	return res == XR_SUCCESS;
}

// Create a VkDevice via xrCreateVulkanDeviceKHR — same pattern as the
// instance, the runtime injects whatever device extensions it needs on
// top of our base info. We supply one graphics queue.
bool
create_vulkan_device()
{
	// Find a queue family with graphics support. On Android there's
	// usually exactly one, but the proper enumeration is cheap.
	uint32_t qf_count = 0;
	vkGetPhysicalDeviceQueueFamilyProperties(g_vk_phys_device, &qf_count, nullptr);
	if (qf_count == 0) {
		LOGE("No Vulkan queue families");
		return false;
	}
	VkQueueFamilyProperties qf_props[16] = {};
	const uint32_t qf_cap = sizeof(qf_props) / sizeof(qf_props[0]);
	if (qf_count > qf_cap) {
		qf_count = qf_cap;
	}
	vkGetPhysicalDeviceQueueFamilyProperties(g_vk_phys_device, &qf_count, qf_props);

	g_vk_queue_family = UINT32_MAX;
	for (uint32_t i = 0; i < qf_count; ++i) {
		if (qf_props[i].queueFlags & VK_QUEUE_GRAPHICS_BIT) {
			g_vk_queue_family = i;
			break;
		}
	}
	if (g_vk_queue_family == UINT32_MAX) {
		LOGE("No graphics-capable Vulkan queue family");
		return false;
	}

	const float priority = 1.0f;
	VkDeviceQueueCreateInfo qci = {};
	qci.sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
	qci.queueFamilyIndex = g_vk_queue_family;
	qci.queueCount = 1;
	qci.pQueuePriorities = &priority;

	VkPhysicalDeviceFeatures features = {};

	VkDeviceCreateInfo dci = {};
	dci.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
	dci.queueCreateInfoCount = 1;
	dci.pQueueCreateInfos = &qci;
	dci.pEnabledFeatures = &features;

	PFN_xrCreateVulkanDeviceKHR xr_create_vk_device = nullptr;
	XrResult res = xrGetInstanceProcAddr(
	    g_instance, "xrCreateVulkanDeviceKHR",
	    reinterpret_cast<PFN_xrVoidFunction *>(&xr_create_vk_device));
	if (res != XR_SUCCESS || xr_create_vk_device == nullptr) {
		LOGE("xrGetInstanceProcAddr(xrCreateVulkanDeviceKHR) failed (%d)", (int)res);
		return false;
	}

	XrVulkanDeviceCreateInfoKHR xr_ci = {};
	xr_ci.type = XR_TYPE_VULKAN_DEVICE_CREATE_INFO_KHR;
	xr_ci.systemId = g_system_id;
	xr_ci.pfnGetInstanceProcAddr = &vkGetInstanceProcAddr;
	xr_ci.vulkanPhysicalDevice = g_vk_phys_device;
	xr_ci.vulkanCreateInfo = &dci;
	xr_ci.vulkanAllocator = nullptr;

	VkResult vk_result = VK_SUCCESS;
	res = xr_create_vk_device(g_instance, &xr_ci, &g_vk_device, &vk_result);
	log_xr_result("xrCreateVulkanDeviceKHR", res);
	if (res != XR_SUCCESS || vk_result != VK_SUCCESS) {
		LOGE("xrCreateVulkanDeviceKHR vk_result=%d", (int)vk_result);
		return false;
	}

	vkGetDeviceQueue(g_vk_device, g_vk_queue_family, 0, &g_vk_queue);
	LOGI("Vulkan device ready: queue_family=%u queue=%p", g_vk_queue_family, g_vk_queue);
	return true;
}

bool
create_session()
{
	// XR_KHR_vulkan_enable2 reuses XrGraphicsBindingVulkanKHR — there's
	// no `2` suffix on the binding struct, only on the create/get fns.
	XrGraphicsBindingVulkanKHR binding = {};
	binding.type = XR_TYPE_GRAPHICS_BINDING_VULKAN_KHR;
	binding.instance = g_vk_instance;
	binding.physicalDevice = g_vk_phys_device;
	binding.device = g_vk_device;
	binding.queueFamilyIndex = g_vk_queue_family;
	binding.queueIndex = 0;

	// Texture class: hand the runtime our shared VkImage as the weave target so
	// it weaves 3D into the canvas sub-rect and presents nothing — the app owns
	// presentation (present_frame). window=NULL: we keep our own surface.
	XrAndroidSurfaceBindingCreateInfoEXT android_binding = {};
	android_binding.type = XR_TYPE_ANDROID_SURFACE_BINDING_CREATE_INFO_EXT;
	android_binding.window = nullptr;
	android_binding.sharedImage = (uint64_t)(uintptr_t)g_shared_image;
	android_binding.sharedImageWidth = g_shared_w;
	android_binding.sharedImageHeight = g_shared_h;
	android_binding.sharedImageFormat = (uint32_t)kSharedFormat;
	binding.next = &android_binding;

	XrSessionCreateInfo ci = {};
	ci.type = XR_TYPE_SESSION_CREATE_INFO;
	ci.next = &binding;
	ci.systemId = g_system_id;

	XrResult res = xrCreateSession(g_instance, &ci, &g_session);
	log_xr_result("xrCreateSession", res);
	if (res != XR_SUCCESS) {
		return false;
	}

	// Tell the runtime the canvas sub-rect within the shared image where 3D
	// should be woven (the surround region we 2D-fill ourselves).
	res = xrGetInstanceProcAddr(g_instance, "xrSetSharedTextureOutputRectEXT",
	                            reinterpret_cast<PFN_xrVoidFunction *>(&g_set_output_rect));
	if (res == XR_SUCCESS && g_set_output_rect != nullptr) {
		XrResult rr = g_set_output_rect(g_session, g_canvas_x, g_canvas_y, g_canvas_w, g_canvas_h);
		log_xr_result("xrSetSharedTextureOutputRectEXT", rr);
	} else {
		LOGW("xrSetSharedTextureOutputRectEXT unavailable (%d) — canvas = full image", (int)res);
	}
	return true;
}

// Enumerate the runtime's view configuration for PRIMARY_STEREO and
// create one swapchain per view using a runtime-supported color format.
// xrEndFrame will reference these swapchains via the projection layer.
bool
create_swapchains()
{
	uint32_t expected_view_count = 0;
	XrResult res = xrEnumerateViewConfigurationViews(
	    g_instance, g_system_id, XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO,
	    0, &expected_view_count, nullptr);
	log_xr_result("xrEnumerateViewConfigurationViews(count)", res);
	if (res != XR_SUCCESS || expected_view_count != kViewCount) {
		LOGE("Expected %u views, runtime reports %u", kViewCount, expected_view_count);
		return false;
	}

	XrViewConfigurationView view_configs[kViewCount] = {};
	for (uint32_t i = 0; i < kViewCount; ++i) {
		view_configs[i].type = XR_TYPE_VIEW_CONFIGURATION_VIEW;
	}
	res = xrEnumerateViewConfigurationViews(
	    g_instance, g_system_id, XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO,
	    kViewCount, &expected_view_count, view_configs);
	if (res != XR_SUCCESS) {
		log_xr_result("xrEnumerateViewConfigurationViews(fill)", res);
		return false;
	}

	// Pick a swapchain format the runtime supports. Prefer 8-bit linear
	// RGBA / BGRA — these line up with what the runtime's vk_native
	// compositor and the CNSDK DP expect. SRGB variants kicked out so we
	// don't trip the gamma double-correction we just fixed in audit B2.
	uint32_t format_count = 0;
	res = xrEnumerateSwapchainFormats(g_session, 0, &format_count, nullptr);
	if (res != XR_SUCCESS || format_count == 0) {
		log_xr_result("xrEnumerateSwapchainFormats(count)", res);
		return false;
	}
	int64_t formats[64] = {};
	if (format_count > 64) {
		format_count = 64;
	}
	res = xrEnumerateSwapchainFormats(g_session, format_count, &format_count, formats);
	if (res != XR_SUCCESS) {
		log_xr_result("xrEnumerateSwapchainFormats(fill)", res);
		return false;
	}
	const int64_t preferred[] = {
	    VK_FORMAT_B8G8R8A8_UNORM,
	    VK_FORMAT_R8G8B8A8_UNORM,
	};
	for (int64_t pref : preferred) {
		for (uint32_t i = 0; i < format_count && g_swapchain_format == VK_FORMAT_UNDEFINED; ++i) {
			if (formats[i] == pref) {
				g_swapchain_format = (VkFormat)pref;
			}
		}
		if (g_swapchain_format != VK_FORMAT_UNDEFINED) {
			break;
		}
	}
	if (g_swapchain_format == VK_FORMAT_UNDEFINED) {
		LOGE("Runtime didn't advertise a UNORM swapchain format; first supported = 0x%llx",
		     (long long)formats[0]);
		g_swapchain_format = (VkFormat)formats[0];
	}
	LOGI("Chose swapchain format: 0x%x", (uint32_t)g_swapchain_format);

	for (uint32_t i = 0; i < kViewCount; ++i) {
		g_views[i].width = view_configs[i].recommendedImageRectWidth;
		g_views[i].height = view_configs[i].recommendedImageRectHeight;

		XrSwapchainCreateInfo ci = {};
		ci.type = XR_TYPE_SWAPCHAIN_CREATE_INFO;
		ci.usageFlags = XR_SWAPCHAIN_USAGE_COLOR_ATTACHMENT_BIT |
		                XR_SWAPCHAIN_USAGE_TRANSFER_DST_BIT;
		ci.format = g_swapchain_format;
		ci.sampleCount = view_configs[i].recommendedSwapchainSampleCount;
		ci.width = g_views[i].width;
		ci.height = g_views[i].height;
		ci.faceCount = 1;
		ci.arraySize = 1;
		ci.mipCount = 1;

		res = xrCreateSwapchain(g_session, &ci, &g_views[i].swapchain);
		if (res != XR_SUCCESS) {
			log_xr_result("xrCreateSwapchain", res);
			return false;
		}

		uint32_t img_count = 0;
		res = xrEnumerateSwapchainImages(g_views[i].swapchain, 0, &img_count, nullptr);
		if (res != XR_SUCCESS) {
			log_xr_result("xrEnumerateSwapchainImages(count)", res);
			return false;
		}
		if (img_count > 8) {
			LOGW("Swapchain advertises %u images; capping at 8", img_count);
			img_count = 8;
		}
		for (uint32_t j = 0; j < img_count; ++j) {
			g_views[i].images[j].type = XR_TYPE_SWAPCHAIN_IMAGE_VULKAN_KHR;
		}
		res = xrEnumerateSwapchainImages(
		    g_views[i].swapchain, img_count, &img_count,
		    reinterpret_cast<XrSwapchainImageBaseHeader *>(g_views[i].images));
		if (res != XR_SUCCESS) {
			log_xr_result("xrEnumerateSwapchainImages(fill)", res);
			return false;
		}
		g_views[i].image_count = img_count;
		LOGI("View %u swapchain: %ux%u, %u images", i, g_views[i].width,
		     g_views[i].height, img_count);
	}
	return true;
}

// One reference space for the app — projection layer poses are expressed
// relative to this. STAGE if the runtime supports it, else LOCAL.
bool
create_reference_space()
{
	XrReferenceSpaceCreateInfo ci = {};
	ci.type = XR_TYPE_REFERENCE_SPACE_CREATE_INFO;
	ci.referenceSpaceType = XR_REFERENCE_SPACE_TYPE_LOCAL;
	ci.poseInReferenceSpace.orientation = {0, 0, 0, 1};
	ci.poseInReferenceSpace.position = {0, 0, 0};
	XrResult res = xrCreateReferenceSpace(g_session, &ci, &g_app_space);
	log_xr_result("xrCreateReferenceSpace(LOCAL)", res);
	return res == XR_SUCCESS;
}

// Standalone command pool for the test app's per-frame cmd buffers.
// Created lazily once the session + swapchains exist.
bool
create_cmd_pool()
{
	VkCommandPoolCreateInfo ci = {};
	ci.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
	ci.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
	ci.queueFamilyIndex = g_vk_queue_family;
	VkResult res = vkCreateCommandPool(g_vk_device, &ci, nullptr, &g_app_cmd_pool);
	if (res != VK_SUCCESS) {
		LOGE("vkCreateCommandPool failed: %d", res);
		return false;
	}
	return true;
}

void
destroy_swapchains()
{
	for (uint32_t i = 0; i < kViewCount; ++i) {
		if (g_views[i].swapchain != XR_NULL_HANDLE) {
			xrDestroySwapchain(g_views[i].swapchain);
			g_views[i].swapchain = XR_NULL_HANDLE;
		}
		g_views[i].image_count = 0;
		g_views[i].width = 0;
		g_views[i].height = 0;
	}
	g_swapchain_format = VK_FORMAT_UNDEFINED;
}

void
destroy_reference_space()
{
	if (g_app_space != XR_NULL_HANDLE) {
		xrDestroySpace(g_app_space);
		g_app_space = XR_NULL_HANDLE;
	}
}

void
destroy_cmd_pool()
{
	if (g_app_cmd_pool != VK_NULL_HANDLE && g_vk_device != VK_NULL_HANDLE) {
		vkDestroyCommandPool(g_vk_device, g_app_cmd_pool, nullptr);
		g_app_cmd_pool = VK_NULL_HANDLE;
	}
}

// Record + submit a clear-to-color cmd buffer on the swapchain image
// for view `view_idx` at swapchain index `image_idx`. Distinct colors
// per view so a one-eye-covered hardware test can verify left/right
// (see displayxr-leia-plugin docs/cnsdk-android-calibration.md § "Tile-to-eye
// mapping"). Layout-aware: arrives from xrAcquireSwapchainImage in
// ─── matrix helpers ──────────────────────────────────────────────────
//
// Column-major 4x4 matrix so push constants land in GLSL "mat4" layout
// without per-element transposition.

struct Mat4 { float m[16]; };

inline Mat4
mat4_identity()
{
	Mat4 r{};
	r.m[0] = r.m[5] = r.m[10] = r.m[15] = 1.0f;
	return r;
}

inline Mat4
mat4_mul(const Mat4 &a, const Mat4 &b)
{
	Mat4 r{};
	for (int col = 0; col < 4; ++col) {
		for (int row = 0; row < 4; ++row) {
			float s = 0.0f;
			for (int k = 0; k < 4; ++k) {
				s += a.m[k * 4 + row] * b.m[col * 4 + k];
			}
			r.m[col * 4 + row] = s;
		}
	}
	return r;
}

// Build the view matrix that transforms world-space points into the
// eye's local frame. OpenXR's XrPosef is world-from-eye, so the view
// matrix is inverse(world-from-eye). For a rigid transform that's
// transpose(R) + (-transpose(R) * t).
Mat4
view_matrix_from_pose(const XrPosef &pose)
{
	const float x = pose.orientation.x, y = pose.orientation.y;
	const float z = pose.orientation.z, w = pose.orientation.w;
	const float xx = x * x, yy = y * y, zz = z * z;
	const float xy = x * y, xz = x * z, yz = y * z;
	const float wx = w * x, wy = w * y, wz = w * z;

	// R is world-from-eye rotation. View matrix uses R^T.
	const float r00 = 1.0f - 2.0f * (yy + zz);
	const float r01 = 2.0f * (xy + wz);
	const float r02 = 2.0f * (xz - wy);
	const float r10 = 2.0f * (xy - wz);
	const float r11 = 1.0f - 2.0f * (xx + zz);
	const float r12 = 2.0f * (yz + wx);
	const float r20 = 2.0f * (xz + wy);
	const float r21 = 2.0f * (yz - wx);
	const float r22 = 1.0f - 2.0f * (xx + yy);

	// Translation in eye-space: -R^T * t
	const float tx = -(r00 * pose.position.x + r01 * pose.position.y + r02 * pose.position.z);
	const float ty = -(r10 * pose.position.x + r11 * pose.position.y + r12 * pose.position.z);
	const float tz = -(r20 * pose.position.x + r21 * pose.position.y + r22 * pose.position.z);

	// Column-major: col c, row r → m[c*4+r]
	Mat4 v{};
	v.m[0]  = r00; v.m[1]  = r10; v.m[2]  = r20; v.m[3]  = 0.0f;
	v.m[4]  = r01; v.m[5]  = r11; v.m[6]  = r21; v.m[7]  = 0.0f;
	v.m[8]  = r02; v.m[9]  = r12; v.m[10] = r22; v.m[11] = 0.0f;
	v.m[12] = tx;  v.m[13] = ty;  v.m[14] = tz;  v.m[15] = 1.0f;
	return v;
}

// Build an asymmetric perspective projection from OpenXR FOV (radians,
// signed: angleLeft < 0, angleRight > 0). Vulkan clip space: x ∈ [-1,1],
// y ∈ [-1,1] points DOWN, z ∈ [0,1], depth grows away from camera (we
// look along -Z in eye space). near < far, both positive.
Mat4
projection_matrix_from_fov(const XrFovf &fov, float aspect_w_over_h, float near_z, float far_z)
{
	const float tan_l = std::tan(fov.angleLeft);
	const float tan_r = std::tan(fov.angleRight);
	const float tan_d = std::tan(fov.angleDown);
	const float tan_u = std::tan(fov.angleUp);
	const float tan_w = tan_r - tan_l;
	const float tan_h = tan_u - tan_d;

	Mat4 p{};
	p.m[0]  = 2.0f / tan_w;
	p.m[5]  = 2.0f / tan_h;
	p.m[8]  = (tan_r + tan_l) / tan_w;
	p.m[9]  = (tan_u + tan_d) / tan_h;
	p.m[10] = -far_z / (far_z - near_z);
	p.m[11] = -1.0f;
	p.m[14] = -(far_z * near_z) / (far_z - near_z);

	// Aspect correction: the runtime reports a (near-)square per-eye FOV,
	// but each eye image is 16:10 (2560x1600), so an uncorrected projection
	// stretches geometry horizontally. Derive the horizontal scale from the
	// vertical one and the real viewport aspect, keeping the vertical FOV.
	// Applied identically to both eyes, so the stereo (IPD in the view
	// matrix) is preserved — only the per-eye shape is un-stretched.
	if (aspect_w_over_h > 0.0f) {
		p.m[0] = (2.0f / tan_h) / aspect_w_over_h;
		p.m[8] = 0.0f;  // symmetric Leia FOV → no horizontal skew
	}

	// Vulkan flips Y in clip space vs OpenGL — negate the Y-related
	// terms so triangles aren't upside-down.
	p.m[5]  = -p.m[5];
	p.m[9]  = -p.m[9];
	return p;
}

// Read a float system property (live-tunable knob), e.g.
//   adb shell setprop debug.dxr.aspect_mult 1.5
// Returns default_val if unset/unparseable. Used to tune the SBS aspect
// multiplier on the device without rebuilding.
static float
get_prop_float(const char *name, float default_val)
{
	char buf[PROP_VALUE_MAX] = {0};
	int n = __system_property_get(name, buf);
	if (n <= 0) {
		return default_val;
	}
	char *end = nullptr;
	float v = strtof(buf, &end);
	return (end != buf) ? v : default_val;
}

// Model matrix for the spinning cube: rotate about Y (and slower about X)
// by `angle` radians, then push 1 m in front of the viewer (-Z in the
// reference space). Depth testing makes occlusion correct regardless of
// the rotation signs, so direction here is purely cosmetic.
Mat4
cube_model_matrix(float angle)
{
	const float cy = std::cos(angle), sy = std::sin(angle);
	const float ax = angle * 0.5f;
	const float cx = std::cos(ax), sx = std::sin(ax);

	Mat4 ry = mat4_identity();  // rotate about Y
	ry.m[0] = cy;  ry.m[2] = -sy;
	ry.m[8] = sy;  ry.m[10] = cy;

	Mat4 rx = mat4_identity();  // rotate about X
	rx.m[5] = cx;  rx.m[6] = sx;
	rx.m[9] = -sx; rx.m[10] = cx;

	Mat4 t = mat4_identity();   // translate forward (-Z); closer = bigger + more pop
	t.m[14] = -0.6f;

	return mat4_mul(t, mat4_mul(ry, rx));
}

// ─── render pass + pipeline ───────────────────────────────────────────

bool
create_render_pass()
{
	VkAttachmentDescription color = {};
	color.format = g_swapchain_format;
	color.samples = VK_SAMPLE_COUNT_1_BIT;
	color.loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
	color.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
	color.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
	color.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
	// xrAcquireSwapchainImage delivers in COLOR_ATTACHMENT_OPTIMAL per
	// OpenXR spec; xrReleaseSwapchainImage expects it to stay there.
	color.initialLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
	color.finalLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;

	VkAttachmentReference color_ref = {};
	color_ref.attachment = 0;
	color_ref.layout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;

	// Depth attachment for the cube. Cleared each frame, not stored (only
	// needed within the render pass for occlusion).
	VkAttachmentDescription depth = {};
	depth.format = VK_FORMAT_D32_SFLOAT;
	depth.samples = VK_SAMPLE_COUNT_1_BIT;
	depth.loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
	depth.storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
	depth.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
	depth.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
	depth.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
	depth.finalLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;

	VkAttachmentReference depth_ref = {};
	depth_ref.attachment = 1;
	depth_ref.layout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;

	VkSubpassDescription subpass = {};
	subpass.pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
	subpass.colorAttachmentCount = 1;
	subpass.pColorAttachments = &color_ref;
	subpass.pDepthStencilAttachment = &depth_ref;

	VkAttachmentDescription attachments[2] = {color, depth};
	VkRenderPassCreateInfo rpci = {};
	rpci.sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
	rpci.attachmentCount = 2;
	rpci.pAttachments = attachments;
	rpci.subpassCount = 1;
	rpci.pSubpasses = &subpass;

	VkResult res = vkCreateRenderPass(g_vk_device, &rpci, nullptr, &g_render_pass);
	if (res != VK_SUCCESS) {
		LOGE("vkCreateRenderPass failed: %d", res);
		return false;
	}
	DXR_HW_DBG("render pass created (format=0x%x)", (uint32_t)g_swapchain_format);
	return true;
}

bool
create_pipeline()
{
	// Shader modules. The spirv_shaders() CMake helper generates
	// unsigned-int arrays with idiomatic identifier names from the
	// source path: "shaders/triangle.vert" → "shaders_triangle_vert".
	VkShaderModuleCreateInfo vs_ci = {};
	vs_ci.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
	vs_ci.codeSize = sizeof(shaders_cube_vert);
	vs_ci.pCode = shaders_cube_vert;
	if (vkCreateShaderModule(g_vk_device, &vs_ci, nullptr, &g_vs_module) != VK_SUCCESS) {
		LOGE("vkCreateShaderModule(vert) failed");
		return false;
	}

	VkShaderModuleCreateInfo fs_ci = {};
	fs_ci.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
	fs_ci.codeSize = sizeof(shaders_cube_frag);
	fs_ci.pCode = shaders_cube_frag;
	if (vkCreateShaderModule(g_vk_device, &fs_ci, nullptr, &g_fs_module) != VK_SUCCESS) {
		LOGE("vkCreateShaderModule(frag) failed");
		return false;
	}

	VkPipelineShaderStageCreateInfo stages[2] = {};
	stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
	stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
	stages[0].module = g_vs_module;
	stages[0].pName = "main";
	stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
	stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
	stages[1].module = g_fs_module;
	stages[1].pName = "main";

	VkPushConstantRange pc_range = {};
	pc_range.stageFlags = VK_SHADER_STAGE_VERTEX_BIT;
	pc_range.offset = 0;
	pc_range.size = sizeof(Mat4);

	VkPipelineLayoutCreateInfo pli = {};
	pli.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
	pli.pushConstantRangeCount = 1;
	pli.pPushConstantRanges = &pc_range;
	if (vkCreatePipelineLayout(g_vk_device, &pli, nullptr, &g_pipeline_layout) != VK_SUCCESS) {
		LOGE("vkCreatePipelineLayout failed");
		return false;
	}

	// Vertex input: one interleaved buffer of CubeVertex {vec3 pos; vec3 color;}.
	VkVertexInputBindingDescription vbind = {};
	vbind.binding = 0;
	vbind.stride = sizeof(CubeVertex);
	vbind.inputRate = VK_VERTEX_INPUT_RATE_VERTEX;
	VkVertexInputAttributeDescription vattrs[2] = {};
	vattrs[0].location = 0;  // in_pos
	vattrs[0].binding = 0;
	vattrs[0].format = VK_FORMAT_R32G32B32_SFLOAT;
	vattrs[0].offset = offsetof(CubeVertex, pos);
	vattrs[1].location = 1;  // in_color
	vattrs[1].binding = 0;
	vattrs[1].format = VK_FORMAT_R32G32B32_SFLOAT;
	vattrs[1].offset = offsetof(CubeVertex, color);

	VkPipelineVertexInputStateCreateInfo vi = {};
	vi.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
	vi.vertexBindingDescriptionCount = 1;
	vi.pVertexBindingDescriptions = &vbind;
	vi.vertexAttributeDescriptionCount = 2;
	vi.pVertexAttributeDescriptions = vattrs;

	VkPipelineInputAssemblyStateCreateInfo ia = {};
	ia.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
	ia.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;

	VkPipelineViewportStateCreateInfo vp = {};
	vp.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
	vp.viewportCount = 1;
	vp.scissorCount = 1;

	VkPipelineRasterizationStateCreateInfo rs = {};
	rs.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
	rs.polygonMode = VK_POLYGON_MODE_FILL;
	// No cull — the triangle is drawn world-facing but we may approach
	// it from either side as the head moves; better to keep both sides
	// visible than to debug a missing-triangle problem later.
	rs.cullMode = VK_CULL_MODE_NONE;
	rs.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
	rs.lineWidth = 1.0f;

	VkPipelineMultisampleStateCreateInfo ms = {};
	ms.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
	ms.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

	VkPipelineColorBlendAttachmentState cba = {};
	cba.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
	                     VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
	VkPipelineColorBlendStateCreateInfo cb = {};
	cb.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
	cb.attachmentCount = 1;
	cb.pAttachments = &cba;

	// Depth test so the spinning cube's near faces occlude its far faces
	// (cube renders correctly regardless of triangle winding — we cull none).
	VkPipelineDepthStencilStateCreateInfo ds = {};
	ds.sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
	ds.depthTestEnable = VK_TRUE;
	ds.depthWriteEnable = VK_TRUE;
	ds.depthCompareOp = VK_COMPARE_OP_LESS;

	const VkDynamicState dyn_states[2] = {VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR};
	VkPipelineDynamicStateCreateInfo dyn = {};
	dyn.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
	dyn.dynamicStateCount = 2;
	dyn.pDynamicStates = dyn_states;

	VkGraphicsPipelineCreateInfo gpi = {};
	gpi.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
	gpi.stageCount = 2;
	gpi.pStages = stages;
	gpi.pVertexInputState = &vi;
	gpi.pInputAssemblyState = &ia;
	gpi.pViewportState = &vp;
	gpi.pRasterizationState = &rs;
	gpi.pMultisampleState = &ms;
	gpi.pDepthStencilState = &ds;
	gpi.pColorBlendState = &cb;
	gpi.pDynamicState = &dyn;
	gpi.layout = g_pipeline_layout;
	gpi.renderPass = g_render_pass;
	gpi.subpass = 0;

	VkResult pres = vkCreateGraphicsPipelines(g_vk_device, VK_NULL_HANDLE, 1, &gpi, nullptr,
	                                          &g_pipeline);
	if (pres != VK_SUCCESS) {
		LOGE("vkCreateGraphicsPipelines failed: %d", pres);
		return false;
	}
	DXR_HW_DBG("graphics pipeline created");
	return true;
}

// Pick a memory type satisfying `type_bits` with the requested properties.
uint32_t
find_memory_type(uint32_t type_bits, VkMemoryPropertyFlags props)
{
	VkPhysicalDeviceMemoryProperties mp = {};
	vkGetPhysicalDeviceMemoryProperties(g_vk_phys_device, &mp);
	for (uint32_t i = 0; i < mp.memoryTypeCount; ++i) {
		if ((type_bits & (1u << i)) &&
		    (mp.memoryTypes[i].propertyFlags & props) == props) {
			return i;
		}
	}
	return UINT32_MAX;
}

// ─── texture-class helpers (app-owns-presentation) ────────────────────────

// Create the shared weave-target VkImage at panel resolution and compute the
// canvas sub-rect. The runtime weaves 3D into the canvas; we 2D-fill the
// surround and blit the canvas to our own swapchain in present_frame().
bool
create_shared_image()
{
	if (g_app == nullptr || g_app->window == nullptr) {
		LOGE("create_shared_image: no window");
		return false;
	}
	g_shared_w = (uint32_t)ANativeWindow_getWidth(g_app->window);
	g_shared_h = (uint32_t)ANativeWindow_getHeight(g_app->window);
	if (g_shared_w == 0 || g_shared_h == 0) {
		LOGE("create_shared_image: window has zero extent");
		return false;
	}

	VkImageCreateInfo ici = {};
	ici.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
	ici.imageType = VK_IMAGE_TYPE_2D;
	ici.format = kSharedFormat;
	ici.extent = {g_shared_w, g_shared_h, 1};
	ici.mipLevels = 1;
	ici.arrayLayers = 1;
	ici.samples = VK_SAMPLE_COUNT_1_BIT;
	ici.tiling = VK_IMAGE_TILING_OPTIMAL;
	ici.usage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT |  // DP weave target
	            VK_IMAGE_USAGE_TRANSFER_SRC_BIT |       // our present blit
	            VK_IMAGE_USAGE_SAMPLED_BIT;
	ici.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
	ici.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
	if (vkCreateImage(g_vk_device, &ici, nullptr, &g_shared_image) != VK_SUCCESS) {
		LOGE("create_shared_image: vkCreateImage failed");
		return false;
	}

	VkMemoryRequirements req = {};
	vkGetImageMemoryRequirements(g_vk_device, g_shared_image, &req);
	VkMemoryAllocateInfo mai = {};
	mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
	mai.allocationSize = req.size;
	mai.memoryTypeIndex = find_memory_type(req.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
	if (mai.memoryTypeIndex == UINT32_MAX ||
	    vkAllocateMemory(g_vk_device, &mai, nullptr, &g_shared_mem) != VK_SUCCESS) {
		LOGE("create_shared_image: memory alloc failed");
		return false;
	}
	vkBindImageMemory(g_vk_device, g_shared_image, g_shared_mem, 0);

	// Canvas sub-rect: inset on each side. 0.0 → full panel (no surround).
	uint32_t ix = (uint32_t)(kCanvasInsetFrac * (float)g_shared_w);
	uint32_t iy = (uint32_t)(kCanvasInsetFrac * (float)g_shared_h);
	g_canvas_x = (int32_t)ix;
	g_canvas_y = (int32_t)iy;
	g_canvas_w = g_shared_w - 2 * ix;
	g_canvas_h = g_shared_h - 2 * iy;

	LOGI("Shared image %ux%u, canvas rect=(%d,%d %ux%u)", g_shared_w, g_shared_h,
	     g_canvas_x, g_canvas_y, g_canvas_w, g_canvas_h);
	return true;
}

// Create the app's own present swapchain on the Activity's ANativeWindow. The
// runtime presents nothing in texture mode — we composite + present here.
bool
create_present_swapchain()
{
	VkAndroidSurfaceCreateInfoKHR sci = {};
	sci.sType = VK_STRUCTURE_TYPE_ANDROID_SURFACE_CREATE_INFO_KHR;
	sci.window = g_app->window;
	if (vkCreateAndroidSurfaceKHR(g_vk_instance, &sci, nullptr, &g_present_surface) != VK_SUCCESS) {
		LOGE("create_present_swapchain: vkCreateAndroidSurfaceKHR failed");
		return false;
	}

	VkBool32 supported = VK_FALSE;
	vkGetPhysicalDeviceSurfaceSupportKHR(g_vk_phys_device, g_vk_queue_family,
	                                     g_present_surface, &supported);
	if (!supported) {
		LOGE("create_present_swapchain: queue family %u can't present", g_vk_queue_family);
		return false;
	}

	VkSurfaceCapabilitiesKHR caps = {};
	vkGetPhysicalDeviceSurfaceCapabilitiesKHR(g_vk_phys_device, g_present_surface, &caps);

	// Pick a surface format: prefer B8G8R8A8_UNORM to match the blit source.
	uint32_t fmt_count = 0;
	vkGetPhysicalDeviceSurfaceFormatsKHR(g_vk_phys_device, g_present_surface, &fmt_count, nullptr);
	VkSurfaceFormatKHR fmts[32] = {};
	if (fmt_count > 32) fmt_count = 32;
	vkGetPhysicalDeviceSurfaceFormatsKHR(g_vk_phys_device, g_present_surface, &fmt_count, fmts);
	VkSurfaceFormatKHR chosen = fmts[0];
	for (uint32_t i = 0; i < fmt_count; ++i) {
		if (fmts[i].format == kSharedFormat) { chosen = fmts[i]; break; }
	}
	g_present_format = chosen.format;

	g_present_w = caps.currentExtent.width;
	g_present_h = caps.currentExtent.height;
	if (g_present_w == 0xFFFFFFFFu) { g_present_w = g_shared_w; g_present_h = g_shared_h; }

	uint32_t min_images = caps.minImageCount + 1;
	if (caps.maxImageCount > 0 && min_images > caps.maxImageCount) min_images = caps.maxImageCount;

	// Woven 3D in the canvas region must NOT be rotated by WSI (the lenticular
	// is fixed to the panel) — prefer IDENTITY transform, like the runtime's
	// vk_native target does. The 2D surround tolerates either.
	VkSurfaceTransformFlagBitsKHR pre_xform =
	    (caps.supportedTransforms & VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR)
	        ? VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR
	        : caps.currentTransform;

	VkSwapchainCreateInfoKHR ci = {};
	ci.sType = VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR;
	ci.surface = g_present_surface;
	ci.minImageCount = min_images;
	ci.imageFormat = g_present_format;
	ci.imageColorSpace = chosen.colorSpace;
	ci.imageExtent = {g_present_w, g_present_h};
	ci.imageArrayLayers = 1;
	ci.imageUsage = VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;
	ci.imageSharingMode = VK_SHARING_MODE_EXCLUSIVE;
	ci.preTransform = pre_xform;
	ci.compositeAlpha = VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;
	ci.presentMode = VK_PRESENT_MODE_FIFO_KHR;  // always supported
	ci.clipped = VK_TRUE;
	if (vkCreateSwapchainKHR(g_vk_device, &ci, nullptr, &g_present_swapchain) != VK_SUCCESS) {
		LOGE("create_present_swapchain: vkCreateSwapchainKHR failed");
		return false;
	}

	g_present_image_count = 0;
	vkGetSwapchainImagesKHR(g_vk_device, g_present_swapchain, &g_present_image_count, nullptr);
	if (g_present_image_count > 8) g_present_image_count = 8;
	vkGetSwapchainImagesKHR(g_vk_device, g_present_swapchain, &g_present_image_count, g_present_images);

	VkSemaphoreCreateInfo sem_ci = {};
	sem_ci.sType = VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO;
	vkCreateSemaphore(g_vk_device, &sem_ci, nullptr, &g_present_acquire_sem);
	vkCreateSemaphore(g_vk_device, &sem_ci, nullptr, &g_present_blit_sem);

	g_present_ready = true;
	LOGI("Present swapchain %ux%u, %u images, fmt=0x%x, xform=0x%x",
	     g_present_w, g_present_h, g_present_image_count, g_present_format, pre_xform);
	return true;
}

// Composite the woven shared image (canvas region) + 2D surround into the
// app's swapchain and present. Called after xrEndFrame — the runtime's weave
// already vkQueueWaitIdle'd, so the canvas pixels are ready.
void
present_frame()
{
	if (!g_present_ready || g_shared_image == VK_NULL_HANDLE) return;

	uint32_t idx = 0;
	VkResult res = vkAcquireNextImageKHR(g_vk_device, g_present_swapchain, UINT64_MAX,
	                                     g_present_acquire_sem, VK_NULL_HANDLE, &idx);
	if (res == VK_ERROR_OUT_OF_DATE_KHR || res == VK_SUBOPTIMAL_KHR) {
		// Rotation/resize — swapchain recreation is a follow-up; skip this frame.
		DXR_HW_DBG_ONCE("present acquire returned %d (out-of-date) — skipping", (int)res);
		return;
	}
	if (res != VK_SUCCESS) {
		LOGW("vkAcquireNextImageKHR failed: %d", (int)res);
		return;
	}
	VkImage dst = g_present_images[idx];

	VkCommandBufferAllocateInfo cai = {};
	cai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
	cai.commandPool = g_app_cmd_pool;
	cai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
	cai.commandBufferCount = 1;
	VkCommandBuffer cmd = VK_NULL_HANDLE;
	if (vkAllocateCommandBuffers(g_vk_device, &cai, &cmd) != VK_SUCCESS) return;

	VkCommandBufferBeginInfo bi = {};
	bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
	bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
	vkBeginCommandBuffer(cmd, &bi);

	const VkImageSubresourceRange full = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};

	// dst: UNDEFINED → TRANSFER_DST
	VkImageMemoryBarrier b = {};
	b.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
	b.srcAccessMask = 0;
	b.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
	b.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED;
	b.newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
	b.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
	b.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
	b.image = dst;
	b.subresourceRange = full;
	vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT,
	                     0, 0, nullptr, 0, nullptr, 1, &b);

	// shared: the DP just wrote it as a color attachment. Transition to
	// TRANSFER_SRC to read it. ★ DEVICE-ITERATION POINT: oldLayout must match
	// the Leia DP render-pass finalLayout (assumed COLOR_ATTACHMENT_OPTIMAL).
	VkImageMemoryBarrier sb = {};
	sb.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
	sb.srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
	sb.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
	sb.oldLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
	sb.newLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
	sb.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
	sb.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
	sb.image = g_shared_image;
	sb.subresourceRange = full;
	vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
	                     VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 0, nullptr, 0, nullptr, 1, &sb);

	// 2D surround: clear the whole present image to a distinct color.
	VkClearColorValue surround = {{0.05f, 0.08f, 0.14f, 1.0f}};  // dark slate-blue
	vkCmdClearColorImage(cmd, dst, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, &surround, 1, &full);

	// Order the clear before the canvas blit (both write dst).
	VkMemoryBarrier mb = {};
	mb.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER;
	mb.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
	mb.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
	vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT,
	                     0, 1, &mb, 0, nullptr, 0, nullptr);

	// Blit the woven canvas sub-rect 1:1 into the present image.
	VkImageBlit blit = {};
	blit.srcSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
	blit.srcOffsets[0] = {g_canvas_x, g_canvas_y, 0};
	blit.srcOffsets[1] = {g_canvas_x + (int32_t)g_canvas_w, g_canvas_y + (int32_t)g_canvas_h, 1};
	blit.dstSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
	blit.dstOffsets[0] = {g_canvas_x, g_canvas_y, 0};
	blit.dstOffsets[1] = {g_canvas_x + (int32_t)g_canvas_w, g_canvas_y + (int32_t)g_canvas_h, 1};
	vkCmdBlitImage(cmd, g_shared_image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
	               dst, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &blit, VK_FILTER_LINEAR);

	// dst → PRESENT_SRC
	b.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
	b.dstAccessMask = 0;
	b.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
	b.newLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;
	vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT,
	                     0, 0, nullptr, 0, nullptr, 1, &b);

	// shared: TRANSFER_SRC → COLOR_ATTACHMENT_OPTIMAL (restore for next weave).
	sb.srcAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
	sb.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
	sb.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
	sb.newLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
	vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT,
	                     VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
	                     0, 0, nullptr, 0, nullptr, 1, &sb);

	vkEndCommandBuffer(cmd);

	VkPipelineStageFlags wait_stage = VK_PIPELINE_STAGE_TRANSFER_BIT;
	VkSubmitInfo si = {};
	si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
	si.waitSemaphoreCount = 1;
	si.pWaitSemaphores = &g_present_acquire_sem;
	si.pWaitDstStageMask = &wait_stage;
	si.commandBufferCount = 1;
	si.pCommandBuffers = &cmd;
	si.signalSemaphoreCount = 1;
	si.pSignalSemaphores = &g_present_blit_sem;
	vkQueueSubmit(g_vk_queue, 1, &si, VK_NULL_HANDLE);

	VkPresentInfoKHR pi = {};
	pi.sType = VK_STRUCTURE_TYPE_PRESENT_INFO_KHR;
	pi.waitSemaphoreCount = 1;
	pi.pWaitSemaphores = &g_present_blit_sem;
	pi.swapchainCount = 1;
	pi.pSwapchains = &g_present_swapchain;
	pi.pImageIndices = &idx;
	vkQueuePresentKHR(g_vk_queue, &pi);

	// Serialize (matches the rest of this app's per-frame vkQueueWaitIdle idiom)
	// and lets us free the command buffer safely.
	vkQueueWaitIdle(g_vk_queue);
	vkFreeCommandBuffers(g_vk_device, g_app_cmd_pool, 1, &cmd);
}

void
destroy_present_swapchain()
{
	if (g_vk_device == VK_NULL_HANDLE) return;
	if (g_present_blit_sem != VK_NULL_HANDLE) {
		vkDestroySemaphore(g_vk_device, g_present_blit_sem, nullptr);
		g_present_blit_sem = VK_NULL_HANDLE;
	}
	if (g_present_acquire_sem != VK_NULL_HANDLE) {
		vkDestroySemaphore(g_vk_device, g_present_acquire_sem, nullptr);
		g_present_acquire_sem = VK_NULL_HANDLE;
	}
	if (g_present_swapchain != VK_NULL_HANDLE) {
		vkDestroySwapchainKHR(g_vk_device, g_present_swapchain, nullptr);
		g_present_swapchain = VK_NULL_HANDLE;
	}
	if (g_present_surface != VK_NULL_HANDLE) {
		vkDestroySurfaceKHR(g_vk_instance, g_present_surface, nullptr);
		g_present_surface = VK_NULL_HANDLE;
	}
	g_present_ready = false;
}

void
destroy_shared_image()
{
	if (g_vk_device == VK_NULL_HANDLE) return;
	if (g_shared_image != VK_NULL_HANDLE) {
		vkDestroyImage(g_vk_device, g_shared_image, nullptr);
		g_shared_image = VK_NULL_HANDLE;
	}
	if (g_shared_mem != VK_NULL_HANDLE) {
		vkFreeMemory(g_vk_device, g_shared_mem, nullptr);
		g_shared_mem = VK_NULL_HANDLE;
	}
}

// Upload the cube's 36 vertices (6 faces × 2 triangles, per-face color) into
// a host-visible vertex buffer. Half-extent 0.12 m → ~24 cm cube.
bool
create_cube_vertex_buffer()
{
	const float S = 0.22f;  // half-extent → ~44 cm cube (bigger = easier to see)
	const float R[3] = {0.90f, 0.20f, 0.20f};  // front  red
	const float G[3] = {0.20f, 0.80f, 0.30f};  // back   green
	const float B[3] = {0.25f, 0.45f, 0.95f};  // left   blue
	const float Y[3] = {0.95f, 0.80f, 0.20f};  // right  yellow
	const float M[3] = {0.85f, 0.35f, 0.85f};  // top    magenta
	const float C[3] = {0.25f, 0.80f, 0.85f};  // bottom cyan
#define V(x, y, z, c) {{x, y, z}, {c[0], c[1], c[2]}}
	const CubeVertex verts[kCubeVertexCount] = {
	    // front (z+)
	    V(-S, -S, S, R), V(S, -S, S, R), V(S, S, S, R),
	    V(-S, -S, S, R), V(S, S, S, R), V(-S, S, S, R),
	    // back (z-)
	    V(S, -S, -S, G), V(-S, -S, -S, G), V(-S, S, -S, G),
	    V(S, -S, -S, G), V(-S, S, -S, G), V(S, S, -S, G),
	    // left (x-)
	    V(-S, -S, -S, B), V(-S, -S, S, B), V(-S, S, S, B),
	    V(-S, -S, -S, B), V(-S, S, S, B), V(-S, S, -S, B),
	    // right (x+)
	    V(S, -S, S, Y), V(S, -S, -S, Y), V(S, S, -S, Y),
	    V(S, -S, S, Y), V(S, S, -S, Y), V(S, S, S, Y),
	    // top (y+)
	    V(-S, S, S, M), V(S, S, S, M), V(S, S, -S, M),
	    V(-S, S, S, M), V(S, S, -S, M), V(-S, S, -S, M),
	    // bottom (y-)
	    V(-S, -S, -S, C), V(S, -S, -S, C), V(S, -S, S, C),
	    V(-S, -S, -S, C), V(S, -S, S, C), V(-S, -S, S, C),
	};
#undef V

	const VkDeviceSize size = sizeof(verts);
	VkBufferCreateInfo bci = {};
	bci.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
	bci.size = size;
	bci.usage = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;
	bci.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
	if (vkCreateBuffer(g_vk_device, &bci, nullptr, &g_cube_vbuf) != VK_SUCCESS) {
		LOGE("create cube vertex buffer failed");
		return false;
	}

	VkMemoryRequirements req = {};
	vkGetBufferMemoryRequirements(g_vk_device, g_cube_vbuf, &req);
	VkMemoryAllocateInfo mai = {};
	mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
	mai.allocationSize = req.size;
	mai.memoryTypeIndex = find_memory_type(
	    req.memoryTypeBits,
	    VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
	if (mai.memoryTypeIndex == UINT32_MAX ||
	    vkAllocateMemory(g_vk_device, &mai, nullptr, &g_cube_vbuf_mem) != VK_SUCCESS) {
		LOGE("alloc cube vertex buffer memory failed");
		return false;
	}
	vkBindBufferMemory(g_vk_device, g_cube_vbuf, g_cube_vbuf_mem, 0);

	void *mapped = nullptr;
	if (vkMapMemory(g_vk_device, g_cube_vbuf_mem, 0, size, 0, &mapped) != VK_SUCCESS) {
		LOGE("map cube vertex buffer failed");
		return false;
	}
	memcpy(mapped, verts, (size_t)size);
	vkUnmapMemory(g_vk_device, g_cube_vbuf_mem);
	DXR_HW_DBG("cube vertex buffer uploaded (%u verts)", kCubeVertexCount);
	return true;
}

// ─── in-frame HUD ─────────────────────────────────────────────────────────
// 3x5 bitmap font. Each glyph is 5 rows; the low 3 bits of each row are the
// pixels (bit2 = left column, bit0 = right column). Only the characters the
// HUD needs are defined; unknown chars render blank.
static void
hud_glyph(char ch, uint8_t rows[5])
{
	auto set = [&](uint8_t a, uint8_t b, uint8_t c, uint8_t d, uint8_t e) {
		rows[0] = a; rows[1] = b; rows[2] = c; rows[3] = d; rows[4] = e;
	};
	switch (ch) {
	case '0': set(0b111,0b101,0b101,0b101,0b111); break;
	case '1': set(0b010,0b110,0b010,0b010,0b111); break;
	case '2': set(0b111,0b001,0b111,0b100,0b111); break;
	case '3': set(0b111,0b001,0b111,0b001,0b111); break;
	case '4': set(0b101,0b101,0b111,0b001,0b001); break;
	case '5': set(0b111,0b100,0b111,0b001,0b111); break;
	case '6': set(0b111,0b100,0b111,0b101,0b111); break;
	case '7': set(0b111,0b001,0b010,0b010,0b010); break;
	case '8': set(0b111,0b101,0b111,0b101,0b111); break;
	case '9': set(0b111,0b101,0b111,0b001,0b111); break;
	case '-': set(0b000,0b000,0b111,0b000,0b000); break;
	case '+': set(0b000,0b010,0b111,0b010,0b000); break;
	case '.': set(0b000,0b000,0b000,0b000,0b010); break;
	case ':': set(0b000,0b010,0b000,0b010,0b000); break;
	case 'B': set(0b110,0b101,0b110,0b101,0b110); break;
	case 'G': set(0b011,0b100,0b101,0b101,0b011); break;
	case 'E': set(0b111,0b100,0b110,0b100,0b111); break;
	case 'X': set(0b101,0b101,0b010,0b101,0b101); break;
	case 'Y': set(0b101,0b101,0b010,0b010,0b010); break;
	case 'Z': set(0b111,0b001,0b010,0b100,0b111); break;
	default:  set(0,0,0,0,0); break;
	}
}

static uint32_t
hud_quad(CubeVertex *v, uint32_t n, float x0, float y0, float x1, float y1,
         float z, const float c[3])
{
	if (n + 6 > kHudMaxVerts) {
		return n;
	}
	const CubeVertex a = {{x0, y0, z}, {c[0], c[1], c[2]}};
	const CubeVertex b = {{x1, y0, z}, {c[0], c[1], c[2]}};
	const CubeVertex d = {{x1, y1, z}, {c[0], c[1], c[2]}};
	const CubeVertex e = {{x0, y1, z}, {c[0], c[1], c[2]}};
	v[n++] = a; v[n++] = b; v[n++] = d;
	v[n++] = a; v[n++] = d; v[n++] = e;
	return n;
}

// Draw a string at (ox, oy) top-left in NDC. px/py = glyph pixel size.
static uint32_t
hud_text(CubeVertex *v, uint32_t n, const char *s, float ox, float oy,
         float px, float py, float z, const float c[3])
{
	float x = ox;
	for (; *s != '\0'; ++s) {
		if (*s != ' ') {
			uint8_t g[5];
			hud_glyph(*s, g);
			for (int r = 0; r < 5; ++r) {
				for (int col = 0; col < 3; ++col) {
					if (g[r] & (1 << (2 - col))) {
						const float qx = x + col * px;
						const float qy = oy + r * py;
						n = hud_quad(v, n, qx, qy, qx + px * 0.85f,
						             qy + py * 0.85f, z, c);
					}
				}
			}
		}
		x += 4.0f * px;  // 3-wide glyph + 1 column gap
	}
	return n;
}

// Format a float as a signed 2-decimal string ("-0.03"). No locale, no libm.
static void
hud_ftoa(float val, char *buf, size_t cap)
{
	const int neg = val < 0.0f;
	float a = neg ? -val : val;
	int whole = (int)a;
	int frac = (int)((a - (float)whole) * 100.0f + 0.5f);
	if (frac >= 100) { whole += 1; frac -= 100; }
	snprintf(buf, cap, "%s%d.%02d", neg ? "-" : "+", whole, frac);
}

// Build the HUD geometry into the mapped buffer. Returns the vertex count.
static uint32_t
build_hud(CubeVertex *v)
{
	uint32_t n = 0;
	const float px = 0.016f, py = 0.026f;  // glyph pixel size in NDC
	const float white[3] = {1.0f, 1.0f, 1.0f};

	// Eye-position readout (BG toggle button removed; background is always
	// clean black now). oy=-0.80 with the HUD's vflip lands it at the TOP edge.
	char xs[16], ys[16], zs[16], line[64];
	hud_ftoa(g_eye_x.load(std::memory_order_relaxed), xs, sizeof xs);
	hud_ftoa(g_eye_y.load(std::memory_order_relaxed), ys, sizeof ys);
	hud_ftoa(g_eye_z.load(std::memory_order_relaxed), zs, sizeof zs);
	snprintf(line, sizeof line, "X%s Y%s Z%s", xs, ys, zs);
	n = hud_text(v, n, line, -0.98f, -0.80f, px, py, 0.04f, white);
	return n;
}

static bool
create_hud_buffer()
{
	const VkDeviceSize size = sizeof(CubeVertex) * kHudMaxVerts;
	VkBufferCreateInfo bci = {};
	bci.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
	bci.size = size;
	bci.usage = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;
	bci.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
	if (vkCreateBuffer(g_vk_device, &bci, nullptr, &g_hud_vbuf) != VK_SUCCESS) {
		LOGE("create HUD vertex buffer failed");
		return false;
	}
	VkMemoryRequirements req = {};
	vkGetBufferMemoryRequirements(g_vk_device, g_hud_vbuf, &req);
	VkMemoryAllocateInfo mai = {};
	mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
	mai.allocationSize = req.size;
	mai.memoryTypeIndex = find_memory_type(
	    req.memoryTypeBits,
	    VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
	if (mai.memoryTypeIndex == UINT32_MAX ||
	    vkAllocateMemory(g_vk_device, &mai, nullptr, &g_hud_vbuf_mem) != VK_SUCCESS) {
		LOGE("alloc HUD vertex buffer memory failed");
		return false;
	}
	vkBindBufferMemory(g_vk_device, g_hud_vbuf, g_hud_vbuf_mem, 0);
	// Persistently mapped (host-coherent): rebuilt each frame in record_draw.
	if (vkMapMemory(g_vk_device, g_hud_vbuf_mem, 0, size, 0, &g_hud_mapped) != VK_SUCCESS) {
		LOGE("map HUD vertex buffer failed");
		return false;
	}
	DXR_HW_DBG("HUD vertex buffer created (%u verts max)", kHudMaxVerts);
	return true;
}

// Create the per-view depth target (D32_SFLOAT, view dimensions).
bool
create_view_depth(uint32_t view_idx)
{
	VkImageCreateInfo ici = {};
	ici.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
	ici.imageType = VK_IMAGE_TYPE_2D;
	ici.format = VK_FORMAT_D32_SFLOAT;
	ici.extent = {g_views[view_idx].width, g_views[view_idx].height, 1};
	ici.mipLevels = 1;
	ici.arrayLayers = 1;
	ici.samples = VK_SAMPLE_COUNT_1_BIT;
	ici.tiling = VK_IMAGE_TILING_OPTIMAL;
	ici.usage = VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT;
	ici.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
	ici.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
	if (vkCreateImage(g_vk_device, &ici, nullptr, &g_views[view_idx].depth_image) != VK_SUCCESS) {
		LOGE("create depth image view=%u failed", view_idx);
		return false;
	}

	VkMemoryRequirements req = {};
	vkGetImageMemoryRequirements(g_vk_device, g_views[view_idx].depth_image, &req);
	VkMemoryAllocateInfo mai = {};
	mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
	mai.allocationSize = req.size;
	mai.memoryTypeIndex = find_memory_type(req.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
	if (mai.memoryTypeIndex == UINT32_MAX ||
	    vkAllocateMemory(g_vk_device, &mai, nullptr, &g_views[view_idx].depth_mem) != VK_SUCCESS) {
		LOGE("alloc depth memory view=%u failed", view_idx);
		return false;
	}
	vkBindImageMemory(g_vk_device, g_views[view_idx].depth_image, g_views[view_idx].depth_mem, 0);

	VkImageViewCreateInfo dvci = {};
	dvci.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
	dvci.image = g_views[view_idx].depth_image;
	dvci.viewType = VK_IMAGE_VIEW_TYPE_2D;
	dvci.format = VK_FORMAT_D32_SFLOAT;
	dvci.subresourceRange = {VK_IMAGE_ASPECT_DEPTH_BIT, 0, 1, 0, 1};
	if (vkCreateImageView(g_vk_device, &dvci, nullptr, &g_views[view_idx].depth_view) != VK_SUCCESS) {
		LOGE("create depth view view=%u failed", view_idx);
		return false;
	}
	return true;
}

bool
create_view_framebuffers(uint32_t view_idx)
{
	if (!create_view_depth(view_idx)) {
		return false;
	}
	for (uint32_t i = 0; i < g_views[view_idx].image_count; ++i) {
		VkImageViewCreateInfo ivci = {};
		ivci.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
		ivci.image = g_views[view_idx].images[i].image;
		ivci.viewType = VK_IMAGE_VIEW_TYPE_2D;
		ivci.format = g_swapchain_format;
		ivci.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
		if (vkCreateImageView(g_vk_device, &ivci, nullptr,
		                      &g_views[view_idx].image_views[i]) != VK_SUCCESS) {
			LOGE("vkCreateImageView view=%u img=%u failed", view_idx, i);
			return false;
		}

		VkImageView fb_attachments[2] = {g_views[view_idx].image_views[i],
		                                 g_views[view_idx].depth_view};
		VkFramebufferCreateInfo fbi = {};
		fbi.sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO;
		fbi.renderPass = g_render_pass;
		fbi.attachmentCount = 2;
		fbi.pAttachments = fb_attachments;
		fbi.width = g_views[view_idx].width;
		fbi.height = g_views[view_idx].height;
		fbi.layers = 1;
		if (vkCreateFramebuffer(g_vk_device, &fbi, nullptr,
		                        &g_views[view_idx].framebuffers[i]) != VK_SUCCESS) {
			LOGE("vkCreateFramebuffer view=%u img=%u failed", view_idx, i);
			return false;
		}
	}
	return true;
}

void
destroy_view_framebuffers(uint32_t view_idx)
{
	for (uint32_t i = 0; i < 8; ++i) {
		if (g_views[view_idx].framebuffers[i] != VK_NULL_HANDLE) {
			vkDestroyFramebuffer(g_vk_device, g_views[view_idx].framebuffers[i], nullptr);
			g_views[view_idx].framebuffers[i] = VK_NULL_HANDLE;
		}
		if (g_views[view_idx].image_views[i] != VK_NULL_HANDLE) {
			vkDestroyImageView(g_vk_device, g_views[view_idx].image_views[i], nullptr);
			g_views[view_idx].image_views[i] = VK_NULL_HANDLE;
		}
	}
	if (g_views[view_idx].depth_view != VK_NULL_HANDLE) {
		vkDestroyImageView(g_vk_device, g_views[view_idx].depth_view, nullptr);
		g_views[view_idx].depth_view = VK_NULL_HANDLE;
	}
	if (g_views[view_idx].depth_image != VK_NULL_HANDLE) {
		vkDestroyImage(g_vk_device, g_views[view_idx].depth_image, nullptr);
		g_views[view_idx].depth_image = VK_NULL_HANDLE;
	}
	if (g_views[view_idx].depth_mem != VK_NULL_HANDLE) {
		vkFreeMemory(g_vk_device, g_views[view_idx].depth_mem, nullptr);
		g_views[view_idx].depth_mem = VK_NULL_HANDLE;
	}
}

void
destroy_pipeline()
{
	if (g_pipeline != VK_NULL_HANDLE) {
		vkDestroyPipeline(g_vk_device, g_pipeline, nullptr);
		g_pipeline = VK_NULL_HANDLE;
	}
	if (g_pipeline_layout != VK_NULL_HANDLE) {
		vkDestroyPipelineLayout(g_vk_device, g_pipeline_layout, nullptr);
		g_pipeline_layout = VK_NULL_HANDLE;
	}
	if (g_fs_module != VK_NULL_HANDLE) {
		vkDestroyShaderModule(g_vk_device, g_fs_module, nullptr);
		g_fs_module = VK_NULL_HANDLE;
	}
	if (g_vs_module != VK_NULL_HANDLE) {
		vkDestroyShaderModule(g_vk_device, g_vs_module, nullptr);
		g_vs_module = VK_NULL_HANDLE;
	}
}

void
destroy_render_pass()
{
	if (g_render_pass != VK_NULL_HANDLE) {
		vkDestroyRenderPass(g_vk_device, g_render_pass, nullptr);
		g_render_pass = VK_NULL_HANDLE;
	}
}

// ─── per-frame draw ───────────────────────────────────────────────────
//
// Records and submits a cmd buffer that begins our render pass on the
// view's framebuffer, clears to a per-eye background color (red/blue —
// same calibration hint as the old record_clear), binds the triangle
// pipeline, pushes proj*view, and draws 3 vertices. Replaces the old
// vkCmdClearColorImage-only path.

// COLOR_ATTACHMENT_OPTIMAL (per OpenXR spec), transitions to
// TRANSFER_DST for the clear, then back to COLOR_ATTACHMENT_OPTIMAL
// for xrReleaseSwapchainImage.
bool
record_clear(uint32_t view_idx, uint32_t image_idx)
{
	VkCommandBufferAllocateInfo ai = {};
	ai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
	ai.commandPool = g_app_cmd_pool;
	ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
	ai.commandBufferCount = 1;
	VkCommandBuffer cmd = VK_NULL_HANDLE;
	if (vkAllocateCommandBuffers(g_vk_device, &ai, &cmd) != VK_SUCCESS) {
		return false;
	}

	VkCommandBufferBeginInfo bi = {};
	bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
	bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
	vkBeginCommandBuffer(cmd, &bi);

	VkImage img = g_views[view_idx].images[image_idx].image;

	VkImageMemoryBarrier to_dst = {};
	to_dst.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
	to_dst.srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
	to_dst.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
	to_dst.oldLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
	to_dst.newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
	to_dst.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
	to_dst.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
	to_dst.image = img;
	to_dst.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
	vkCmdPipelineBarrier(cmd,
	    VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
	    VK_PIPELINE_STAGE_TRANSFER_BIT,
	    0, 0, nullptr, 0, nullptr, 1, &to_dst);

	VkClearColorValue color = {};
	color.float32[0] = (view_idx == 0) ? 0.8f : 0.1f;  // left: red, right: blue
	color.float32[1] = 0.1f;
	color.float32[2] = (view_idx == 0) ? 0.1f : 0.8f;
	color.float32[3] = 1.0f;
	VkImageSubresourceRange range = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
	vkCmdClearColorImage(cmd, img, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
	                     &color, 1, &range);

	VkImageMemoryBarrier to_color = to_dst;
	to_color.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
	to_color.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
	to_color.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
	to_color.newLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
	vkCmdPipelineBarrier(cmd,
	    VK_PIPELINE_STAGE_TRANSFER_BIT,
	    VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
	    0, 0, nullptr, 0, nullptr, 1, &to_color);

	vkEndCommandBuffer(cmd);

	VkSubmitInfo si = {};
	si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
	si.commandBufferCount = 1;
	si.pCommandBuffers = &cmd;
	VkResult res = vkQueueSubmit(g_vk_queue, 1, &si, VK_NULL_HANDLE);
	if (res == VK_SUCCESS) {
		// vkQueueWaitIdle is a host stall but acceptable for this
		// skeleton — xrEndFrame needs the image to be ready and we
		// haven't wired a per-frame fence yet.
		vkQueueWaitIdle(g_vk_queue);
	}
	vkFreeCommandBuffers(g_vk_device, g_app_cmd_pool, 1, &cmd);
	return res == VK_SUCCESS;
}

// Triangle draw — supersedes record_clear. Begins our render pass on the
// per-view framebuffer (LOAD_OP_CLEAR clears to the per-eye background
// color so the lightfield calibration check stays visible behind the
// triangle), binds the triangle pipeline, pushes proj*view, draws 3
// vertices.
bool
record_draw(uint32_t view_idx, uint32_t image_idx, const XrView &view)
{
	VkCommandBufferAllocateInfo ai = {};
	ai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
	ai.commandPool = g_app_cmd_pool;
	ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
	ai.commandBufferCount = 1;
	VkCommandBuffer cmd = VK_NULL_HANDLE;
	if (vkAllocateCommandBuffers(g_vk_device, &ai, &cmd) != VK_SUCCESS) {
		return false;
	}

	VkCommandBufferBeginInfo bi = {};
	bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
	bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
	vkBeginCommandBuffer(cmd, &bi);

	// LOAD_OP_CLEAR. Background color is toggleable on-device (tap the screen,
	// or the Kotlin overlay). Default OFF → black in both eyes so the weave/3D
	// is judged against a clean black field. When ON, the per-eye red/blue
	// tint aids calibration test 2 (one-eye-covered tile-mapping check).
	// Clean black background on both eye tiles (LOAD_OP_CLEAR to black). The
	// per-eye red/blue 3D-check tint and the on-screen BG toggle were removed
	// for a clean display.
	VkClearValue clears[2] = {};
	clears[0].color.float32[3] = 1.0f;
	clears[1].depthStencil.depth = 1.0f;

	VkRenderPassBeginInfo rpbi = {};
	rpbi.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
	rpbi.renderPass = g_render_pass;
	rpbi.framebuffer = g_views[view_idx].framebuffers[image_idx];
	rpbi.renderArea.offset = {0, 0};
	rpbi.renderArea.extent = {g_views[view_idx].width, g_views[view_idx].height};
	rpbi.clearValueCount = 2;
	rpbi.pClearValues = clears;
	vkCmdBeginRenderPass(cmd, &rpbi, VK_SUBPASS_CONTENTS_INLINE);

	VkViewport vp = {};
	vp.x = 0.0f;
	vp.y = 0.0f;
	vp.width = (float)g_views[view_idx].width;
	vp.height = (float)g_views[view_idx].height;
	vp.minDepth = 0.0f;
	vp.maxDepth = 1.0f;
	vkCmdSetViewport(cmd, 0, 1, &vp);

	VkRect2D scissor = {};
	scissor.offset = {0, 0};
	scissor.extent = {g_views[view_idx].width, g_views[view_idx].height};
	vkCmdSetScissor(cmd, 0, 1, &scissor);

	vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, g_pipeline);

	// MVP = proj * view * model for this eye. Both eyes use the same
	// g_frame_count-derived angle so the stereo pair stays in sync.
	const Mat4 view_mat = view_matrix_from_pose(view.pose);
	// Two decoupled knobs (both live, read every frame):
	//  - aspect_mult (HORIZONTAL): also scales the stereo disparity (lower =
	//    more disparity). 1.0 gives the clean weave on the nubia NP02J; 0.5
	//    over-drove disparity and degraded the weave. Keep it at the
	//    weave-clean value.
	//  - yscale (VERTICAL): stretches clip-space Y to cancel the ~2x vertical
	//    squash (from the half-width SBS tile + the landscape-atlas->portrait-
	//    panel rotation). Vertical does NOT affect the horizontal disparity,
	//    so it un-squishes WITHOUT hurting the weave.
	//    adb shell setprop debug.dxr.aspect_mult <f> ; debug.dxr.yscale <f>
	// Orientation-aware aspect. Portrait: the weave rotates the landscape tile
	// onto the portrait panel, needing yscale=1.25. Landscape: no such rotation,
	// so the correction differs. Defaults derived from orientation; setprop
	// (>=0) overrides for tuning (set to -1 to return to the derived value).
	const int disp_rot_a = g_display_rotation.load(std::memory_order_relaxed) & 3;
	const bool is_landscape = (disp_rot_a == 1 || disp_rot_a == 3);
	const float am_prop = get_prop_float("debug.dxr.aspect_mult", -1.0f);
	const float ys_prop = get_prop_float("debug.dxr.yscale", -1.0f);
	// Landscape correct at yscale=1.0; portrait needs vertical compression
	// (cube was too tall) because the weave fits the tile to the taller portrait
	// panel. 0.6 is the first calibration point — tune if still tall / too wide.
	const float aspect_mult = (am_prop >= 0.0f) ? am_prop : 1.0f;
	const float yscale = (ys_prop >= 0.0f) ? ys_prop : (is_landscape ? 1.0f : 0.6f);
	const float aspect = aspect_mult * (float)g_views[view_idx].width / (float)g_views[view_idx].height;
	Mat4 proj_mat = projection_matrix_from_fov(view.fov, aspect, 0.05f, 100.0f);
	proj_mat.m[5] *= yscale;  // clip-space Y stretch (cancels vertical squash; disparity is horizontal, untouched)
	proj_mat.m[9] *= yscale;
	const Mat4 view_proj = mat4_mul(proj_mat, view_mat);
	const Mat4 model = cube_model_matrix((float)g_frame_count * 0.02f);
	const Mat4 mvp = mat4_mul(view_proj, model);
	vkCmdPushConstants(cmd, g_pipeline_layout, VK_SHADER_STAGE_VERTEX_BIT,
	                   0, sizeof(mvp), &mvp);

	VkDeviceSize vb_offset = 0;
	vkCmdBindVertexBuffers(cmd, 0, 1, &g_cube_vbuf, &vb_offset);
	vkCmdDraw(cmd, kCubeVertexCount, 1, 0, 0);

	// In-frame HUD (identity MVP → screen-space NDC), drawn over the cube and
	// identically into both eye tiles (zero disparity → sits at the screen
	// plane). Rebuilt into the persistently-mapped buffer each call; the
	// per-submit vkQueueWaitIdle below guarantees it isn't in flight.
	if (g_hud_vbuf != VK_NULL_HANDLE && g_hud_mapped != nullptr) {
		const uint32_t hud_n = build_hud(reinterpret_cast<CubeVertex *>(g_hud_mapped));
		if (hud_n > 0) {
			// The landscape per-eye tile is rotated onto the portrait panel, so
			// the HUD (drawn in tile-NDC) needs a compensating rotation to read
			// upright. Live-tunable:
			//   adb shell setprop debug.dxr.hud_rot 0|1|2|3   (×90° CCW)
			// Orientation-aware. Portrait needs rot=3/hflip=1 (tile rotated onto
			// the portrait panel); landscape needs no rotation. Defaults derived
			// from orientation; setprop (>=0) overrides for tuning (-1 = derived).
			//   debug.dxr.hud_rot 0|1|2|3, hud_hflip, hud_vflip
			const float rot_prop = get_prop_float("debug.dxr.hud_rot", -1.0f);
			const float hflip_prop = get_prop_float("debug.dxr.hud_hflip", -1.0f);
			// HUD orientation, per display rotation, calibrated on-device for the
			// preTransform=IDENTITY weave (LOXR-730/733). Portrait & normal
			// landscape: rot=0, vflip on. Reverse-landscape (disp_rot=3) needs a
			// 180° rotate with hflip (not vflip) to read upright at the top-left.
			// Verified on device at disp_rot 0/1/3; disp_rot=2 (reverse-portrait,
			// rarely reached) keeps the portrait-style values. setprop
			// debug.dxr.hud_rot/hud_hflip/hud_vflip (>=0) override per knob.
			//   disp_rot:  0(port) 1(land) 2(rev-port) 3(rev-land)
			//   hud_rot:    0       0       2           2
			//   hud_hflip:  0       0       0           1
			//   hud_vflip:  1       1       1           0
			static const int kHudRotForDisp[4]   = {0, 0, 2, 2};
			static const int kHudHflipForDisp[4] = {0, 0, 0, 1};
			static const int kHudVflipForDisp[4] = {1, 1, 1, 0};
			const int disp_rot_h = g_display_rotation.load(std::memory_order_relaxed) & 3;
			const int rot = ((rot_prop >= 0.0f) ? (int)rot_prop : kHudRotForDisp[disp_rot_h]) & 3;
			const bool hflip = (hflip_prop >= 0.0f) ? (hflip_prop != 0.0f)
			                                        : (kHudHflipForDisp[disp_rot_h] != 0);
			const float vflip_prop = get_prop_float("debug.dxr.hud_vflip", -1.0f);
			const bool vflip = (vflip_prop >= 0.0f) ? (vflip_prop != 0.0f)
			                                        : (kHudVflipForDisp[disp_rot_h] != 0);
			static int huddbg = 0;
			if ((huddbg++ % 120) == 0) {
				LOGI("HW_HUD: disp_rot=%d rot=%d hflip=%d vflip=%d",
				     disp_rot_h, rot, (int)hflip, (int)vflip);
			}
			const float cs[4] = {1.0f, 0.0f, -1.0f, 0.0f};
			const float sn[4] = {0.0f, 1.0f, 0.0f, -1.0f};
			const float c = cs[rot], s = sn[rot];
			Mat4 hud_mvp = mat4_identity();
			hud_mvp.m[0] = c;  hud_mvp.m[4] = -s;
			hud_mvp.m[1] = s;  hud_mvp.m[5] = c;
			if (hflip) { hud_mvp.m[0] = -hud_mvp.m[0]; hud_mvp.m[4] = -hud_mvp.m[4]; }
			if (vflip) { hud_mvp.m[1] = -hud_mvp.m[1]; hud_mvp.m[5] = -hud_mvp.m[5]; }
			vkCmdPushConstants(cmd, g_pipeline_layout, VK_SHADER_STAGE_VERTEX_BIT,
			                   0, sizeof(hud_mvp), &hud_mvp);
			VkDeviceSize hud_off = 0;
			vkCmdBindVertexBuffers(cmd, 0, 1, &g_hud_vbuf, &hud_off);
			vkCmdDraw(cmd, hud_n, 1, 0, 0);
		}
	}

	vkCmdEndRenderPass(cmd);
	vkEndCommandBuffer(cmd);

	VkSubmitInfo si = {};
	si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
	si.commandBufferCount = 1;
	si.pCommandBuffers = &cmd;
	VkResult res = vkQueueSubmit(g_vk_queue, 1, &si, VK_NULL_HANDLE);
	if (res == VK_SUCCESS) {
		vkQueueWaitIdle(g_vk_queue);
	}
	vkFreeCommandBuffers(g_vk_device, g_app_cmd_pool, 1, &cmd);

	DXR_HW_DBG_ONCE("record_draw: first successful triangle submit");
	return res == VK_SUCCESS;
}

void
handle_session_state(XrSessionState new_state)
{
	g_session_state = new_state;
	switch (new_state) {
	case XR_SESSION_STATE_READY: {
		XrSessionBeginInfo begin = {};
		begin.type = XR_TYPE_SESSION_BEGIN_INFO;
		begin.primaryViewConfigurationType = XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO;
		XrResult res = xrBeginSession(g_session, &begin);
		log_xr_result("xrBeginSession", res);
		if (res == XR_SUCCESS) {
			g_session_running = true;
		}
		break;
	}
	case XR_SESSION_STATE_STOPPING: {
		XrResult res = xrEndSession(g_session);
		log_xr_result("xrEndSession", res);
		g_session_running = false;
		break;
	}
	case XR_SESSION_STATE_EXITING:
	case XR_SESSION_STATE_LOSS_PENDING:
		g_exit_requested = true;
		break;
	default:
		break;
	}
}

void
poll_xr_events()
{
	for (;;) {
		XrEventDataBuffer ev = {};
		ev.type = XR_TYPE_EVENT_DATA_BUFFER;
		XrResult res = xrPollEvent(g_instance, &ev);
		if (res == XR_EVENT_UNAVAILABLE) {
			break;
		}
		if (res != XR_SUCCESS) {
			log_xr_result("xrPollEvent", res);
			break;
		}
		if (ev.type == XR_TYPE_EVENT_DATA_SESSION_STATE_CHANGED) {
			const auto *e = reinterpret_cast<const XrEventDataSessionStateChanged *>(&ev);
			if (e->session == g_session) {
				LOGI("session state -> %d", (int)e->state);
				handle_session_state(e->state);
			}
		} else if (ev.type == XR_TYPE_EVENT_DATA_INSTANCE_LOSS_PENDING) {
			LOGW("instance loss pending — exiting");
			g_exit_requested = true;
		}
	}
}

bool
render_frame()
{
	XrFrameWaitInfo wait_info = {};
	wait_info.type = XR_TYPE_FRAME_WAIT_INFO;
	XrFrameState frame_state = {};
	frame_state.type = XR_TYPE_FRAME_STATE;
	XrResult res = xrWaitFrame(g_session, &wait_info, &frame_state);
	if (res != XR_SUCCESS) {
		log_xr_result("xrWaitFrame", res);
		return false;
	}

	XrFrameBeginInfo begin_info = {};
	begin_info.type = XR_TYPE_FRAME_BEGIN_INFO;
	res = xrBeginFrame(g_session, &begin_info);
	if (res != XR_SUCCESS) {
		log_xr_result("xrBeginFrame", res);
		return false;
	}

	XrCompositionLayerProjectionView projection_views[kViewCount] = {};
	bool rendered = false;
	if (frame_state.shouldRender) {
		XrViewState view_state = {};
		view_state.type = XR_TYPE_VIEW_STATE;
		XrViewLocateInfo locate_info = {};
		locate_info.type = XR_TYPE_VIEW_LOCATE_INFO;
		locate_info.viewConfigurationType = XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO;
		locate_info.displayTime = frame_state.predictedDisplayTime;
		locate_info.space = g_app_space;

		XrView views[kViewCount] = {};
		for (uint32_t i = 0; i < kViewCount; ++i) {
			views[i].type = XR_TYPE_VIEW;
		}
		uint32_t located_view_count = 0;
		res = xrLocateViews(g_session, &locate_info, &view_state,
		                    kViewCount, &located_view_count, views);
		if (res == XR_SUCCESS && located_view_count == kViewCount) {
#ifdef XRT_DEBUG_ANDROID_VERBOSE
			// Throttle ~1Hz: dump per-view pose + FOV so calibration tests
			// (see android-bringup-checklist.md § B) can read them off
			// directly without instrumenting further.
			if ((g_frame_count % 60) == 0) {
				DXR_HW_DBG("views[L]: pos=(%.3f, %.3f, %.3f) quat=(%.3f, %.3f, %.3f, %.3f) "
				           "fov=(L=%.3f R=%.3f U=%.3f D=%.3f) rad",
				           views[0].pose.position.x, views[0].pose.position.y, views[0].pose.position.z,
				           views[0].pose.orientation.x, views[0].pose.orientation.y,
				           views[0].pose.orientation.z, views[0].pose.orientation.w,
				           views[0].fov.angleLeft, views[0].fov.angleRight,
				           views[0].fov.angleUp, views[0].fov.angleDown);
				DXR_HW_DBG("views[R]: pos=(%.3f, %.3f, %.3f) quat=(%.3f, %.3f, %.3f, %.3f)",
				           views[1].pose.position.x, views[1].pose.position.y, views[1].pose.position.z,
				           views[1].pose.orientation.x, views[1].pose.orientation.y,
				           views[1].pose.orientation.z, views[1].pose.orientation.w);
			}
#endif
			DXR_HW_DBG_ONCE("first xrLocateViews success");
			// L/R swap test (ghost diagnosis): when set, render the OTHER
			// eye's camera into each tile, swapping which view feeds which
			// eye. Live-tunable:
			//   adb shell setprop debug.dxr.leia.swap_lr 1   (0 = normal)
			const bool swap_lr = get_prop_float("debug.dxr.leia.swap_lr", 0.0f) != 0.0f;

			// Cache the tracked head-center (midpoint of the two eye poses)
			// for the on-screen marker + the Kotlin overlay readout. When the
			// runtime has a real face this moves with the head; otherwise it
			// sits at the static IPD fallback (~0,0,0.5).
			g_eye_x.store(0.5f * (views[0].pose.position.x + views[1].pose.position.x),
			              std::memory_order_relaxed);
			g_eye_y.store(0.5f * (views[0].pose.position.y + views[1].pose.position.y),
			              std::memory_order_relaxed);
			g_eye_z.store(0.5f * (views[0].pose.position.z + views[1].pose.position.z),
			              std::memory_order_relaxed);

			for (uint32_t i = 0; i < kViewCount; ++i) {
				XrSwapchainImageAcquireInfo acq = {};
				acq.type = XR_TYPE_SWAPCHAIN_IMAGE_ACQUIRE_INFO;
				uint32_t img_idx = 0;
				res = xrAcquireSwapchainImage(g_views[i].swapchain, &acq, &img_idx);
				if (res != XR_SUCCESS) {
					log_xr_result("xrAcquireSwapchainImage", res);
					break;
				}

				XrSwapchainImageWaitInfo wait_img = {};
				wait_img.type = XR_TYPE_SWAPCHAIN_IMAGE_WAIT_INFO;
				wait_img.timeout = XR_INFINITE_DURATION;
				res = xrWaitSwapchainImage(g_views[i].swapchain, &wait_img);
				if (res != XR_SUCCESS) {
					log_xr_result("xrWaitSwapchainImage", res);
					break;
				}

				// Render eye `src` into tile `i` (src != i when swapped).
				const uint32_t src = swap_lr ? (kViewCount - 1 - i) : i;
				record_draw(i, img_idx, views[src]);

				XrSwapchainImageReleaseInfo rel = {};
				rel.type = XR_TYPE_SWAPCHAIN_IMAGE_RELEASE_INFO;
				res = xrReleaseSwapchainImage(g_views[i].swapchain, &rel);
				if (res != XR_SUCCESS) {
					log_xr_result("xrReleaseSwapchainImage", res);
					break;
				}

				projection_views[i].type = XR_TYPE_COMPOSITION_LAYER_PROJECTION_VIEW;
				projection_views[i].pose = views[i].pose;
				projection_views[i].fov = views[i].fov;
				projection_views[i].subImage.swapchain = g_views[i].swapchain;
				projection_views[i].subImage.imageRect.offset = {0, 0};
				projection_views[i].subImage.imageRect.extent = {
				    (int32_t)g_views[i].width, (int32_t)g_views[i].height};
				projection_views[i].subImage.imageArrayIndex = 0;
			}
			rendered = (res == XR_SUCCESS);
		} else {
			log_xr_result("xrLocateViews", res);
		}
	}

	XrCompositionLayerProjection projection_layer = {};
	projection_layer.type = XR_TYPE_COMPOSITION_LAYER_PROJECTION;
	projection_layer.space = g_app_space;
	projection_layer.viewCount = kViewCount;
	projection_layer.views = projection_views;

	const XrCompositionLayerBaseHeader *layers[1] = {
	    reinterpret_cast<const XrCompositionLayerBaseHeader *>(&projection_layer),
	};

	XrFrameEndInfo end_info = {};
	end_info.type = XR_TYPE_FRAME_END_INFO;
	end_info.displayTime = frame_state.predictedDisplayTime;
	end_info.environmentBlendMode = XR_ENVIRONMENT_BLEND_MODE_OPAQUE;
	end_info.layerCount = rendered ? 1 : 0;
	end_info.layers = rendered ? layers : nullptr;

	res = xrEndFrame(g_session, &end_info);
	if (res != XR_SUCCESS) {
		log_xr_result("xrEndFrame", res);
		return false;
	}

	// Texture class: the runtime has now woven the cube into the shared image's
	// canvas sub-rect (and waited idle). Composite it with the 2D surround and
	// present to our own swapchain.
	present_frame();

	g_frame_count++;
	if ((g_frame_count % 60) == 0) {
		LOGI("frame %llu", (unsigned long long)g_frame_count);
	}
	return true;
}

void
destroy_session()
{
	if (g_session != XR_NULL_HANDLE) {
		XrResult res = xrDestroySession(g_session);
		log_xr_result("xrDestroySession", res);
		g_session = XR_NULL_HANDLE;
	}
}

void
destroy_vulkan()
{
	if (g_vk_device != VK_NULL_HANDLE) {
		// Drain the queue before tearing down — same defensive idiom as
		// the runtime's DP destroy path (B6 audit fix).
		vkDeviceWaitIdle(g_vk_device);
		vkDestroyDevice(g_vk_device, nullptr);
		g_vk_device = VK_NULL_HANDLE;
		g_vk_queue = VK_NULL_HANDLE;
		g_vk_queue_family = UINT32_MAX;
	}
	if (g_vk_instance != VK_NULL_HANDLE) {
		vkDestroyInstance(g_vk_instance, nullptr);
		g_vk_instance = VK_NULL_HANDLE;
	}
	g_vk_phys_device = VK_NULL_HANDLE;
}

void
destroy_instance()
{
	// Tear down in reverse-creation order: cmd_pool → space → swapchains
	// → session → Vulkan → instance. Doing it any other way invalidates
	// handles still referenced by the runtime / loader. Drain GPU
	// before per-view image destruction (audit B6).
	if (g_vk_device != VK_NULL_HANDLE) {
		vkDeviceWaitIdle(g_vk_device);
	}
	destroy_view_framebuffers(0);
	destroy_view_framebuffers(1);
	if (g_cube_vbuf != VK_NULL_HANDLE) {
		vkDestroyBuffer(g_vk_device, g_cube_vbuf, nullptr);
		g_cube_vbuf = VK_NULL_HANDLE;
	}
	if (g_cube_vbuf_mem != VK_NULL_HANDLE) {
		vkFreeMemory(g_vk_device, g_cube_vbuf_mem, nullptr);
		g_cube_vbuf_mem = VK_NULL_HANDLE;
	}
	destroy_pipeline();
	destroy_render_pass();
	destroy_cmd_pool();
	destroy_reference_space();
	destroy_swapchains();
	destroy_session();
	// After the session (and thus the compositor) is gone, nothing references
	// our shared image — tear down the present swapchain + shared image.
	destroy_present_swapchain();
	destroy_shared_image();
	destroy_vulkan();
	if (g_instance != XR_NULL_HANDLE) {
		XrResult res = xrDestroyInstance(g_instance);
		log_xr_result("xrDestroyInstance", res);
		g_instance = XR_NULL_HANDLE;
		g_system_id = XR_NULL_SYSTEM_ID;
	}
}

void
handle_cmd(struct android_app *app, int32_t cmd)
{
	switch (cmd) {
	case APP_CMD_INIT_WINDOW:
		LOGI("APP_CMD_INIT_WINDOW (window=%p)", app->window);
		// xrCreateInstance is deferred until the window exists because
		// some runtimes inspect the Activity surface state during create.
		// Idempotent — guarded by g_instance.
		if (g_instance == XR_NULL_HANDLE) {
			// Chain the bring-up steps — bail at the first failure
			// because each step depends on the previous one's outputs.
			bool brought_up =
			    create_instance(app) &&
			    query_system_and_graphics_reqs() &&
			    create_vulkan_instance() &&
			    pick_physical_device() &&
			    create_vulkan_device() &&
			    create_shared_image() &&       // texture class: weave target
			    create_session() &&            // chains the binding + output rect
			    create_present_swapchain() &&  // app-owned presentation
			    create_swapchains() &&
			    create_reference_space() &&
			    create_cmd_pool() &&
			    create_render_pass() &&
			    create_pipeline() &&
			    create_cube_vertex_buffer() &&
			    create_hud_buffer() &&
			    create_view_framebuffers(0) &&
			    create_view_framebuffers(1);
			if (brought_up) {
				LOGI("Bring-up chain complete; awaiting session state events.");
			} else {
				LOGW("Bring-up chain failed; see logs above.");
			}
		}
		break;
	case APP_CMD_TERM_WINDOW:
		LOGI("APP_CMD_TERM_WINDOW");
		break;
	case APP_CMD_GAINED_FOCUS:
		LOGI("APP_CMD_GAINED_FOCUS");
		break;
	case APP_CMD_LOST_FOCUS:
		LOGI("APP_CMD_LOST_FOCUS");
		break;
	case APP_CMD_DESTROY:
		LOGI("APP_CMD_DESTROY");
		destroy_instance();
		break;
	default:
		break;
	}
}

// On-device background toggle: a single tap anywhere flips g_bg_enabled.
// MonadoView is FLAG_NOT_FOCUSABLE, so touch events land in this
// NativeActivity input queue rather than being swallowed by the runtime's
// display window.
static int32_t
handle_input(struct android_app *app, AInputEvent *event)
{
	(void)app;
	if (AInputEvent_getType(event) == AINPUT_EVENT_TYPE_MOTION &&
	    (AMotionEvent_getAction(event) & AMOTION_EVENT_ACTION_MASK) ==
	        AMOTION_EVENT_ACTION_UP) {
		const bool now = !g_bg_enabled.load(std::memory_order_relaxed);
		g_bg_enabled.store(now, std::memory_order_relaxed);
		LOGI("background color %s (tap)", now ? "ON" : "OFF");
		return 1;  // consumed
	}
	return 0;
}

} // namespace

// ─── JNI bridge to the Kotlin overlay (MainActivity) ──────────────────────
// Underscores in the package/class become `_1` in JNI symbol names.
extern "C" JNIEXPORT void JNICALL
Java_com_displayxr_cube_1texture_1vk_1android_MainActivity_nativeSetBackgroundEnabled(
    JNIEnv * /*env*/, jobject /*thiz*/, jboolean enabled)
{
	g_bg_enabled.store(enabled == JNI_TRUE, std::memory_order_relaxed);
}

extern "C" JNIEXPORT jfloatArray JNICALL
Java_com_displayxr_cube_1texture_1vk_1android_MainActivity_nativeGetEye(
    JNIEnv *env, jobject /*thiz*/)
{
	jfloatArray arr = env->NewFloatArray(3);
	if (arr == nullptr) {
		return nullptr;
	}
	const jfloat v[3] = {
	    g_eye_x.load(std::memory_order_relaxed),
	    g_eye_y.load(std::memory_order_relaxed),
	    g_eye_z.load(std::memory_order_relaxed),
	};
	env->SetFloatArrayRegion(arr, 0, 3, v);
	return arr;
}

// Authoritative device orientation, pushed from MainActivity (onCreate +
// onConfigurationChanged) since the native window buffer reports a fixed
// orientation. Drives the orientation-aware HUD rotation + projection aspect.
extern "C" JNIEXPORT void JNICALL
Java_com_displayxr_cube_1texture_1vk_1android_MainActivity_nativeSetRotation(
    JNIEnv * /*env*/, jobject /*thiz*/, jint rotation)
{
	g_display_rotation.store(rotation & 3, std::memory_order_relaxed);
	LOGI("nativeSetRotation: %d (Surface.ROTATION_%d)", (int)rotation, (int)rotation * 90);
}

// True once xrCreateInstance has failed with RUNTIME_UNAVAILABLE — MainActivity
// polls this to prompt the user to launch DisplayXR first.
extern "C" JNIEXPORT jboolean JNICALL
Java_com_displayxr_cube_1texture_1vk_1android_MainActivity_nativeRuntimeUnavailable(
    JNIEnv * /*env*/, jobject /*thiz*/)
{
	return g_runtime_unavailable.load(std::memory_order_relaxed) ? JNI_TRUE : JNI_FALSE;
}

// True once the OpenXR instance is up (runtime reached) — lets MainActivity stop
// watching so the "runtime missing" dialog can't re-fire after a good start.
extern "C" JNIEXPORT jboolean JNICALL
Java_com_displayxr_cube_1texture_1vk_1android_MainActivity_nativeXrReady(
    JNIEnv * /*env*/, jobject /*thiz*/)
{
	return (g_instance != XR_NULL_HANDLE) ? JNI_TRUE : JNI_FALSE;
}

extern "C" void
android_main(struct android_app *app)
{
	LOGI("cube_texture_vk_android: android_main entered");
	DXR_HW_DBG("android_main: activity=%p vm=%p", (void *)app->activity->clazz,
	           (void *)app->activity->vm);
	g_app = app;  // texture-class helpers reach app->window through this
	app->onAppCmd = handle_cmd;
	app->onInputEvent = handle_input;

	if (!initialize_loader(app)) {
		LOGE("OpenXR loader init failed; the loop continues but no XR calls will work");
	}

	while (true) {
		// Drain Android lifecycle events. Block only when the OpenXR
		// session isn't actively rendering yet — once we hit
		// SYNCHRONIZED+, we want to spin the frame loop and only
		// non-blocking poll Android.
		const int poll_timeout_ms = g_session_running ? 0 : 250;
		int events;
		struct android_poll_source *source;
		while (ALooper_pollAll(poll_timeout_ms, nullptr, &events, (void **)&source) >= 0) {
			if (source != nullptr) {
				source->process(app, source);
			}
			if (app->destroyRequested != 0) {
				LOGI("destroyRequested — exiting android_main");
				destroy_instance();
				return;
			}
		}

		// (Orientation comes from MainActivity via nativeSetRotation — the
		// window buffer dims aren't a reliable rotation signal.)

		// OpenXR side: pump session state events and render a frame
		// when the session is in a rendering state.
		if (g_instance != XR_NULL_HANDLE) {
			poll_xr_events();
			if (g_exit_requested) {
				LOGI("XR exit requested — exiting android_main");
				destroy_instance();
				return;
			}
			if (g_session_running &&
			    (g_session_state == XR_SESSION_STATE_SYNCHRONIZED ||
			     g_session_state == XR_SESSION_STATE_VISIBLE ||
			     g_session_state == XR_SESSION_STATE_FOCUSED)) {
				render_frame();
			}
		}
	}
}
