// Copyright 2026, The DisplayXR Project and its contributors
// SPDX-License-Identifier: Apache-2.0

plugins {
    id 'com.android.library'
    id 'kotlin-android'
}

android {
    namespace 'org.displayxr.client'
    compileSdk project.sharedCompileSdk
    buildToolsVersion = buildToolsVersion

    defaultConfig {
        minSdkVersion project.sharedMinSdk
        targetSdkVersion project.sharedTargetSdk
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }
}

dependencies {
    implementation "androidx.startup:startup-runtime:1.1.1"
}
